/*
 *
 *  Shi Nai Jun (Mark Sea) CONFIDENTIAL
 * __________________
 *
 *  Shi Nai Jun (Mark Sea)
 *  All Rights Reserved.
 *
 * NOTICE:  All information and all copyrights contained herein are,
 * and remain the property of Shi Nai Jun, if any.
 * The intellectual and technical concepts contained herein are
 * proprietary to Shi Nai Jun and may be covered by patents, patents
 * in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Shi Nai Jun.
 *
 */
self.importScripts("lang/en.js")
self.importScripts("brokers.js")
var f6o={};var f6=f6o;
f6.J={
 atp:dict.m1,
 atq:dict.m2,
 aDO:dict.m3,
 Fu:dict.m4,
 rC:dict.m5,
 VR:dict.m6,
 anF:dict.m7,
 aDm:dict.m8,
 anB:dict.m9,
 aBJ:dict.m10,
 aBv:dict.m11,
 aCt:dict.m12,
 aBs:dict.m13,
 aCw:dict.m14,
 aoG:dict.m15,
 aCV:dict.m16,
 aCz:dict.m17,
 aBD:dict.m18,
 aBi:dict.m19,
 aDo:dict.m20,
 zH:dict.m21,
 anQ:dict.m22,
 aDz:dict.m23,
 aRJ:dict.m24,
 aRq:dict.m25,
 LM:dict.m26,
 IP:dict.m27,
 PB:dict.m28,
 aQd:dict.m29,
 alP:dict.m30,
 aqW:dict.m31,
 aCI:dict.m32,
 aEh:dict.m33,
 aDy:dict.m34,
 aCg:dict.m35,
 aOh:dict.m36,
 aBI:dict.m37,
 aPg:dict.m38,
 aBf:dict.m39,
 apJ:dict.m40,
 eC:dict.m41,
 aoB:dict.m42,
 aDt:dict.m43,
 aBS:dict.m44,
 aBy:dict.m45,
 aOd:dict.m46,
 Jg:dict.m47,
 atd:dict.m48,
 auA:dict.m49,
 auK:dict.m50,
 auZ:dict.m51,
 atR:dict.m52,
 atW:dict.m53,
 SH:dict.m54,
 pZ:dict.m55,
 atS:dict.m56,
 atV:dict.m57,
 aEM:dict.m58,
 aug:dict.m59,
 aDS:dict.m60,
 TJ:dict.m61,
 lM:dict.m62,
 uG:dict.m63,
 aOF:dict.m64,
 Kw:dict.m65,
 aSN:dict.m66,
 aob:dict.m67,
 wD:dict.m68,
 aiS:dict.m69,
 awk:dict.m70,
 JU:dict.m71,
 aVM:dict.m72,
 Ql:dict.m73,
 agi:dict.m74,
 aSw:dict.m75,
 agO:dict.m76,
 tu:dict.m77,
 Fo:dict.m78,
 ajw:dict.m79,
 amL:dict.m80,
 anw:dict.m81,
 amx:dict.m82,
 VP:dict.m83,
 Pb:dict.m84,
 uq:dict.m85,
 qr:dict.m86,
 aTK:dict.m87,
 aKA:dict.m88,
 ajd:dict.m89,
 ajm:dict.m90,
 auN:dict.m91,
 agE:dict.m92,
 HZ:dict.m93,
 asW:dict.m94,
 alK:dict.m95,
 aJC:dict.m96,
 SR:dict.m97,
 aes:dict.m98,
 oV:dict.m99,
 aKj:dict.m100,
 aIR:dict.m101,
 aPv:dict.m102,
 pJ:dict.m103,
 aig:dict.m104,
 aIX:dict.m105,
 aSp:dict.m106,
 aPO:dict.m107,
 PK:dict.m108,
 avH:dict.m109,
 Np:dict.m110,
 avh:dict.m111,
 adI:dict.m112,
 aOc:dict.m113,
 aMt:dict.m114,
 afR:dict.m115,
 abo:dict.m116,
 aDj:dict.m117,
 asj:dict.m118,
 aib:dict.m119,
 aKF:dict.m120,
 NP:dict.m121,
 Og:dict.m122,
 fa:dict.m123,
 io:dict.m124,
 hg:dict.m125,
 aGF:dict.m126,
 Qu:dict.m127,
 auO:dict.m128,
 Ip:dict.m129,
 aux:dict.m130,
 ayo:dict.m131,
 ays:dict.m132,
 axq:dict.m133,
 adP:dict.m134,
 nX:dict.m135,
 FE:dict.m136,
 aoW:dict.m137,
 aoh:dict.m138,
 anM:dict.m139,
 anA:dict.m140,
 atm:dict.m141,
 aSi:dict.m142,
 Yb:dict.m143,
 vr:dict.m144,
 xj:dict.m145,
 aII:dict.m146,
 aTc:dict.m147,
 aJe:dict.m148,
 aUc:dict.m149,
 aTx:dict.m150,
 aTr:dict.m151,
 Rm:dict.m152,
 YQ:dict.m153,
 aFn:dict.m154,
 ahv:dict.m155,
 aqP:dict.m156,
 aof:dict.m157,
 cq:dict.m158,
 lL:dict.m159,
 GR:dict.m160,
 arM:dict.m161,
 ann:dict.m162,
 aum:dict.m163,
 aoL:dict.m164,
 aoT:dict.m165,
 atQ:dict.m166,
 aoZ:dict.m167,
 avc:dict.m168,
 ho:dict.m169,
 aia:dict.m170,
 oi:dict.m171,
 VU:dict.m172,
 nA:dict.m173,
 CG:dict.m174,
 nK:dict.m175,
 pv:dict.m176,
 Hx:dict.m177,
 aiZ:dict.m178,
 Dg:dict.m179,
 NF:dict.m180,
 ER:dict.m181,
 Ii:dict.m182,
 aHb:dict.m183,
 wy:dict.m184,
 aJj:dict.m185,
 avA:dict.m186,
 aLn:dict.m187,
 aJS:dict.m188,
 ajh:dict.m189,
 agr:dict.m190,
 Tg:dict.m191,
 PH:dict.m192,
 acc:dict.m193,
 PE:dict.m194,
 UC:dict.m195,
 Ws:dict.m196,
 Xk:dict.m197,
 Hg:dict.m198,
 ue:dict.m199,
 aFV:dict.m200,
 arm:dict.m201,
 Fa:dict.m202,
 xO:dict.m203,
 asT:dict.m204,
 aod:dict.m205,
 SP:dict.m206,
 SS:dict.m207,
 aov:dict.m208,
 aBm:dict.m209,
 aBz:dict.m210,
 aCG:dict.m211,
 aCK:dict.m212,
 awE:dict.m213,
 awL:dict.m214,
 aDG:dict.m215,
 aMy:dict.m216,
 aNe:dict.m217,
 awS:dict.m218,
 awi:dict.m219,
 od:dict.m220,
 Ag:dict.m221,
 AA:dict.m222,
 aGj:dict.m223,
 awm:dict.m224,
 aM:dict.m225,
 aCs:dict.m226,
 aTs:dict.m227,
 ayH:dict.m228,
 SQ:dict.m229,
 ayI:dict.m230,
 aJT:dict.m231,
 aFr:dict.m232,
 Oc:dict.m233,
 pi:dict.m234,
 It:dict.m235,
 uw:dict.m236,
 Bj:dict.m237,
 By:dict.m238,
 atP:dict.m239,
 auM:dict.m240,
 YG:dict.m241,
 aUP:dict.m242,
 WN:dict.m243,
 aAt:dict.m244,
 aKX:dict.m245,
 asa:dict.m246,
 akM:dict.m247,
 aoJ:dict.m248,
 aLr:dict.m249,
 arx:dict.m250,
 axE:dict.m251,
 aTI:dict.m252,
 aTm:dict.m253,
 azS:dict.m254,
 azV:dict.m255,
 aiv:dict.m256,
 GI:dict.m257,
 aDU:dict.m258,
 aCy:dict.m259,
 avn:dict.m260,
 avR:dict.m261,
 aEJ:dict.m262,
 aBk:dict.m263,
 auk:dict.m264,
 ath:dict.m265,
 ajP:dict.m266,
 RX:dict.m267,
 auV:dict.m268,
 aoU:dict.m269,
 RD:dict.m270,
 aEr:dict.m271,
 aGR:dict.m272,
 awJ:dict.m273,
 awG:dict.m274,
 asv:dict.m275,
 asB:dict.m276,
 arX:dict.m277,
 atc:dict.m278,
 aMi:dict.m279,
 UZ:dict.m280,
 aNS:dict.m281,
 GG:dict.m282,
 aBu:dict.m283,
 aBA:dict.m284,
 aCM:dict.m285,
 apO:dict.m286
};f6.au=function(bF){var mX=new Date(Date.now()).toString()+" "+f6.J.atp+bF;console.error(mX)};f6.dq=function(bF){var mX=new Date(Date.now()).toString()+" "+bF;console.log(mX)};f6.fQ=function(bF){var mX=new Date(Date.now()).toString()+" "+bF;console.log(mX)};f6.ii={Dy:"cc_s_m",BA:"cc_e_m",Eu:"cc_w_m",aSh:"cc_s_m_b",aSd:"cc_e_m_b",aQW:"cc_w_m_b",aUq:".header",Co:".p",aLk:".message .close",arl:".message",GP:"transition",FH:"hidden",aDx:"fade",XP:"<br>",Wl:"padding-left",Hs:"5em",awb:'<div class="ui overlay success message transition hidden" style="position:fixed!important;overflow-y:scroll" id="cc_s_m">'+'<i class="close icon" style="font-size:1.5rem" id="cc_s_m_b"></i>'+'<div class="header">'+'Success Message'+'</div>'+'<p class="p"></p>'+'</div>',aDN:'<div class="ui overlay error message transition hidden" style="position:fixed!important;overflow-y:scroll" id="cc_e_m">'+'<i class="close icon" style="font-size:1.5rem" id="cc_e_m_b"></i>'+'<div class="header">'+'Error Message'+'</div>'+'<p class="p"></p>'+'</div>',atF:'<div class="ui overlay warning message transition hidden" style="position:fixed!important;overflow-y:scroll" id="cc_w_m">'+'<i class="close icon" style="font-size:1.5rem" id="cc_w_m_b"></i>'+'<div class="header">'+'Warning Message'+'</div>'+'<p class="p"></p>'+'</div>',BL:true,afN:true,ZN:"",ZW:function(bF){if(this.afN){$(document).attr(f6.T.iw,this.ZN)}else{$(document).attr(f6.T.iw,bF)}},ji:function(BL,CW,BU,Eb){if (typeof BL!=f6.K.ec) {
 return;
}if (typeof CW!=f6.K.O) {
 return;
}if (typeof BU!=f6.K.O) {
 return;
}if (typeof Eb!=f6.K.O) {
 return;
}this.BL=BL;this.ajl(CW,BU,Eb,this.Hs);this.ZN=$(document).attr(f6.T.iw);var G=this;window.addEventListener(f6.dF.aCx,function(){G.afN=true});window.addEventListener(f6.dF.aEW,function(){G.afN=false})},ajl:function(CW,BU,Eb,Hs){$("#"+CW).append(this.awb);$("#"+BU).append(this.aDN);$("#"+Eb).append(this.atF);$("#"+this.Dy).css(this.Wl,Hs);$("#"+this.BA).css(this.Wl,Hs);$("#"+this.Eu).css(this.Wl,Hs);var G=this;$(this.aLk).on(f6.dF.cA,function(){$(this).closest(G.arl).transition(G.aDx);$(this).closest(G.arl).find(G.Co).html("");$(document).attr(f6.T.iw,G.ZN)})},amj:function(){$("#"+this.Dy).addClass(this.GP);$("#"+this.Dy).addClass(this.FH);$("#"+this.Dy).find(this.Co).html("");$("#"+this.BA).addClass(this.GP);$("#"+this.BA).addClass(this.FH);$("#"+this.BA).find(this.Co).html("");$("#"+this.Eu).addClass(this.GP);$("#"+this.Eu).addClass(this.FH);$("#"+this.Eu).find(this.Co).html("")}};f6.gT=function(bF){if(f6.ii.BL){$("#"+f6.ii.Dy+" > "+f6.ii.Co).append(bF+f6.ii.XP);$("#"+f6.ii.Dy).removeClass(f6.ii.GP);$("#"+f6.ii.Dy).removeClass(f6.ii.FH);f6.ii.ZW(bF)}};f6.ah=function(bF){if(f6.ii.BL){$("#"+f6.ii.BA+" > "+f6.ii.Co).append(bF+f6.ii.XP);$("#"+f6.ii.BA).removeClass(f6.ii.GP);$("#"+f6.ii.BA).removeClass(f6.ii.FH);f6.ii.ZW(bF)}};f6.ck=function(bF){if(f6.ii.BL){$("#"+f6.ii.Eu+" > "+f6.ii.Co).append(bF+f6.ii.XP);$("#"+f6.ii.Eu).removeClass(f6.ii.GP);$("#"+f6.ii.Eu).removeClass(f6.ii.FH);f6.ii.ZW(bF)}};f6.dc={nJ:"e",MJ:"i_s",asR:"k_s",auh:"s_s",afM:"q_s",aer:"q_bt_s",Zz:"uq_s",aay:"as_s",anp:"o_s",arg:"mo_s",amR:"co_s",aqT:"mt_s",anr:"ct_s",aeA:"t_s",Zu:"ut_s",afH:"tm_s",Zk:"um_s",apn:"a_s",apA:"m_s",MW:"tk_s",aid:"y_s",QM:"rtk_s",Sd:"ss_s",atO:"gt_s",JF:"r_c",aml:"r_bt_c",ajM:"k_c",akN:"q_c",akg:"q_bt_c",Ru:"s_c",akp:"t_c",alu:"tm_c",amK:"a_c",akh:"m_c",OA:"ts_c",zm:"tf_c",OG:"rts_c",Ah:"rtf_c"};f6.hl=function(Xd,Ic){this.hn=Xd;this.ai=Ic};f6.hF=function(Ic){postMessage(new f6.hl(f6.dc.nJ,f6.J.atp+Ic))};f6.ma=function(Xd,Ic){postMessage(new f6.hl(Xd,Ic))};f6.Mw={PB:"i_i_ok",aDy:"g_o_b_g_ok",aOh:"s_o_b_ok",aPg:"l_o_b_ok",aDt:"g_h_q_ok",aBS:"d_o_p_ok",aBy:"d_o_a_ok",aOd:"r_s_d",atJ:"o_i_ok"};f6.cF={eJ:"t",gv:"b"};f6.fH=f6.cF.eJ;f6.aQY=false;f6.tL=false;f6.km={ll:1,aLR:2};f6.lb=f6.km.ll;f6.hC=true;f6.yd=false;f6.aM=10000;f6.gB=true;f6.zO={zE:"r",Yd:"m"};f6.rj={nL:"p",dw:"t",aqX:"m"};f6.eO={rm:"m",ci:"b",bX:"a",pq:"ba"};f6.K={L:"undefined",aLo:"[object Function]",O:"string",gn:"index",bE:"key",ec:"boolean",dP:"object",akX:"_blank",ge:"true",oJ:"false",aoO:"null",GX:"_",aqm:Number.MIN_SAFE_INTEGER,AO:Number.MAX_SAFE_INTEGER,aqf: -Number.MAX_VALUE,aSM:Number.MAX_VALUE,asu: -9999999999,aTy:9999999999};f6.T={Oe:"svg",H:"id",Is:"div",cT:"class",gY:"g",aaj:"url",acN:"clipPath",acr:"clip-path",jk:"rect",fM:"line",qC:"circle",fB:"x",fj:"y",pe:"dx",nt:"dy",df:"x1",de:"x2",dE:"y1",ds:"y2",gK:"cx",hw:"cy",jf:"r",eB:"width",eP:"height",fG:"opacity",cE:"fill",cr:"stroke",ir:"stroke-width",AI:"stroke-dasharray",dW:"transform",eQ:"translate",aRG:"rotate",jd:"text",fr:"font-size",mB:"text-anchor",fD:"start",aTA:"middle",hN:"end",oO:"drag",ug:"path",rs:"round",ai:"d",atX:"stroke-linejoin",auv:"stroke-linecap",ud:"none",aQS:"svg-container",aRt:"svg-content-responsive",aQz:"viewBox",aUg:"preserveAspectRatio",aTJ:"xMinYMin",aSW:"meet",DK:"active",ac:"cursor",Ay:"pointer",mO:"background-color",sO:"color",SN:"border",Ab:"display",alb:"block",aST:"important",yu:"style",DH:"src",aSL:"margin",iw:"title"};f6.aTg={aRf:"b",aSt:"d"};f6.dU={jL:"p",wa:"f",Qy:"f_o",Qb:"f_c",yB:"t",ti:"c",vH:"r",nH:"m_c",qv:"m_r",ta:"b_c",pV:"m_n",rv:"a"};f6.sG=function(aGx,nr,aFb){if (nr) {
 return null;
}return aGx.encode(aFb)};f6.kA={eE:"o",qW:"c",wd:"c_w_t",vt:"t",rv:"a"};f6.ca={aP:"o",cU:"h",al:"p",dR:"s",nj:"c",rn:"m",Cf:"t",Ro:"b",pE:"a",qh:"r",OS:"i",Ud:"f",OX:"l",sK:"k",aph:"d",vN:"z",cn:"e",tX:"x",tc:"v"};f6.ym={nj:"Cancelled",rn:"Rejected",aSs:"Unknown",cn:"Expired",al:"Order Pending",aP:"Open Trade",cU:"Trade Closed",dR:"Swap Done"};f6.dF={mX:"message",nJ:"error",eE:"open",qQ:"resize",cA:"click",aSu:"submit",aqS:"mousedown",aqi:"mousemove",Bw:"mouseup",aVC:"orientationchange",aJq:"change",azg:"customevent",Fd:"touchstart",aCx:"focus",aEW:"blur"};f6.aO={rd:11,lF:0,MF:1,Oq:2,Jo:3,Kv:4,Nl:5,MI:6,KA:7,IZ:8,OD:9,afh:10,mU:7,kj:0,xV:1,yE:2,yY:3,yw:4,xM:5,Fe:6};f6.xK=function(QK){if (typeof QK==f6.K.L||QK==null) {
 return false;
}var uW={};return QK&&uW.toString.call(QK)===f6.K.aLo;};f6.bp=function(ye){if (typeof ye==f6.K.L||ye==null) {
 return false;
}return!isNaN(parseFloat(ye))&&isFinite(ye);};f6.bi=function(ye){return!isNaN(ye)&&parseInt(Number(ye), 10)==ye&& !isNaN(parseInt(ye,10))};f6.cg=function(ahA){if (typeof ahA==f6.K.L||ahA==null) {
 return false;
}return ahA.constructor===Array};f6.su=function(Gl){
 if (typeof Gl!=f6.K.O) {
  return false;
 }if(Gl===""){return false}if(Gl==="inherit"){return false}if(Gl==="transparent"){return false}var Gu=document.createElement("img");Gu.style.color="rgb(0, 0, 0)";Gu.style.color=Gl;if(Gu.style.color!=="rgb(0, 0, 0)"){return true}Gu.style.color="rgb(255, 255, 255)";Gu.style.color=Gl;return Gu.style.color!=="rgb(255, 255, 255)";
};f6.asx=function(axY){return!isNaN(new Date(axY).getTime())};f6.JW=function(aql){var LH=[];for(var bE in aql){LH.push(encodeURIComponent(bE)+"="+encodeURIComponent(aql[bE]))}return LH.join("&")};f6.Qa=function(af){var jB=[];for(var i in af){if(af.hasOwnProperty(i)){if(typeof af[i]==f6.K.O){jB.push(i+': "'+af[i]+'"')}else if(f6.cg(af[i])){var Pr=JSON.parse(JSON.stringify(af[i]));for(var j in Pr){if(Pr[j]==null){Pr[j]="null"}}jB.push(i+': ['+Pr.join(', ')+']')}else{jB.push(i+": "+af[i])}}}return jB};f6.bc={jG:"s1",jJ:"s2",ko:"s3",lA:"s4",lh:"m1",lK:"m2",ni:"m3",kI:"m4",ow:"m5",kr:"m6",ky:"m7",kg:"h1",mr:"h2",nv:"h3",lm:"h4",nb:"h5",mc:"h6",nh:"h7",jZ:"d",kn:"w",kL:"m"};f6.cG={jG:"S5",jJ:"S10",ko:"S15",lA:"S30",lh:"M1",lK:"M2",ni:"M4",kI:"M5",ow:"M10",kr:"M15",ky:"M30",kg:"H1",mr:"H2",nv:"H3",lm:"H4",nb:"H6",mc:"H8",nh:"H12",jZ:"D",kn:"W",kL:"M"};f6.qt=function(bQ){if(bQ==f6.bc.jG){return 5}else if(bQ==f6.bc.jJ){return 10}else if(bQ==f6.bc.ko){return 15}else if(bQ==f6.bc.lA){return 30}else if(bQ==f6.bc.lh){return 60}else if(bQ==f6.bc.lK){return 120}else if(bQ==f6.bc.ni){return 240}else if(bQ==f6.bc.kI){return 300}else if(bQ==f6.bc.ow){return 600}else if(bQ==f6.bc.kr){return 900}else if(bQ==f6.bc.ky){return 1800}else if(bQ==f6.bc.kg){return 3600}else if(bQ==f6.bc.mr){return 7200}else if(bQ==f6.bc.nv){return 10800}else if(bQ==f6.bc.lm){return 14400}else if(bQ==f6.bc.nb){return 21600}else if(bQ==f6.bc.mc){return 28800}else if(bQ==f6.bc.nh){return 43200}else if(bQ==f6.bc.jZ){return 86400}else{return null}};f6.ws=function(bQ){if(bQ==f6.bc.jG){return f6.cG.jG}else if(bQ==f6.bc.jJ){return f6.cG.jJ}else if(bQ==f6.bc.ko){return f6.cG.ko}else if(bQ==f6.bc.lA){return f6.cG.lA}else if(bQ==f6.bc.lh){return f6.cG.lh}else if(bQ==f6.bc.lK){return f6.cG.lK}else if(bQ==f6.bc.ni){return f6.cG.ni}else if(bQ==f6.bc.kI){return f6.cG.kI}else if(bQ==f6.bc.ow){return f6.cG.ow}else if(bQ==f6.bc.kr){return f6.cG.kr}else if(bQ==f6.bc.ky){return f6.cG.ky}else if(bQ==f6.bc.kg){return f6.cG.kg}else if(bQ==f6.bc.mr){return f6.cG.mr}else if(bQ==f6.bc.nv){return f6.cG.nv}else if(bQ==f6.bc.lm){return f6.cG.lm}else if(bQ==f6.bc.nb){return f6.cG.nb}else if(bQ==f6.bc.mc){return f6.cG.mc}else if(bQ==f6.bc.nh){return f6.cG.nh}else if(bQ==f6.bc.jZ){return f6.cG.jZ}else if(bQ==f6.bc.kn){return f6.cG.kn}else if(bQ==f6.bc.kL){return f6.cG.kL}else{return null}};f6.Ou=function(et){if(et==f6.cG.jG){return f6.bc.jG}else if(et==f6.cG.jJ){return f6.bc.jJ}else if(et==f6.cG.ko){return f6.bc.ko}else if(et==f6.cG.lA){return f6.bc.lA}else if(et==f6.cG.lh){return f6.bc.lh}else if(et==f6.cG.lK){return f6.bc.lK}else if(et==f6.cG.ni){return f6.bc.ni}else if(et==f6.cG.kI){return f6.bc.kI}else if(et==f6.cG.ow){return f6.bc.ow}else if(et==f6.cG.kr){return f6.bc.kr}else if(et==f6.cG.ky){return f6.bc.ky}else if(et==f6.cG.kg){return f6.bc.kg}else if(et==f6.cG.mr){return f6.bc.mr}else if(et==f6.cG.nv){return f6.bc.nv}else if(et==f6.cG.lm){return f6.bc.lm}else if(et==f6.cG.nb){return f6.bc.nb}else if(et==f6.cG.mc){return f6.bc.mc}else if(et==f6.cG.nh){return f6.bc.nh}else if(et==f6.cG.jZ){return f6.bc.jZ}else if(et==f6.cG.kn){return f6.bc.kn}else if(et==f6.cG.kL){return f6.bc.kL}else{return null}};f6.rI=function(nr,agK){if (nr) {
 return null;
}return agK.replace(/\r?\n|\r/g,"").trim()};f6.Pw=function(bQ){if(bQ==f6.bc.kn||bQ==f6.bc.kL){return true}else{return false}};f6.aRc=function(bQ){if(bQ==f6.bc.kn){return true}else{return false}};f6.aTq=function(bQ){if(bQ==f6.bc.kL){return true}else{return false}};f6.Eh=function(bQ){if(bQ!=f6.bc.kn&&bQ!=f6.bc.kL&&bQ!=f6.bc.jG&&bQ!=f6.bc.jJ&&bQ!=f6.bc.ko&&bQ!=f6.bc.lA){return true}else{return false}};f6.We=function(bQ){if(bQ==f6.bc.jG){return true}else if(bQ==f6.bc.jJ){return true}else if(bQ==f6.bc.ko){return true}else if(bQ==f6.bc.lA){return true}else if(bQ==f6.bc.lh){return true}else if(bQ==f6.bc.lK){return true}else if(bQ==f6.bc.ni){return true}else if(bQ==f6.bc.kI){return true}else if(bQ==f6.bc.ow){return true}else if(bQ==f6.bc.kr){return true}else if(bQ==f6.bc.ky){return true}else if(bQ==f6.bc.kg){return true}else if(bQ==f6.bc.mr){return true}else if(bQ==f6.bc.nv){return true}else if(bQ==f6.bc.lm){return true}else if(bQ==f6.bc.nb){return true}else if(bQ==f6.bc.mc){return true}else if(bQ==f6.bc.nh){return true}else if(bQ==f6.bc.jZ){return true}else if(bQ==f6.bc.kn){return true}else if(bQ==f6.bc.kL){return true}else{return false}};f6.gl={rr:"%m-%d %H:%M",DG:"%y-%m-%d",lT:"%y-%m-%d %H:%M"};f6.PP=function(bQ){if(bQ==f6.bc.jG){return f6.gl.rr}else if(bQ==f6.bc.jJ){return f6.gl.rr}else if(bQ==f6.bc.ko){return f6.gl.rr}else if(bQ==f6.bc.lA){return f6.gl.rr}else if(bQ==f6.bc.lh){return f6.gl.rr}else if(bQ==f6.bc.lK){return f6.gl.rr}else if(bQ==f6.bc.ni){return f6.gl.rr}else if(bQ==f6.bc.kI){return f6.gl.rr}else if(bQ==f6.bc.ow){return f6.gl.rr}else if(bQ==f6.bc.kr){return f6.gl.rr}else if(bQ==f6.bc.ky){return f6.gl.rr}else if(bQ==f6.bc.kg){return f6.gl.rr}else if(bQ==f6.bc.mr){return f6.gl.rr}else if(bQ==f6.bc.nv){return f6.gl.DG}else if(bQ==f6.bc.lm){return f6.gl.DG}else if(bQ==f6.bc.nb){return f6.gl.DG}else if(bQ==f6.bc.mc){return f6.gl.DG}else if(bQ==f6.bc.nh){return f6.gl.DG}else if(bQ==f6.bc.jZ){return f6.gl.DG}else{return f6.gl.DG}};f6.bf={Hf:"Authorization",zP:"Bearer",agc:"Content-Type",aGr:"Accept-Datetime-Format",azR:"UNIX",agS:"application/json",ht:"application/json; charset=utf-8",hj:"POST",zc:"PUT",fW:"GET",iP:"json",aM:"timeout"};f6.aw={dA:1,eK:2,hm:3,jh:4,he:5,ip:6,Fc:7,Ht:8,DI:9,Gk:10};f6.ln={dA:"BUY",eK:"SELL",hm:"BUY LIMIT",jh:"SELL LIMIT",he:"BUY STOP",ip:"SELL STOP"};f6.Gv={dA:"B",eK:"S",hm:"B L",jh:"S L",he:"B S",ip:"S S"};f6.rZ=function(agK,nr,aFD){if (nr) {
 return null;
}return agK.charCodeAt(aFD)};f6.aPX=function(){return[f6.aw.dA,f6.aw.eK,f6.aw.hm,f6.aw.jh,f6.aw.he,f6.aw.ip]};f6.qO=function(ar){if(ar==f6.aw.dA){return f6.ln.dA}else if(ar==f6.aw.eK){return f6.ln.eK}else if(ar==f6.aw.hm){return f6.ln.hm}else if(ar==f6.aw.jh){return f6.ln.jh}else if(ar==f6.aw.he){return f6.ln.he}else if(ar==f6.aw.ip){return f6.ln.ip}else{return ""}};f6.wJ=function(ar){if(ar==f6.aw.dA){return f6.Gv.dA}else if(ar==f6.aw.eK){return f6.Gv.eK}else if(ar==f6.aw.hm){return f6.Gv.hm}else if(ar==f6.aw.jh){return f6.Gv.jh}else if(ar==f6.aw.he){return f6.Gv.he}else if(ar==f6.aw.ip){return f6.Gv.ip}else{return ""}};f6.aqK=function(ed){if(ed==f6.ln.dA){return f6.aw.dA}else if(ed==f6.ln.eK){return f6.aw.eK}else if(ed==f6.ln.hm){return f6.aw.hm}else if(ed==f6.ln.jh){return f6.aw.jh}else if(ed==f6.ln.he){return f6.aw.he}else if(ed==f6.ln.ip){return f6.aw.ip}else{return null}};f6.atr={uJ:"L",ze:"S"};f6.aSm={uJ:"Limit",ze:"Stop"};f6.LX={Xg:"L",wu:"H"};f6.mQ={FD:0,aqq:1,amN:2,avv:3,asU:4,anI:5,Mr:6};f6.aQO=function(vb){if(vb==f6.mQ.FD){return "Sunday"}else if(vb==f6.mQ.aqq){return "Monday"}else if(vb==f6.mQ.amN){return "Tuesday"}else if(vb==f6.mQ.avv){return "Wednesday"}else if(vb==f6.mQ.asU){return "Thursday"}else if(vb==f6.mQ.anI){return "Friday"}else if(vb==f6.mQ.Mr){return "Saturday"}else{return ""}};f6.Mj={afB:1,aja:2};f6.cf=function(agb,aCZ){var aHk=agb.callee.name;var alh=[];for(var i=0;i<agb.length;i += 1){alh.push(agb[i])}return f6.J.atq+aHk+"("+alh.join(", ")+")"+", "+f6.J.aDO+aCZ};f6.ih={ru:"n",ec:"b",O:"s",rS:"i"};f6.tW={ru:"Number",ec:"Boolean",O:"String",rS:"Integer"};f6.amM=function(iS){if(iS==f6.ih.ru){return f6.tW.ru}else if(iS==f6.ih.ec){return f6.tW.ec}else if(iS==f6.ih.O){return f6.tW.O}else if(iS==f6.ih.rS){return f6.tW.rS}else{return null}};f6.anm=function(OW){if(OW==f6.tW.ru){return f6.ih.ru}else if(OW==f6.tW.ec){return f6.ih.ec}else if(OW==f6.tW.O){return f6.ih.O}else if(OW==f6.tW.rS){return f6.ih.rS}else{return null}};f6.zY={lx:"shift"};f6.LQ={iL:"A",anq:"B"};f6.pn={KE:function(context){},Ll:function(context){},Kf:function(context){},YC:function(context){}};f6.Gg={ba:"fintechee.cloud",jz:"fintechee.cloud",jF:"fintechee.cloud"};f6.EP={ba:"",jz:"",jF:""};f6.Ck={ba:"https://",jz:"https://",jF:"https://"};f6.arw={aTv:"Channel-Sea",ama:"Chart-Coaster"};f6.RI={RR:"0"};f6.auJ=function(){return[f6.bc.lh,f6.bc.kI,f6.bc.kr,f6.bc.ky,f6.bc.kg,f6.bc.lm,f6.bc.jZ,f6.bc.kn,f6.bc.kL]};f6.anT=function(){return f6.bc.lh};f6.aEy=function(){return[500,1000,2000,5000,10000,20000,50000,100000,1000000]};f6.ads={ba:"channel-sea.cc",jz:"channel-sea.cc",jF:"channel-sea.cc"};f6.aJ={ba:"fe",jz:"od",jF:"ol"};f6.acM={ba:"Fintechee Demo",jz:"Oanda Demo (Browser must be Firefox)",jF:"Oanda Live (Browser must be Firefox)"};f6.Ma={ba:"Fintechee Demo",jz:"Oanda Demo",jF:"Oanda Live"};f6.oB={ba:"c",AR:"o"};f6.Ij=[];f6.Ij[f6.aJ.ba]=f6.oB.ba;f6.Ij[f6.aJ.jz]=f6.oB.AR;f6.Ij[f6.aJ.jF]=f6.oB.AR;f6.bx=[];f6.bx[f6.aJ.ba]={bh:[],Rc:false,C:f6.aJ.ba,adL:f6.Ck.ba+f6.Gg.ba+f6.EP.ba,acP:f6.Ck.ba+f6.Gg.ba+f6.EP.ba,XV:f6.Ck.ba+f6.Gg.ba+f6.EP.ba,VD:f6.Ck.ba+f6.Gg.ba+f6.EP.ba,UI:f6.Ck.ba+f6.ads.ba,Wb:"/images/logo.png",np:["EUR/USD"],hH:"Technology Service Provider",qI:21,jN:21,qV:100,oT:true,bz:"USD",cz:100000,aN:100,re:50,qZ:0.01,oH:false,uz:null,tE:null,ee: -1,nS:false,oY:false,kD:false,pg:false,qX:0,UK:"/getSS",Ts:"/signinByTradeToken",TA:"/signinToTrade",TK:"/signinToWatch",RN:"/quickRegister",RS:"/register",Qr:"/changePassword",SL:"/sendResetPwMail",Nh:"/resetPassword",Tk:"/getDefaultAccForInvestor",Qk:"/setWatchable",Ra:"/setNotWatchable",MY:"/acceptOneClick",Sl:"/rejectOneClick",PN:"/triggerMfa",RA:"/setMfaEnabled",QG:"/setMfaDisabled",NG:"/verifyMfa"};f6.mg={eJ:"TRADE",rQ:"INVESTOR"};f6.aiN=[];f6.ayf=function(bb){f6.aiN=bb};f6.Jq=function(){return f6.aiN};f6.yx=function(C,F){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null&&f6.cg(f6.bx[C].bh)){var cP=null;for(var i in f6.bx[C].bh){if(f6.bx[C].bh[i].F==F){if(typeof f6.bx[C].bh[i].dw==f6.K.O){return f6.mg.eJ}else if(typeof f6.bx[C].bh[i].fk==f6.K.O){return f6.mg.rQ}else{return f6.mg.rQ}}}return f6.mg.rQ}else{return f6.mg.rQ}};f6.kR=function(C,F){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null&&f6.cg(f6.bx[C].bh)){var cP=null;for(var i in f6.bx[C].bh){if(f6.bx[C].bh[i].F==F){cP={dw:f6.bx[C].bh[i].dw,fk:f6.bx[C].bh[i].fk,fI:f6.bx[C].bh[i].fI};break}}return cP}else{return null}};f6.ph=function(C,F){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null&&f6.cg(f6.bx[C].bh)){var R=null;for(var i in f6.bx[C].bh){if(f6.bx[C].bh[i].F==F){R=f6.bx[C].bh[i].R;break}}return R}else{return null}};f6.aho=function(C,F,R){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null&&f6.cg(f6.bx[C].bh)){for(var i in f6.bx[C].bh){if(f6.bx[C].bh[i].F==F){f6.bx[C].bh[i].R=R;return true}}}return false};f6.la=function(C,F){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null&&f6.cg(f6.bx[C].bh)){var an=null;for(var i in f6.bx[C].bh){if(f6.bx[C].bh[i].F==F){an={dw:f6.bx[C].bh[i].dw,fk:f6.bx[C].bh[i].fk};break}}if(an!=null){if(an.dw!=null){return f6.mg.eJ+" "+an.dw}else if(an.fk!=null){return f6.mg.rQ+" "+an.fk}else{return f6.mg.rQ}}else{return f6.mg.rQ}}else{return f6.mg.rQ}};f6.aDv=function(){var bh=[];for(var i in f6.bx){for(var j in f6.bx[i].bh){bh.push({C:f6.bx[i].bh[j].C,F:f6.bx[i].bh[j].F})}}return bh};f6.Oo=function(C,F,dw,fk,fI,R){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null&&f6.cg(f6.bx[C].bh)){for(var i in f6.bx[C].bh){if(f6.bx[C].bh[i].F==F){f6.bx[C].bh[i]={C:C,F:F,dw:dw,fk:fk,fI:fI,R:R};return f6.bx[C].bh[i]}}f6.bx[C].bh.push({C:C,F:F,dw:dw,fk:fk,fI:fI,R:R});return true}return false};f6.Gq=function(C,F){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null&&f6.cg(f6.bx[C].bh)){for(var i in f6.bx[C].bh){if(f6.bx[C].bh[i].F==F){f6.bx[C].bh.splice(parseInt(i, 10),1);return true}}}return false};f6.mt=function(C){if(typeof f6.Ij[C]!=f6.K.L){return f6.Ij[C]}else{return f6.oB.ba}};f6.ark=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].adL}else{return f6.bx[f6.aJ.ba].adL}};f6.abp=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].acP}else{return f6.bx[f6.aJ.ba].acP}};f6.Oj=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].XV}else{return f6.bx[f6.aJ.ba].XV}};f6.ea=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].VD}else{return f6.bx[f6.aJ.ba].VD}};f6.apj=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].UI}else{return f6.bx[f6.aJ.ba].UI}};f6.CR=function(){var fU=[];for(var i in f6.bx){fU.push(f6.bx[i].C)}return fU};f6.ei=function(C){for(var i in f6.aJ){if(C==f6.aJ[i]){return f6.Ma[i]}}return null};f6.Pu=function(C){for(var i in f6.aJ){if(C==f6.aJ[i]){return f6.acM[i]}}return null};f6.yg=function(bk){for(var i in f6.Ma){if(bk==f6.Ma[i]){return f6.aJ[i]}}return null};f6.QT=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Wb}else{return f6.bx[f6.aJ.ba].Wb}};f6.aRy=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].np}else{return f6.bx[f6.aJ.ba].np}};f6.aEv=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].hH}else{return f6.bx[f6.aJ.ba].hH}};f6.aTY=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].qI}else{return f6.bx[f6.aJ.ba].qI}};f6.aTH=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].jN}else{return f6.bx[f6.aJ.ba].jN}};f6.aQj=function(){var IC=[];for(var i in f6.bx){for(var j in f6.bx[i].bh){IC.push({C:f6.bx[i].bh[j].C,F:f6.bx[i].bh[j].F,jN:f6.bx[i].jN})}}return IC};f6.aQe=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].qV}else{return f6.bx[f6.aJ.ba].qV}};f6.asO=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].oT}else{return f6.bx[f6.aJ.ba].oT}};f6.Jx=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].bz}else{return f6.bx[f6.aJ.ba].bz}};f6.mY=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].cz}else{return f6.bx[f6.aJ.ba].cz}};f6.wZ=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].aN}else{return f6.bx[f6.aJ.ba].aN}};f6.aKp=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].re}else{return f6.bx[f6.aJ.ba].re}};f6.Vf=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].qZ}else{return f6.bx[f6.aJ.ba].qZ}};f6.asJ=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].oH}else{return f6.bx[f6.aJ.ba].oH}};f6.aQV=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].uz}else{return f6.bx[f6.aJ.ba].uz}};f6.aPo=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].tE}else{return f6.bx[f6.aJ.ba].tE}};f6.IE=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].ee}else{return f6.bx[f6.aJ.ba].ee}};f6.lJ=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].nS}else{return f6.bx[f6.aJ.ba].nS}};f6.Ve=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].oY}else{return f6.bx[f6.aJ.ba].oY}};f6.aSO=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].kD}else{return f6.bx[f6.aJ.ba].kD}};f6.yO=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].pg}else{return f6.bx[f6.aJ.ba].pg}};f6.SZ=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].qX}else{return f6.bx[f6.aJ.ba].qX}};f6.aOS=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Ts}else{return f6.bx[f6.aJ.ba].Ts}};f6.aPI=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].TA}else{return f6.bx[f6.aJ.ba].TA}};f6.aPG=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].TK}else{return f6.bx[f6.aJ.ba].TK}};f6.aPV=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].RN}else{return f6.bx[f6.aJ.ba].RN}};f6.aox=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].RS}else{return f6.bx[f6.aJ.ba].RS}};f6.aDT=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Qr}else{return f6.bx[f6.aJ.ba].Qr}};f6.aPj=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].SL}else{return f6.bx[f6.aJ.ba].SL}};f6.aPa=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Nh}else{return f6.bx[f6.aJ.ba].Nh}};f6.aQv=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Tk}else{return f6.bx[f6.aJ.ba].Tk}};f6.aPE=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Qk}else{return f6.bx[f6.aJ.ba].Qk}};f6.aPy=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Ra}else{return f6.bx[f6.aJ.ba].Ra}};f6.aED=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].MY}else{return f6.bx[f6.aJ.ba].MY}};f6.aOY=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Sl}else{return f6.bx[f6.aJ.ba].Sl}};f6.aOC=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].PN}else{return f6.bx[f6.aJ.ba].PN}};f6.aQi=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].RA}else{return f6.bx[f6.aJ.ba].RA}};f6.aPx=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].QG}else{return f6.bx[f6.aJ.ba].QG}};f6.aNA=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].NG}else{return f6.bx[f6.aJ.ba].NG}};f6.aPb=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].Rc}else{return f6.bx[f6.aJ.ba].Rc}};f6.EO=function(C,ey){if(typeof f6.bx[C]!=f6.K.L){f6.bx[C].Rc=ey}};f6.aPw=function(C){if(typeof f6.bx[C]!=f6.K.L){return f6.bx[C].UK}else{return f6.bx[f6.aJ.ba].UK}};f6.aoz=function(C){var G=this;return new Promise(function(cp,aT){var bk=f6.ei(C);var bJ=function(aK){var bF=null;if(typeof aK.brokerName==f6.K.O&&aK.brokerName==C&&typeof aK.defaultSymbolNames==f6.K.O&&typeof aK.desc==f6.K.O&&typeof aK.startEndHour==f6.K.O&&typeof aK.swapCalcHour==f6.K.O&&typeof aK.pendingOdrsOpenTrdsNumLimit==f6.K.O&&typeof aK.demoMode==f6.K.O&&typeof aK.currency==f6.K.O&&typeof aK.lotsUnit==f6.K.O&&typeof aK.toFixed==f6.K.O&&typeof aK.commentLengthLimit==f6.K.O&&typeof aK.lotsPerOrder==f6.K.O&&typeof aK.externalData==f6.K.O&&typeof aK.externalURL==f6.K.O&&typeof aK.externalTk==f6.K.O&&typeof aK.externalMode==f6.K.O&&typeof aK.spreadBetting==f6.K.O&&typeof aK.brokerless==f6.K.O&&typeof aK.creditsOnboard==f6.K.O&&typeof aK.localHostMode==f6.K.O){try{
 var np=JSON.parse(aK.defaultSymbolNames);if(f6.cg(np)){for(var i in np){if(typeof np[i]!=f6.K.O){throw new Error(f6.J.od+"(defaultSymbolNames, "+bk+", "+aK.defaultSymbolNames+")")}}}else{throw new Error(f6.J.od+"(defaultSymbolNames, "+bk+", "+aK.defaultSymbolNames+")")}var qI=null;if(f6.bi(aK.startEndHour)){qI=parseInt(aK.startEndHour, 10)}else{throw new Error(f6.J.od+"(startEndHour, "+bk+", "+aK.startEndHour+")")}var jN=null;if(f6.bi(aK.swapCalcHour)){jN=parseInt(aK.swapCalcHour, 10)}else{throw new Error(f6.J.od+"(swapCalcHour, "+bk+", "+aK.swapCalcHour+")")}var qV=null;if(f6.bi(aK.pendingOdrsOpenTrdsNumLimit)){qV=parseInt(aK.pendingOdrsOpenTrdsNumLimit, 10)}else{throw new Error(f6.J.od+"(pendingOdrsOpenTrdsNumLimit, "+bk+", "+aK.pendingOdrsOpenTrdsNumLimit+")")}var oT=null;if(aK.demoMode==f6.K.ge){oT=true}else if(aK.demoMode==f6.K.oJ){oT=false}else{throw new Error(f6.J.od+"(demoMode, "+bk+", "+aK.demoMode+")")}var cz=null;if(f6.bp(aK.lotsUnit)){cz=parseFloat(aK.lotsUnit)}else{throw new Error(f6.J.od+"(lotsUnit, "+bk+", "+aK.lotsUnit+")")}var aN=null;if(f6.bi(aK.toFixed)){aN=parseInt(aK.toFixed, 10)}else{throw new Error(f6.J.od+"(toFixed, "+bk+", "+aK.toFixed+")")}var re=null;if(f6.bi(aK.commentLengthLimit)){re=parseInt(aK.commentLengthLimit, 10)}else{throw new Error(f6.J.od+"(commentLengthLimit, "+bk+", "+aK.commentLengthLimit+")")}var qZ=null;if(f6.bp(aK.lotsPerOrder)){qZ=parseFloat(aK.lotsPerOrder)}else{throw new Error(f6.J.od+"(lotsPerOrder, "+bk+", "+aK.lotsPerOrder+")")}var oH=null;if(aK.externalData==f6.K.ge){oH=true}else if(aK.externalData==f6.K.oJ){oH=false}else{throw new Error(f6.J.od+"(externalData, "+bk+", "+aK.externalData+")")}var ee=null;if(f6.bi(aK.externalMode)){ee=parseInt(aK.externalMode, 10)}else{throw new Error(f6.J.od+"(toFixed, "+bk+", "+aK.externalMode+")")}var nS=null;if(aK.spreadBetting==f6.K.ge){nS=true}else if(aK.spreadBetting==f6.K.oJ){nS=false}else{throw new Error(f6.J.od+"(spreadBetting, "+bk+", "+aK.spreadBetting+")")}var oY=null;if(aK.brokerless==f6.K.ge){oY=true}else if(aK.brokerless==f6.K.oJ){oY=false}else{throw new Error(f6.J.od+"(brokerless, "+bk+", "+aK.brokerless+")")}var kD=null;if(aK.creditsOnboard==f6.K.ge){kD=true}else if(aK.creditsOnboard==f6.K.oJ){kD=false}else{throw new Error(f6.J.od+"(creditsOnboard, "+bk+", "+aK.creditsOnboard+")")}var pg=null;if(aK.localHostMode==f6.K.ge){pg=true}else if(aK.localHostMode==f6.K.oJ){pg=false}else{throw new Error(f6.J.od+"(localHostMode, "+bk+", "+aK.localHostMode+")")}var qX=0;if(f6.bi(aK.customMode)){qX=parseInt(aK.customMode, 10)}f6.bx[C].np=np;f6.bx[C].hH=aK.desc;f6.bx[C].qI=qI;f6.bx[C].jN=jN;f6.bx[C].qV=qV;f6.bx[C].oT=oT;f6.bx[C].bz=aK.currency;f6.bx[C].cz=cz;f6.bx[C].aN=aN;f6.bx[C].re=re;f6.bx[C].qZ=qZ;f6.bx[C].oH=oH;f6.bx[C].uz=aK.externalURL;f6.bx[C].tE=aK.externalTk;f6.bx[C].ee=ee;f6.bx[C].nS=nS;f6.bx[C].oY=oY;f6.bx[C].kD=kD;f6.bx[C].pg=pg;f6.bx[C].qX=qX;f6.EO(C,true);cp();
}catch(e){f6.EO(C,true);f6.ah(e.message);f6.au(e.message);aT()}}else{f6.EO(C,true);bF=f6.J.od+"("+bk+")";f6.ah(bF);f6.au(bF);aT()}};$.ajax({url:f6.ea(C)+f6.aPw(C),type:f6.bf.hj,data:JSON.stringify({brokerName:C}),contentType:f6.bf.ht,dataType:f6.bf.iP,timeout:f6.aM,success:bJ,error:function(du,ey,bF){if(ey===f6.bf.aM){f6.EO(C,true);f6.ah(f6.J.aM+"("+bk+")");f6.au(f6.J.aM+"("+bk+")")}else{f6.EO(C,true);f6.ah(bF+"("+bk+")");f6.au(bF+"("+bk+")")}aT()}})})};f6.aOI=function(){var ib=[];for(var i in f6.bx){ib.push({C:f6.bx[i].C,np:f6.bx[i].np,hH:f6.bx[i].hH,qI:f6.bx[i].qI,jN:f6.bx[i].jN,qV:f6.bx[i].qV,oT:f6.bx[i].oT,bz:f6.bx[i].bz,cz:f6.bx[i].cz,aN:f6.bx[i].aN,re:f6.bx[i].re,qZ:f6.bx[i].qZ,oH:f6.bx[i].oH,uz:f6.bx[i].uz,tE:f6.bx[i].tE,ee:f6.bx[i].ee,nS:f6.bx[i].nS,oY:f6.bx[i].oY,kD:f6.bx[i].kD,pg:f6.bx[i].pg,qX:f6.bx[i].qX})}return ib};f6.awQ=function(ib){for(var i in ib){var C=ib[i].C;if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null){f6.bx[C].np=ib[i].np;f6.bx[C].hH=ib[i].hH;f6.bx[C].qI=ib[i].qI;f6.bx[C].jN=ib[i].jN;f6.bx[C].qV=ib[i].qV;f6.bx[C].oT=ib[i].oT;f6.bx[C].bz=ib[i].bz;f6.bx[C].cz=ib[i].cz;f6.bx[C].aN=ib[i].aN;f6.bx[C].re=ib[i].re;f6.bx[C].qZ=ib[i].qZ;f6.bx[C].oH=ib[i].oH;f6.bx[C].uz=ib[i].uz;f6.bx[C].tE=ib[i].tE;f6.bx[C].ee=ib[i].ee;f6.bx[C].nS=ib[i].nS;f6.bx[C].oY=ib[i].oY;f6.bx[C].kD=ib[i].kD;f6.bx[C].pg=ib[i].pg;f6.bx[C].qX=ib[i].qX;f6.EO(C,true)}}};f6.ET=function(C){var eI=null;for(var i in f6.bx){if(C==f6.bx[i].C){eI={np:f6.bx[C].np,hH:f6.bx[C].hH,qI:f6.bx[C].qI,jN:f6.bx[C].jN,qV:f6.bx[C].qV,oT:f6.bx[C].oT,bz:f6.bx[C].bz,cz:f6.bx[C].cz,aN:f6.bx[C].aN,re:f6.bx[C].re,qZ:f6.bx[C].qZ,oH:f6.bx[C].oH,uz:f6.bx[C].uz,tE:f6.bx[C].tE,ee:f6.bx[C].ee,nS:f6.bx[C].nS,oY:f6.bx[C].oY,kD:f6.bx[C].kD,pg:f6.bx[C].pg,qX:f6.bx[C].qX};break}}return eI};f6.Qx=function(C,eI){if(typeof f6.bx[C]!=f6.K.L&&f6.bx[C]!=null){f6.bx[C].np=eI.np;f6.bx[C].hH=eI.hH;f6.bx[C].qI=eI.qI;f6.bx[C].jN=eI.jN;f6.bx[C].qV=eI.qV;f6.bx[C].oT=eI.oT;f6.bx[C].bz=eI.bz;f6.bx[C].cz=eI.cz;f6.bx[C].aN=eI.aN;f6.bx[C].re=eI.re;f6.bx[C].qZ=eI.qZ;f6.bx[C].oH=eI.oH;f6.bx[C].uz=eI.uz;f6.bx[C].tE=eI.tE;f6.bx[C].ee=eI.ee;f6.bx[C].nS=eI.nS;f6.bx[C].oY=eI.oY;f6.bx[C].kD=eI.kD;f6.bx[C].pg=eI.pg;f6.bx[C].qX=eI.qX}};f6.aRB=function(){var mI=0;for(var i in f6.bx){mI += 1}return mI};f6.aRV=function(){return f6.aJ.ba};f6.Jr=function(){try{if(typeof brokerDomain!=f6.K.L){for(var i in brokerDomain){if(typeof f6.Gg[i]==f6.K.L){f6.Gg[i]=brokerDomain[i]}else{throw new Error(f6.J.Ag+"(brokerDomain."+i+")")}}}if(typeof brokerPort!=f6.K.L){for(var i in brokerPort){if(typeof f6.EP[i]==f6.K.L){f6.EP[i]=brokerPort[i]}else{throw new Error(f6.J.Ag+"(brokerPort."+i+")")}}}if(typeof brokerProtocol!=f6.K.L){for(var i in brokerProtocol){if(typeof f6.Ck[i]==f6.K.L){f6.Ck[i]=brokerProtocol[i]}else{throw new Error(f6.J.Ag+"(brokerProtocol."+i+")")}}}if(typeof shopDomain!=f6.K.L){for(var i in shopDomain){if(typeof f6.ads[i]==f6.K.L){f6.ads[i]=shopDomain[i]}else{throw new Error(f6.J.Ag+"(shopDomain."+i+")")}}}if(typeof brokerName!=f6.K.L){for(var i in brokerName){if(typeof f6.aJ[i]==f6.K.L){f6.aJ[i]=brokerName[i]}else{throw new Error(f6.J.Ag+"(brokerName."+i+")")}}}if(typeof signInShownBrokerName!=f6.K.L){for(var i in signInShownBrokerName){if(typeof f6.acM[i]==f6.K.L){f6.acM[i]=signInShownBrokerName[i]}else{throw new Error(f6.J.Ag+"(signInShownBrokerName."+i+")")}}}if(typeof shownBrokerName!=f6.K.L){for(var i in shownBrokerName){if(typeof f6.Ma[i]==f6.K.L){f6.Ma[i]=shownBrokerName[i]}else{throw new Error(f6.J.Ag+"(shownBrokerName."+i+")")}}}if(typeof brokerCtx!=f6.K.L){for(var i in brokerCtx){if(typeof f6.bx[i]==f6.K.L){f6.bx[i]={bh:[],Rc:false,C:brokerCtx[i].brokerName,adL:brokerCtx[i].dataStreamURL,acP:brokerCtx[i].dataBaseURL,XV:brokerCtx[i].orderStreamURL,VD:brokerCtx[i].orderBaseURL,UI:brokerCtx[i].shopURL,Wb:brokerCtx[i].logoURL,np:brokerCtx[i].defaultSymbolNames,hH:brokerCtx[i].desc,qI:brokerCtx[i].startEndHour,jN:brokerCtx[i].swapCalcHour,qV:brokerCtx[i].pendingOdrsOpenTrdsNumLimit,oT:brokerCtx[i].demoMode,bz:brokerCtx[i].currency,cz:brokerCtx[i].lotsUnit,aN:brokerCtx[i].toFixed,re:brokerCtx[i].commentLengthLimit,qZ:brokerCtx[i].lotsPerOrder,oH:brokerCtx[i].externalData,uz:brokerCtx[i].externalURL,tE:brokerCtx[i].externalTk,ee:brokerCtx[i].externalMode,nS:brokerCtx[i].nS,oY:brokerCtx[i].oY,kD:brokerCtx[i].kD,pg:brokerCtx[i].pg,qX:brokerCtx[i].qX,UK:f6.bx[f6.aJ.ba].UK,Ts:f6.bx[f6.aJ.ba].Ts,TA:f6.bx[f6.aJ.ba].TA,TK:f6.bx[f6.aJ.ba].TK,RN:f6.bx[f6.aJ.ba].RN,RS:f6.bx[f6.aJ.ba].RS,Qr:f6.bx[f6.aJ.ba].Qr,SL:f6.bx[f6.aJ.ba].SL,Nh:f6.bx[f6.aJ.ba].Nh,Tk:f6.bx[f6.aJ.ba].Tk,Qk:f6.bx[f6.aJ.ba].Qk,Ra:f6.bx[f6.aJ.ba].Ra,MY:f6.bx[f6.aJ.ba].MY,Sl:f6.bx[f6.aJ.ba].Sl,PN:f6.bx[f6.aJ.ba].PN,RA:f6.bx[f6.aJ.ba].RA,QG:f6.bx[f6.aJ.ba].QG,NG:f6.bx[f6.aJ.ba].NG};f6.Ij[i]=f6.oB.ba}else{throw new Error(f6.J.Ag+"(brokerCtx."+i+")")}}}return true}catch(e){f6.ah(e.message);f6.au(e.message);return false}};f6.zC="FINTECHEE";self.addEventListener(f6.dF.nJ,function(bB){});self.addEventListener(f6.dF.mX,function(bB){if(bB.data.hn==f6.dc.MJ){f6.Jr();f6.fH=bB.data.ai.iA;f6o.jX[f6.oB.ba].Us(f6o.ev);f6o.jX[f6.oB.ba].XN(f6o.gE);if(typeof Ax!=f6.K.L&&Ax!=null){f6o.jX[f6.oB.AR].Us(Ax)}f6o.jX[f6.oB.AR].XN(f6o.gE);f6o.gE.azz(f6o.jX);f6.ma(f6.dc.JF,f6.Mw.atJ)}else if(bB.data.hn==f6.dc.aeA){f6o.gE.xo(bB.data.ai)}else if(bB.data.hn==f6.dc.Zu){f6o.gE.wf(bB.data.ai)}else if(bB.data.hn==f6.dc.afH){f6o.gE.Dr(bB.data.ai)}else if(bB.data.hn==f6.dc.Zk){f6o.gE.zx(bB.data.ai)}else if(bB.data.hn==f6.dc.atO){f6o.gE.afS(bB.data.ai)}else if(bB.data.hn==f6.dc.anp){f6o.gE.Au(bB.data.ai)}else if(bB.data.hn==f6.dc.arg){f6o.gE.Cc(bB.data.ai)}else if(bB.data.hn==f6.dc.amR){f6o.gE.CP(bB.data.ai)}else if(bB.data.hn==f6.dc.aqT){f6o.gE.Cr(bB.data.ai)}else if(bB.data.hn==f6.dc.anr){f6o.gE.vY(bB.data.ai)}else if(bB.data.hn==f6.dc.aay){f6o.gE.uf(bB.data.ai)}else if(bB.data.hn==f6.dc.apn){f6o.gE.QL(bB.data.ai)}else if(bB.data.hn==f6.dc.apA){f6o.gE.Dh(bB.data.ai)}else if(bB.data.hn==f6.dc.MW){var eU=bB.data.ai;var bM=f6.Oo(eU.C,eU.F,eU.dw,eU.fk,eU.fI,eU.R);if(typeof bM==f6.K.dP||bM){if(eU.C==f6.aJ.jz||eU.C==f6.aJ.jF){var Yi=eU.dw!=null?eU.dw:eU.fk;if(typeof Ax!=f6.K.L&&Ax!=null){Ax.wG(eU.C,eU.F,Yi)}}f6.Qx(eU.C,eU.eI);f6.ma(f6.dc.OA,{C:eU.C,F:eU.F,dw:eU.dw,fk:eU.fk,fI:eU.fI,R:eU.R,eI:eU.eI})}else{f6.ma(f6.dc.zm,{C:eU.C,F:eU.F})}}else if(bB.data.hn==f6.dc.QM){var eU=bB.data.ai;if(f6.Gq(eU.C,eU.F)){if(eU.C==f6.aJ.jz||eU.C==f6.aJ.jF){if(typeof Ax!=f6.K.L&&Ax!=null){Ax.wk(eU.C,eU.F)}}f6.ma(f6.dc.OG,{C:eU.C,F:eU.F})}else{f6.ma(f6.dc.Ah,{C:eU.C,F:eU.F})}}else if(bB.data.hn==f6.dc.Sd){var eI=bB.data.ai;f6.Qx(eI.C,eI.eI)}},false);f6o.gE={jX:null,azz:function(jX){this.jX=jX},aHi:[],bO:function(C,F){return C+":::"+F},xo:function(kx){var C=kx.C,F=kx.F;if(f6.fH==f6.cF.eJ){this.jX[f6.mt(C)].xo(C,F)}else{var bE=this.bO(C,F);this.aHi[bE]={C:C,F:F}}},wf:function(kx){var C=kx.C,F=kx.F;this.jX[f6.mt(C)].wf(C,F)},uS:function(bo){f6.ma(f6.dc.akp,bo)},uf:function(uU){var C=uU.C,F=uU.F;this.jX[f6.mt(C)].uf(C,F).then(function(be){f6.ma(f6.dc.Ru,{C:C,F:F,bz:be.bz,be:be.be})}).catch(function(){})},afS:function(um){this.jX[f6.mt(um.C)].afS(um).then(function(){}).catch(function(){})},QL:function(uU){var C=uU.C,F=uU.F;this.jX[f6.mt(C)].QL(C,F).then(function(bK){f6.ma(f6.dc.amK,{C:C,F:F,bK:bK})}).catch(function(){})},Au:function(dj){this.jX[f6.mt(dj.C)].Au(dj).then(function(Tp){}).catch(function(){})},Cc:function(dj){this.jX[f6.mt(dj.C)].Cc(dj).then(function(Tp){}).catch(function(){})},CP:function(dj){this.jX[f6.mt(dj.C)].CP(dj).then(function(Tp){}).catch(function(){})},Cr:function(dj){this.jX[f6.mt(dj.C)].Cr(dj).then(function(Tp){}).catch(function(){})},vY:function(dj){this.jX[f6.mt(dj.C)].vY(dj).then(function(Tp){}).catch(function(){})},Dr:function(kx){var C=kx.C,F=kx.F;this.jX[f6.mt(C)].Dr(C,F)},zx:function(kx){var C=kx.C,F=kx.F;this.jX[f6.mt(C)].zx(C,F)},UE:function(bo){f6.ma(f6.dc.alu,bo)},Dh:function(uU){var C=uU.C,F=uU.F,vn=uU.vn;this.jX[f6.mt(C)].Dh(C,F,vn).then(function(aE){f6.ma(f6.dc.akh,{C:vn,F:F,aE:aE})}).catch(function(){})}};f6o.jX=[];f6o.jX[f6.oB.ba]={
 kk:null,
 Us:function(kk){this.kk=kk},
 gE:null,
 XN:function(gE){this.gE=gE},
 aPm:[],
 bO:function(C,F,gr){return C+":::"+F+":::"+gr},
 eb:{tc:"HEARTBEAT",we:"MARKET_ORDER",sd:"LIMIT_ORDER",GF:"STOP_ORDER",Ft:"TAKE_PROFIT_ORDER",Gb:"STOP_LOSS_ORDER",SF:"ORDER_TRIGGERED",Dk:"ORDER_FILL",nj:"ORDER_CANCEL",adH:"DAILY_FINANCING",nH:"MARGIN_NOT_ENOUGH_REJECTED",qv:"MARKET_REJECTED",ta:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",pV:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",Cf:"TRANSFER_FUNDS",Ro:"SYNC_BALANCE",pE:"ACCOUNT_CREATED",qh:"ACCOUNT_REMOVED",OS:"ACCOUNT_BOUND",aSl:"100014",aRk:"100015",Ud:"100016",OX:"100017",sK:"ORDERBOOK",aAz:"DAILY_FINANCING_DONE",tX:"x"},
 nN:{aIt:"CLIENT_ORDER",we:"MARKET_ORDER",SC:"MARKET_ORDER_TRADE_CLOSE",sd:"LIMIT_ORDER",GF:"STOP_ORDER",Ft:"TAKE_PROFIT_ORDER",Gb:"STOP_LOSS_ORDER",SF:"ORDER_TRIGGERED",aHx:"CLOSEOUT",axX:"SHOP_ORDER",acZ:"DASHBOARD_ORDER",aSy:"CRYPTO_ORDER",acU:"CLIENT_REQUEST",cn:"EXPIRATION"},
 gm:{jL:"PENDING",wa:"FILLED",yB:"TRIGGERED",ti:"CANCELLED",vH:"REPLACED",nH:"MARGIN_NOT_ENOUGH_REJECTED",qv:"MARKET_REJECTED",ta:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",pV:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",rv:"ALL"},
 om:{eE:"OPEN",qW:"CLOSED",wd:"CLOSE_WHEN_TRADEABLE",vt:"TRANSFERRED",rv:"ALL"},
 TX:{rv:"ALL"},
 aDa:{dA:"B",eK:"S"},
 ja:{Iq:"MARKET",uJ:"LIMIT",ze:"STOP",cJ:"TAKE_PROFIT",cC:"STOP_LOSS"},
 auH:{aoa: -1},
 aJE:500,
 axF:500,
 ahx:function(V){if(typeof V.state==f6.K.O){if(V.state==this.gm.jL){return f6.dU.jL}else if(V.state==this.gm.wa&&typeof V.tradeOpenedID!=f6.K.L){return f6.dU.Qy}else if(V.state==this.gm.wa&&typeof V.tradeClosedIDs!=f6.K.L){return f6.dU.Qb}else if(V.state==this.gm.yB){return f6.dU.yB}else if(V.state==this.gm.ti){return f6.dU.ti}else if(V.state==this.gm.vH){return f6.dU.vH}else if(V.state==this.gm.nH){return f6.dU.nH}else if(V.state==this.gm.qv){return f6.dU.qv}else if(V.state==this.gm.ta){return f6.dU.ta}else if(V.state==this.gm.pV){return f6.dU.pV}else{return V.state+""}}else{return null}},
 PQ:function(V){if(typeof V.state==f6.K.O){if(V.state==this.om.eE){return f6.kA.eE}else if(V.state==this.om.qW){return f6.kA.qW}else if(V.state==this.om.wd){return f6.kA.wd}else if(V.state==this.om.vt){return f6.kA.vt}else{return V.state+""}}else{return null}},
 aPn:function(iQ){if(iQ==f6.dU.jL){return this.gm.jL}else if(iQ==f6.dU.wa){return this.gm.wa}else if(iQ==f6.dU.yB){return this.gm.yB}else if(iQ==f6.dU.ti){return this.gm.ti}else if(iQ==f6.dU.vH){return this.gm.vH}else if(iQ==f6.dU.nH){return this.gm.nH}else if(iQ==f6.dU.qv){return this.gm.qv}else if(iQ==f6.dU.ta){return this.gm.ta}else if(iQ==f6.dU.pV){return this.gm.pV}else{return this.gm.rv}},
 aOD:function(iQ){if(iQ==f6.kA.eE){return this.om.eE}else if(iQ==f6.kA.qW){return this.om.qW}else if(iQ==f6.kA.wd){return this.om.wd}else if(iQ==f6.kA.vt){return this.om.vt}else{return this.om.rv}},

 agI:function(C,V){
  var dG=this.ahx(V);var cl=0.0;var dQ=0.0;if(typeof V.takeProfitOnFill!=f6.K.L&&V.takeProfitOnFill!=null){cl=f6.bp(V.takeProfitOnFill.price)?parseFloat(V.takeProfitOnFill.price):0.0}if(typeof V.stopLossOnFill!=f6.K.L&&V.stopLossOnFill!=null){dQ=f6.bp(V.stopLossOnFill.price)?parseFloat(V.stopLossOnFill.price):0.0}var cz=f6.mY(C);if(dG==f6.dU.jL){return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:null,tK:null,sz:null,bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?(parseFloat(V.units)/cz):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:null,bn:f6.bp(V.price)?parseFloat(V.price):null,sg:null,cl:cl,dQ:dQ,bY:typeof V.comment==f6.K.O?V.comment:null,dO:f6.bi(V.magicNumber)?parseInt(V.magicNumber, 10):null,cn:f6.bi(V.expiration)?parseInt(V.expiration, 10):null}}else if(dG==f6.dU.Qy){return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:typeof V.fillingTransactionID==f6.K.O?V.fillingTransactionID:null,tK:f6.bp(V.filledTime)?parseFloat(V.filledTime):null,sz:null,bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?(parseFloat(V.units)/cz):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:typeof V.acp==f6.K.O?V.acp:null,sg:f6.bp(V.donePrice)?parseFloat(V.donePrice):null,bY:typeof V.comment==f6.K.O?V.comment:null,dO:f6.bi(V.magicNumber)?parseInt(V.magicNumber, 10):null,cn:f6.bi(V.expiration)?parseInt(V.expiration, 10):null}}else if(dG==f6.dU.Qb){return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:typeof V.fillingTransactionID==f6.K.O?V.fillingTransactionID:null,tK:f6.bp(V.filledTime)?parseFloat(V.filledTime):null,sz:f6.cg(V.tradeClosedIDs)?V.tradeClosedIDs:[],bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?(parseFloat(V.units)/cz):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:null,sg:f6.bp(V.donePrice)?parseFloat(V.donePrice):null}}else if(dG==f6.dU.ti||dG==f6.dU.nH){var hO=null;if(typeof V.reason==f6.K.O){if(V.reason==this.nN.acU){hO=f6.ca.nj}else if(V.reason==this.nN.cn){hO=f6.ca.cn}}if(dG==f6.dU.nH){hO=f6.ca.rn}return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:typeof V.cancellingTransactionID==f6.K.O?V.cancellingTransactionID:null,tK:f6.bp(V.cancelledTime)?parseFloat(V.cancelledTime):null,sz:f6.cg(V.tradeClosedIDs)?V.tradeClosedIDs:[],bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?(parseFloat(V.units)/cz):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:null,bn:f6.bp(V.price)?parseFloat(V.price):null,sg:f6.bp(V.donePrice)?parseFloat(V.donePrice):null,cl:cl,dQ:dQ,hO:hO,bY:typeof V.comment==f6.K.O?V.comment:null,dO:f6.bi(V.magicNumber)?parseInt(V.magicNumber, 10):null,cn:f6.bi(V.expiration)?parseInt(V.expiration, 10):null}}
 },

 agh:function(C,V){
  var cl=0.0;var dQ=0.0;if(typeof V.takeProfit!=f6.K.L&&V.takeProfit!=null){cl=f6.bp(V.takeProfit.price)?parseFloat(V.takeProfit.price):0.0}if(typeof V.stopLoss!=f6.K.L&&V.stopLoss!=null){dQ=f6.bp(V.stopLoss.price)?parseFloat(V.stopLoss.price):0.0}var cz=f6.mY(C);return{H:typeof V.id==f6.K.O?V.id:null,dG:this.PQ(V),bI:typeof V.instrument==f6.K.O?V.instrument:null,fE:f6.bp(V.openTime)?parseFloat(V.openTime):null,bn:f6.bp(V.price)?parseFloat(V.price):null,ij:f6.bp(V.currentUnits)?(parseFloat(V.currentUnits)/cz):null,hY:f6.bp(V.initialUnits)?(parseFloat(V.initialUnits)/cz):null,dR:f6.bp(V.financing)?parseFloat(V.financing):null,hd:f6.bp(V.realizedPL)?parseFloat(V.realizedPL):null,fZ:0.0,cL:f6.bp(V.commission)?parseFloat(V.commission):null,sz:f6.cg(V.tradeClosedIDs)?V.tradeClosedIDs:[],cl:cl,dQ:dQ,bY:typeof V.comment==f6.K.O?V.comment:null,dO:f6.bi(V.magicNumber)?parseInt(V.magicNumber, 10):null}
 },

 aOW:function(V){return{F:typeof V.accountID==f6.K.O?V.accountID:null,H:typeof V.id==f6.K.O?V.id:null,vV:typeof V.clOrderID==f6.K.O?V.clOrderID:null,dG:this.PQ(V),ab:f6.bp(V.openTime)?parseFloat(V.openTime):null,mu:f6.bp(V.initialUnits)?parseFloat(V.initialUnits):null,cL:f6.bp(V.commission)?parseFloat(V.commission):null,bY:typeof V.comment==f6.K.O?V.comment:null,Fg:typeof V.tradeClosedIds==f6.K.O?V.tradeClosedIds:null}},
 aeY:function(C,V){return{F:typeof V.accountId==f6.K.O?V.accountId:null,bI:typeof V.instrument==f6.K.O?V.instrument:null,zG:f6.bp(V.averagePrice)?parseFloat(V.averagePrice):null,cL:f6.bp(V.commission)?parseFloat(V.commission):null,bS:f6.bp(V.units)?(parseFloat(V.units)/f6.mY(C)):null,fA:f6.bp(V.pl)?parseFloat(V.pl):null,Gt:f6.bp(V.resettablePL)?parseFloat(V.resettablePL):null,fZ:f6.bp(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,dR:f6.bp(V.financing)?parseFloat(V.financing):null}},
 aPQ:function(V){return{Ey:typeof V.lN==f6.K.O?V.lN:null,Ej:f6.bi(V.sendingTime)?parseInt(V.sendingTime, 10):null,Jv:typeof V.cOID==f6.K.O?V.cOID:null,QE:typeof V.orderID==f6.K.O?V.orderID:null,TM:typeof V.eID==f6.K.O?V.eID:null,aV:typeof V.symbol==f6.K.O?V.symbol:null,Hc:typeof V.side==f6.K.O?V.side:null,HH:f6.bp(V.px)?parseFloat(V.px):null,JI:f6.bp(V.qty)?parseFloat(V.qty):null,iL:typeof V.a==f6.K.ec?V.a:null,C:typeof V.brokerName==f6.K.O?V.brokerName:null}},
 YP:function(V){return{C:typeof V.brokerName==f6.K.O?V.brokerName:null,hH:typeof V.brokerDesc==f6.K.O?V.brokerDesc:null,bz:typeof V.currency==f6.K.O?V.currency:null,aN:f6.bp(V.toFixed)?parseFloat(V.toFixed):null}},
 Pv:function(C,V){return{fz:f6.bp(V.nav)?parseFloat(V.nav):null,aIh:typeof V.alias==f6.K.O?V.alias:null,dV:f6.bp(V.balance)?parseFloat(V.balance):null,cL:f6.bp(V.commission)?parseFloat(V.commission):null,aCP:f6.bi(V.createdByUserID)?parseInt(V.createdByUserID, 10):null,aCj:f6.bp(V.createdTime)?parseFloat(V.createdTime):null,bz:typeof V.currency==f6.K.O?V.currency:f6.Jx(C),rq:typeof V.hedgingEnabled==f6.K.ec?V.hedgingEnabled:null,H:typeof V.id==f6.K.O?V.id:null,gr:typeof V.lastTransactionID==f6.K.O?V.lastTransactionID:null,jA:f6.bp(V.marginAvailable)?parseFloat(V.marginAvailable):null,aKZ:f6.bp(V.marginCallMarginUsed)?parseFloat(V.marginCallMarginUsed):null,aKS:f6.bp(V.marginCallPercent)?parseFloat(V.marginCallPercent):null,aLp:f6.bp(V.marginCloseoutMarginUsed)?parseFloat(V.marginCloseoutMarginUsed):null,aKC:f6.bp(V.marginCloseoutNAV)?parseFloat(V.marginCloseoutNAV):null,aMx:f6.bp(V.marginCloseoutPercent)?parseFloat(V.marginCloseoutPercent):null,aLf:f6.bp(V.marginCloseoutPositionValue)?parseFloat(V.marginCloseoutPositionValue):null,aKK:f6.bp(V.marginCloseoutUnrealizedPL)?parseFloat(V.marginCloseoutUnrealizedPL):null,aMw:f6.bp(V.marginRate)?parseFloat(V.marginRate):null,gN:f6.bp(V.marginUsed)?parseFloat(V.marginUsed):null,aLq:(f6.bi(V.openPositionCount)&&typeof V.openPositionCount!=f6.K.O)?V.openPositionCount:null,aIS:(f6.bi(V.openTradeCount)&&typeof V.openTradeCount!=f6.K.O)?V.openTradeCount:null,aNn:(f6.bi(V.pendingOrderCount)&&typeof V.pendingOrderCount!=f6.K.O)?V.pendingOrderCount:null,fA:f6.bp(V.pl)?parseFloat(V.pl):null,aNR:f6.bp(V.positionValue)?parseFloat(V.positionValue):null,Gt:f6.bp(V.resettablePL)?parseFloat(V.resettablePL):null,fZ:f6.bp(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,awY:f6.bp(V.withdrawalLimit)?parseFloat(V.withdrawalLimit):null,aN:f6.bp(V.toFixed)?parseFloat(V.toFixed):f6.wZ(C),mi:f6.bp(V.marginCallLevel)?parseFloat(V.marginCallLevel):null,qP:f6.bp(V.marginCloseoutLevel)?parseFloat(V.marginCloseoutLevel):null,F:typeof V.accountId==f6.K.O?V.accountId:null,iF:typeof V.email==f6.K.O?V.email:null,fK:typeof V.bWatchable==f6.K.ec?V.bWatchable:null,eY:typeof V.bOneClickAccepted==f6.K.ec?V.bOneClickAccepted:null,fL:typeof V.bMfaEnabled==f6.K.ec?V.bMfaEnabled:null,pf:typeof V.identifier==f6.K.O?V.identifier:null,iL:typeof V.bt==f6.K.ec?V.bt:null,fO:f6.bi(V.level)?parseInt(V.level, 10):null,mT:f6.bp(V.buyOpnCmmssn)?parseFloat(V.buyOpnCmmssn):null,lZ:f6.bp(V.buyClsdCmmssn)?parseFloat(V.buyClsdCmmssn):null,mP:f6.bp(V.sellOpnCmmssn)?parseFloat(V.sellOpnCmmssn):null,mx:f6.bp(V.sellClsdCmmssn)?parseFloat(V.sellClsdCmmssn):null,ci:f6.bp(V.bid)?parseFloat(V.bid):null,bX:f6.bp(V.ask)?parseFloat(V.ask):null,lD:f6.bp(V.latestUpdatedDate)?parseFloat(V.latestUpdatedDate):null}},
 pM:function(C,V){var cl=0.0;var dQ=0.0;if(typeof V.takeProfitOnFill!=f6.K.L&&V.takeProfitOnFill!=null){cl=f6.bp(V.takeProfitOnFill.price)?parseFloat(V.takeProfitOnFill.price):0.0}if(typeof V.stopLossOnFill!=f6.K.L&&V.stopLossOnFill!=null){dQ=f6.bp(V.stopLossOnFill.price)?parseFloat(V.stopLossOnFill.price):0.0}return{xc:f6.bp(V.accountBalance)?parseFloat(V.accountBalance):null,F:typeof V.accountID==f6.K.O?V.accountID:null,aFJ:typeof V.batchID==f6.K.O?V.batchID:null,cL:f6.bp(V.commission)?parseFloat(V.commission):null,dR:f6.bp(V.financing)?parseFloat(V.financing):null,aEE:null,H:typeof V.id==f6.K.O?V.id:null,hK:f6.bi(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,bI:typeof V.instrument==f6.K.O?V.instrument:null,eH:typeof V.orderID==f6.K.O?V.orderID:null,fA:f6.bp(V.pl)?parseFloat(V.pl):null,bn:f6.bp(V.price)?parseFloat(V.price):null,hO:typeof V.reason==f6.K.O?V.reason:null,GD:typeof V.requestID==f6.K.O?V.requestID:null,ab:f6.bp(V.time)?parseFloat(V.time):null,cj:typeof V.type==f6.K.O?V.type:null,oK:f6.bp(V.units)?parseFloat(V.units):null,bS:f6.bp(V.units)?(parseFloat(V.units)/f6.mY(C)):null,Ix:f6.bi(V.userID)?parseInt(V.userID, 10):null,cl:cl,dQ:dQ,vV:typeof V.clOrderID==f6.K.O?V.clOrderID:null,bY:typeof V.comment==f6.K.O?V.comment:null,dO:f6.bi(V.magicNumber)?parseInt(V.magicNumber, 10):null,fq:f6.bi(V.slippage)?parseInt(V.slippage, 10):null,cn:f6.bi(V.expiration)?parseInt(V.expiration, 10):null,C:typeof V.brokerName==f6.K.O?V.brokerName:null}},

 wX:function(V){
  var mC={gp:typeof V.id==f6.K.O?V.id:null,hK:f6.bi(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,C:typeof V.brokerName==f6.K.O?V.brokerName:null,F:typeof V.accountID==f6.K.O?V.accountID:null,ab:f6.bp(V.time)?parseFloat(V.time):null};if(mC.gp==null||mC.ab==null){throw new Error(f6.J.lM)}var gp=f6.bi(mC.gp)?parseInt(mC.gp, 10):null;gp=(gp!=null&&gp==this.auH.aoa)?null:gp;return{gp:gp,hK:mC.hK,C:mC.C,F:mC.F,ab:mC.ab}
 },

 NN:function(sK,cz){var anG=[];if(f6.cg(sK)){for(var i in sK){var Fw=sK[i];var bn=null;var bS=null;var En=null;var QH=null;bn=f6.bp(Fw.price)?parseFloat(Fw.price):null;bS=f6.bp(Fw.units)?(parseFloat(Fw.units)/cz):null;En=typeof Fw.type==f6.K.O?Fw.type:null;if(En!=f6.atr.uJ&&En!=f6.atr.ze){En=null}QH=bS>0?f6.aw.dA:f6.aw.eK;bS=Math.abs(bS);if(bn!=null&&bS!=null&&En!=null&&QH!=null){anG.push({En:En,QH:QH,bn:bn,bS:bS})}}}return anG},

 aqD:function(C,V){
  var mC={
   gp:typeof V.id==f6.K.O?V.id:null,
   hK:f6.bi(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,
   C:typeof V.brokerName==f6.K.O?V.brokerName:null,
   ab:f6.bp(V.time)?parseFloat(V.time):null,
   av:typeof V.instrument==f6.K.O?V.instrument:null
  };var cz=f6.mY(C);var DW=this.NN(V.orderBookBuyLimit,cz);var Ea=this.NN(V.orderBookSellLimit,cz);var Eq=this.NN(V.orderBookBuyStop,cz);var Ep=this.NN(V.orderBookSellStop,cz);if(mC.gp==null||mC.C==null||mC.ab==null||mC.av==null){throw new Error(f6.J.lM)}var tQ=null;if(DW.length>0){DW.sort(function(a,b){return a.bn-b.bn});tQ=0;for(var i=DW.length-1;i>=0;i -= 1){DW[i].bS+=tQ;tQ=DW[i].bS}}if(Ea.length>0){Ea.sort(function(a,b){return a.bn-b.bn});tQ=0;for(var i=Ea.length-1;i>=0;i -= 1){Ea[i].bS+=tQ;tQ=Ea[i].bS}}if(Eq.length>0){Eq.sort(function(a,b){return a.bn-b.bn});tQ=0;for(var i=Eq.length-1;i>=0;i -= 1){Eq[i].bS+=tQ;tQ=Eq[i].bS}}if(Ep.length>0){Ep.sort(function(a,b){return a.bn-b.bn});tQ=0;for(var i=Ep.length-1;i>=0;i -= 1){Ep[i].bS+=tQ;tQ=Ep[i].bS}}var gp=f6.bi(mC.gp)?parseInt(mC.gp, 10):null;gp=(gp!=null&&gp==this.auH.aoa)?null:gp;return{gp:gp,hK:mC.hK,C:mC.C,ab:mC.ab,av:mC.av,DW:DW,Ea:Ea,Eq:Eq,Ep:Ep}
 },

 ahn:function(V){var mp={C:typeof V.brokerName==f6.K.O?V.brokerName:null,F:typeof V.accountID==f6.K.O?V.accountID:null,H:typeof V.id==f6.K.O?V.id:null,hK:f6.bi(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,eH:typeof V.orderID==f6.K.O?V.orderID:null,ab:f6.bp(V.time)?parseFloat(V.time):null};if(mp.H==null||mp.C==null||mp.F==null||mp.eH==null||mp.ab==null){throw new Error(f6.J.lM)}return{gp:f6.bi(mp.H)?parseInt(mp.H, 10):null,hK:mp.hK,H:mp.eH,ab:mp.ab,iq:mp.H==mp.eH,C:mp.C,F:mp.F}},
 aud:function(C,V){var al=this.pM(C,V);if(al.C==null||al.F==null||al.H==null||al.eH==null||al.bI==null||al.ab==null||al.bn==null||al.bS==null){throw new Error(f6.J.lM)}return{gp:f6.bi(al.H)?parseInt(al.H, 10):null,hK:al.hK,H:al.eH,bI:al.bI,ar:al.bS>0?(al.cj==this.eb.sd?f6.aw.hm:f6.aw.he):(al.cj==this.eb.sd?f6.aw.jh:f6.aw.ip),ab:al.ab,bn:al.bn,bS:Math.abs(al.bS),cl:al.cl,dQ:al.dQ,iq:al.H==al.eH,C:al.C,F:al.F,bY:al.bY,dO:al.dO,cn:al.cn}},
 aON:function(C,V){var oh=this.pM(C,V);if(oh.C==null||oh.F==null||oh.H==null||oh.eH==null||oh.ab==null||oh.bn==null||oh.hO==null){throw new Error(f6.J.lM)}return{gp:f6.bi(oh.H)?parseInt(oh.H, 10):null,hK:oh.hK,H:oh.eH,yJ:oh.ab,sg:oh.bn,hO:oh.hO==this.nN.acU?f6.ca.nj:(oh.hO==this.eb.cn?f6.ca.cn:null),iq:false,C:oh.C,F:oh.F}},
 aPA:function(C,V){var hG=this.pM(C,V);if(hG.C==null||hG.F==null||hG.H==null||hG.eH==null||hG.bI==null||hG.ab==null||hG.bn==null||hG.bS==null){throw new Error(f6.J.lM)}return{gp:f6.bi(hG.H)?parseInt(hG.H, 10):null,hK:hG.hK,H:hG.eH,bI:hG.bI,ar:hG.bS>0?(hG.cj==this.eb.we?f6.aw.dA:(hG.cj==this.eb.sd?f6.aw.hm:f6.aw.he)):(hG.cj==this.eb.we?f6.aw.eK:(hG.cj==this.eb.sd?f6.aw.jh:f6.aw.ip)),yJ:hG.ab,bn:hG.bn,sg:hG.bn,bS:Math.abs(hG.bS),cl:hG.cl,dQ:hG.dQ,hO:f6.ca.rn,iq:hG.H==hG.eH,C:hG.C,F:hG.F}},
 atY:function(C,V){var or=this.pM(C,V);or.aiQ=null;or.ft=null;if(f6.cg(V.tradesClosed)&&V.tradesClosed.length>0){if(typeof V.tradesClosed[0].tradeID==f6.K.O){or.ft=V.tradesClosed[0].tradeID}}if(or.C==null||or.F==null||or.H==null||or.ft==null||or.ab==null){throw new Error(f6.J.lM)}return{gp:f6.bi(or.H)?parseInt(or.H, 10):null,hK:or.hK,H:or.ft,ab:or.ab,cl:or.cl,dQ:or.dQ,iq:false,C:or.C,F:or.F}},
 Mz:function(C,V){var dh=this.pM(C,V);dh.ayZ=null;if(dh.C==null||dh.F==null||dh.H==null||dh.bI==null||dh.ab==null||dh.bn==null||dh.bS==null||dh.fA==null||dh.cL==null||dh.eH==null){throw new Error(f6.J.lM)}return{gp:f6.bi(dh.H)?parseInt(dh.H, 10):null,hK:dh.hK,H:dh.H,bI:dh.bI,ar:dh.bS>0?f6.aw.dA:f6.aw.eK,fE:dh.ab,dS:dh.bn,ij:Math.abs(dh.bS),cl:dh.cl,dQ:dh.dQ,dR:0.0,cL:dh.cL,fZ:0.0,eH:dh.eH,iq:true,C:dh.C,F:dh.F,bY:dh.bY,dO:dh.dO}},
 St:function(C,V){var dh=this.pM(C,V);dh.aiQ=null;dh.ft=null;if(f6.cg(V.tradesClosed)&&V.tradesClosed.length>0){if(typeof V.tradesClosed[0].tradeID==f6.K.O){dh.ft=V.tradesClosed[0].tradeID}}if(dh.C==null||dh.F==null||dh.H==null||dh.bI==null||dh.ab==null||dh.bn==null||dh.bS==null||dh.fA==null||dh.ft==null||dh.cL==null||dh.dR==null){throw new Error(f6.J.lM)}return{gp:f6.bi(dh.H)?parseInt(dh.H, 10):null,hK:dh.hK,H:dh.ft,bI:dh.bI,ar:dh.bS<0?f6.aw.dA:f6.aw.eK,fE:null,dS:null,jO:dh.ab,lz:dh.bn,hY:Math.abs(dh.bS),dR:dh.dR,hd:dh.fA,cL:dh.cL,aiI:dh.H,iq:true,C:dh.C,F:dh.F,bY:dh.bY,dO:dh.dO}},
 Oy:function(V){var po={C:typeof V.brokerName==f6.K.O?V.brokerName:null,F:typeof V.accountID==f6.K.O?V.accountID:null,H:typeof V.id==f6.K.O?V.id:null,hK:f6.bi(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,ab:f6.bp(V.time)?parseFloat(V.time):null};if(po.C==null||po.F==null||po.H==null||po.ab==null){throw new Error(f6.J.lM)}return{gp:f6.bi(po.H)?parseInt(po.H, 10):null,hK:po.hK,H:po.H,ab:po.ab,iq:true,C:po.C,F:po.F}},
 atw:function(C,V){var oS=this.pM(C,V);if(oS.C==null||oS.F==null||oS.H==null||oS.ab==null||oS.oK==null||oS.cL==null){throw new Error(f6.J.lM)}return{gp:f6.bi(oS.H)?parseInt(oS.H, 10):null,hK:oS.hK,C:oS.C,F:oS.F,H:oS.H,vV:oS.vV,ab:oS.ab,mu:oS.oK,cL:oS.cL,iq:true,bY:oS.bY,Fg:oS.GD}},
 XW:function(C,F,V){var bo=null;var da=null;try{if(typeof V.type!=f6.K.L&&V.type){if(V.type==this.eb.tc){bo=this.wX(V);bo.F=F;da=f6.ca.tc}else if(V.type==this.eb.we){bo=this.ahn(V);da=f6.ca.vN}else if(V.type==this.eb.SF){bo=this.wX(V);da=f6.ca.vN}else if(V.type==this.eb.sd){bo=this.aud(C,V);da=f6.ca.al}else if(V.type==this.eb.GF){bo=this.aud(C,V);da=f6.ca.al}else if(V.type==this.eb.Ft){bo=this.atY(C,V);da=f6.ca.aP}else if(V.type==this.eb.Gb){bo=this.atY(C,V);da=f6.ca.aP}else if(V.type==this.eb.nj){bo=this.aON(C,V);da=f6.ca.nj}else if(V.type==this.eb.nH){bo=this.aPA(C,V);da=f6.ca.rn}else if(V.type==this.eb.qv){bo=this.wX(V);da=f6.ca.vN;throw new Error(f6.J.arM+"("+f6.ei(C)+", "+F+")")}else if(V.type==this.eb.Dk&&typeof V.reason!=f6.K.L&&(V.reason==this.nN.we||V.reason==this.nN.sd||V.reason==this.nN.GF)){bo=this.Mz(C,V);da=f6.ca.aP}else if(V.type==this.eb.Dk&&typeof V.reason!=f6.K.L&&(V.reason==this.nN.SC||V.reason==this.nN.Ft||V.reason==this.nN.Gb)){bo=this.St(C,V);da=f6.ca.cU}else if(V.type==this.eb.adH){bo=this.Oy(V);da=f6.ca.dR}else if(V.type==this.eb.pV){bo=this.wX(V);da=f6.ca.vN;throw new Error(f6.J.aum+"("+f6.ei(C)+", "+F+")")}else if(V.type==this.eb.ta){bo=this.wX(V);da=f6.ca.vN;throw new Error(f6.J.ann+"("+f6.ei(C)+", "+F+")")}else if(V.type==this.eb.Cf){bo=this.atw(C,V);da=f6.ca.Cf}else if(V.type==this.eb.Ro){bo=this.wX(V);da=f6.ca.vN}else if(V.type==this.eb.qh){bo=this.wX(V);da=f6.ca.vN;throw new Error(f6.J.aGj+"("+f6.ei(C)+", "+F+")")}else if(V.type==this.eb.sK){bo=this.aqD(C,V);da=f6.ca.sK}else if(V.type==this.eb.tX){bo={};da=f6.ca.tX}else{bo=this.wX(V);da=f6.ca.vN}}}catch(e){f6.au(JSON.stringify(V)+" "+e.message);f6.hF(e.message)}if(bo!=null){this.gE.uS({C:C,F:F,da:da,bo:bo})}},
 xo:function(C,F){var ao=this;this.kk.wv.uo(C,F,{},function(V){ao.XW(C,F,V)})},
 afS:function(um){var C=um.C,F=um.F,Gs=um.Gs;var ao=this;return new Promise(function(cp,aT){ao.kk.wv.apM(C,F,{id:Gs+""}).then(function(aK){if(f6.cg(aK.transactions)){for(var i in aK.transactions){ao.XW(C,F,aK.transactions[i])}cp()}else{f6.au(f6.J.TJ);f6.hF(f6.J.TJ);aT()}}).catch(function(){aT()})})},
 wf:function(C,F){this.kk.wv.tC(C,F)},

 Au:function(dj){
  var C=dj.C,F=dj.F,bI=dj.bI,oK=null,cj=null,bn=dj.bn,fq=dj.fq,bu=dj.bu,cJ=dj.cJ,cC=dj.cC,bY=dj.bY,dO=dj.dO,cn=dj.cn;var cz=f6.mY(C);if(dj.ar==f6.aw.dA){cj=this.ja.Iq;oK=bu*cz}else if(dj.ar==f6.aw.eK){cj=this.ja.Iq;oK= -(bu*cz)}else if(dj.ar==f6.aw.hm){cj=this.ja.uJ;oK=bu*cz}else if(dj.ar==f6.aw.jh){cj=this.ja.uJ;oK= -(bu*cz)}else if(dj.ar==f6.aw.he){cj=this.ja.ze;oK=bu*cz}else if(dj.ar==f6.aw.ip){cj=this.ja.ze;oK= -(bu*cz)}var ao=this;return new Promise(function(cp,aT){
   var Jw=null;var IT=null;if(cJ>0.0){Jw={price:cJ}}if(cC>0.0){IT={price:cC}}var HA={instrument:bI,units:oK,clientExtensions:{id:"",tag:"",comment:bY,magicNumber:dO,slippage:fq,expiration:cn},price:bn,type:cj,takeProfitOnFill:Jw,stopLossOnFill:IT};ao.kk.yn.auD(C,F,HA).then(function(aK){if(typeof aK.id!=f6.K.L){cp(aK.id+"")}else{f6.au(f6.J.auA);f6.hF(f6.J.auA);aT()}}).catch(function(){aT()});
  });
 },

 Cc:function(dj){
  var C=dj.C,F=dj.F,eH=dj.eH,bI=dj.bI,oK=null,cj=null,bn=dj.bn,fq=dj.fq,bu=dj.bu,cJ=dj.cJ,cC=dj.cC,bY=dj.bY,dO=dj.dO,cn=dj.cn;var cz=f6.mY(C);if(dj.ar==f6.aw.dA){cj=this.ja.Iq;oK=bu*cz}else if(dj.ar==f6.aw.eK){cj=this.ja.Iq;oK= -(bu*cz)}else if(dj.ar==f6.aw.hm){cj=this.ja.uJ;oK=bu*cz}else if(dj.ar==f6.aw.jh){cj=this.ja.uJ;oK= -(bu*cz)}else if(dj.ar==f6.aw.he){cj=this.ja.ze;oK=bu*cz}else if(dj.ar==f6.aw.ip){cj=this.ja.ze;oK= -(bu*cz)}var ao=this;return new Promise(function(cp,aT){
   var Jw=null;var IT=null;if(cJ>0.0){Jw={price:cJ}}if(cC>0.0){IT={price:cC}}var HA={instrument:bI,units:oK,clientExtensions:{id:"",tag:"",comment:bY,magicNumber:dO,slippage:fq,expiration:cn},price:bn,type:cj,takeProfitOnFill:Jw,stopLossOnFill:IT};ao.kk.yn.zE(C,F,eH,HA).then(function(aK){if(typeof aK.id!=f6.K.L){cp(aK.id+"")}else{f6.au(f6.J.auK);f6.hF(f6.J.auK);aT()}}).catch(function(){aT()});
  });
 },

 CP:function(dj){var C=dj.C,F=dj.F,eH=dj.eH;var ao=this;return new Promise(function(cp,aT){ao.kk.yn.aIs(C,F,eH).then(function(aK){if(typeof aK.id!=f6.K.L){cp(aK.id+"")}else{f6.au(f6.J.auZ);f6.hF(f6.J.auZ);aT()}}).catch(function(){aT()})})},

 Cr:function(dj){var C=dj.C,F=dj.F,ft=dj.ft,cJ=dj.cJ,cC=dj.cC,Pg=this.TX.rv;var ao=this;return new Promise(function(cp,aT){
  var atf=null;var asl=null;if(cJ>0.0){atf={price:cJ}}if(cC>0.0){asl={price:cC}}var HA={takeProfit:atf,stopLoss:asl};ao.kk.uV.aMo(C,F,ft,HA).then(function(aK){if(typeof aK.id!=f6.K.L){cp(aK.id+"")}else{f6.au(f6.J.atW);f6.hF(f6.J.atW);aT()}}).catch(function(){aT()});
 })},

 vY:function(dj){var C=dj.C,F=dj.F,ft=dj.ft,Pg=this.TX.rv,bn=dj.bn,fq=dj.fq;var ao=this;return new Promise(function(cp,aT){ao.kk.uV.eR(C,F,ft,{units:Pg,price:bn,slippage:fq}).then(function(aK){if(typeof aK.id!=f6.K.L){cp(aK.id+"")}else{f6.au(f6.J.atR);f6.hF(f6.J.atR);aT()}}).catch(function(){aT()})})},
 DS:function(fF){var aa={F:fF.F,iF:fF.iF,dV:fF.dV,bz:fF.bz,aN:fF.aN,cL:fF.cL,rq:fF.rq,fA:fF.fA,mi:fF.mi,qP:fF.qP,fz:fF.fz,gN:fF.gN,Rh:parseInt(fF.gr, 10),fK:fF.fK,eY:fF.eY,fL:fF.fL};if(aa.fz!=null&&aa.gN!=null){aa.jA=Math.round(fF.aN*(aa.fz-aa.gN))/fF.aN}else{aa.jA=null}return aa},
 aEg:function(C,fF){var aa={C:C,F:fF.F,iF:fF.iF,dV:fF.dV,fA:fF.fA,fz:fF.fz,gN:fF.gN,bz:fF.bz,pf:fF.pf,iL:fF.iL,fO:fF.fO,mT:fF.mT,lZ:fF.lZ,mP:fF.mP,mx:fF.mx,ci:fF.ci,bX:fF.bX,aN:fF.aN,lD:fF.lD};if(aa.fz!=null&&aa.gN!=null){aa.jA=Math.round(fF.aN*(aa.fz-aa.gN))/fF.aN}else{aa.jA=null}return aa},
 Dx:function(TQ){var cb=[];for(var i in TQ){var al=TQ[i];if(al.dG==f6.dU.jL&&al.bS!=null&&al.bS!=0&&al.wB!=null&&al.bI!=null&&al.na!=null&&al.bn!=null&&al.cj!=null){cb.push({H:al.wB,bI:al.bI,ar:al.bS>0?(al.cj==this.ja.uJ?f6.aw.hm:f6.aw.he):(al.cj==this.ja.uJ?f6.aw.jh:f6.aw.ip),ab:al.na,bn:al.bn,bS:Math.abs(al.bS),cl:al.cl,dQ:al.dQ,bY:al.bY,dO:al.dO,cn:al.cn})}}cb.sort(function(a,b){return a.ab-b.ab});return cb},
 Uf:function(akU){var eh=[];for(var i in akU){var aZ=akU[i];if(aZ.dG==f6.dU.ti&&aZ.bS!=null&&aZ.bS!=0&&aZ.wB!=null&&aZ.bI!=null&&aZ.na!=null&&aZ.tK!=null&&aZ.bn!=null&&aZ.sg!=null&&aZ.cj!=null&&aZ.hO!=null){eh.push({H:aZ.wB,bI:aZ.bI,ar:aZ.bS>0?(aZ.cj==this.ja.uJ?f6.aw.hm:f6.aw.he):(aZ.cj==this.ja.uJ?f6.aw.jh:f6.aw.ip),na:aZ.na,yJ:aZ.tK,bn:aZ.bn,bS:Math.abs(aZ.bS),cl:aZ.cl,dQ:aZ.dQ,sg:aZ.sg,hO:aZ.hO,bY:aZ.bY,dO:aZ.dO,cn:aZ.cn})}}eh.sort(function(a,b){return a.na-b.na});return eh},
 Dv:function(nl){var aS=[];for(var i in nl){var aP=nl[i];if(aP.dG==f6.kA.eE&&aP.hY!=null&&aP.hY!=0&&aP.H!=null&&aP.bI!=null&&aP.fE!=null&&aP.bn!=null&&aP.ij!=null&&aP.dR!=null&&aP.cL!=null){aS.push({H:aP.H,bI:aP.bI,ar:aP.hY>0?f6.aw.dA:f6.aw.eK,fE:aP.fE,dS:aP.bn,ij:Math.abs(aP.ij),cl:aP.cl,dQ:aP.dQ,dR:aP.dR,cL:aP.cL,fZ:0.0,bY:aP.bY,dO:aP.dO})}}aS.sort(function(a,b){return a.fE-b.fE});return aS},
 LW:function(gW){var cB=[];for(var i in gW){var fp=gW[i];if(fp.dG==f6.kA.qW&&fp.hY!=null&&fp.hY!=0){var jO=null;var lz=null;var EG=null;var hd=null;for(var j in gW){var Cy=gW[j];if(Cy.dG==f6.kA.qW&&Cy.sz.length>0&&Cy.sz[0]+""===fp.H){jO=Cy.fE;lz=Cy.bn;EG=Cy.cL;hd=Cy.hd;break}}if(fp.H!=null&&fp.bI!=null&&fp.fE!=null&&fp.bn!=null&&jO!=null&&lz!=null&&EG!=null&&fp.dR!=null&&hd!=null&&fp.cL!=null){cB.push({H:fp.H,bI:fp.bI,ar:fp.hY>0?f6.aw.dA:f6.aw.eK,fE:fp.fE,dS:fp.bn,jO:jO,lz:lz,hY:Math.abs(fp.hY),dR:fp.dR,hd:hd,cL:fp.cL+EG,cl:fp.cl,dQ:fp.dQ,bY:fp.bY,dO:fp.dO})}}}cB.sort(function(a,b){return a.fE-b.fE});return cB},
 zg:function(wz){var cs=[];for(var i in wz){var sU=wz[i];if(sU.dG==f6.kA.vt&&sU.F!=null&&sU.H!=null&&sU.ab!=null&&sU.mu!=null&&sU.cL!=null){cs.push({F:sU.F,H:sU.H,vV:sU.vV,ab:sU.ab,mu:sU.mu,cL:sU.cL,bY:sU.bY,Fg:sU.Fg})}}cs.sort(function(a,b){return a.ab-b.ab});return cs},
 Sz:function(db){var Cj=[];for(var i in db){var fJ=db[i];if(fJ.F!=null&&fJ.bI!=null&&fJ.zG!=null&&fJ.cL!=null&&fJ.bS!=null&&fJ.bS!=0&&fJ.fZ!=null&&fJ.dR!=null){Cj.push({F:fJ.F,bI:fJ.bI,zG:fJ.zG,cL:fJ.cL,bS:Math.abs(fJ.bS),fA:fJ.fA,Gt:fJ.Gt,fZ:fJ.fZ,dR:fJ.dR,uH:fJ.bS>0?f6.aw.dA:f6.aw.eK})}}Cj.sort(function(a,b){return b.bS-a.bS});return Cj},
 SA:function(db){var Cj=[];for(var i in db){var fJ=db[i];if(fJ.bI!=null&&fJ.bS!=null&&fJ.bS!=0){Cj.push({bI:fJ.bI,bS:fJ.bS})}}Cj.sort(function(a,b){return b.bS-a.bS});return Cj},
 CX:function(JQ){var ez=[];for(var i in JQ){var lX=JQ[i];if(lX.Ey!=null&&lX.Ej!=null&&lX.Jv!=null&&lX.aV!=null&&lX.Hc!=null&&lX.HH!=0&&lX.JI!=null){ez.push({Ey:lX.Ey,Ej:lX.Ej,Jv:lX.Jv,QE:lX.QE,TM:lX.TM,aV:lX.aV,Hc:lX.Hc,HH:lX.HH,JI:lX.JI,iL:lX.iL,C:lX.C})}}ez.sort(function(a,b){return a.Ej-b.Ej});return ez},
 adN:function(gJ){var Js=[];for(var i in gJ){var jS=gJ[i];if(jS.C!=null&&jS.hH!=null&&jS.bz!=null&&jS.aN!=null){Js.push({C:jS.C,hH:jS.hH,bz:jS.bz,aN:jS.aN})}}return Js},
 Ny:function(C,V){if(f6.cg(V)){var Ik=[];for(var i in V){Ik.push(this.agI(C,V[i]))}return Ik}else{throw new Error(f6.J.atS)}},
 PJ:function(C,V){if(f6.cg(V)){var gW=[];for(var i in V){gW.push(this.agh(C,V[i]))}return gW}else{throw new Error(f6.J.atV)}},
 Hu:function(V){if(f6.cg(V)){var gW=[];for(var i in V){gW.push(this.aOW(V[i]))}return gW}else{throw new Error(f6.J.aEM)}},
 afz:function(C,V){if(f6.cg(V)){var mK=[];for(var i in V){mK.push(this.aeY(C,V[i]))}return mK}else{throw new Error(f6.J.aug)}},
 abT:function(V){if(f6.cg(V)){var ez=[];for(var i in V){ez.push(this.aPQ(V[i]))}return ez}else{throw new Error(f6.J.aEH)}},
 aEC:function(V){if(f6.cg(V)){var gJ=[];for(var i in V){gJ.push(this.YP(V[i]))}return gJ}else{throw new Error(f6.J.aDC)}},
 Sb:function(C,V){if(f6.cg(V)){var bU=[];for(var i in V){bU.push(this.aEg(C,this.Pv(C,V[i])))}return bU}else{throw new Error(f6.J.aDS)}},
 QL:function(C,F){var ao=this;var bK={aa:null,cb:null,eh:null,aS:null,cB:null,cs:null};return new Promise(function(CU,DB){ao.kk.bh.fW(C,F).then(function(aK){return new Promise(function(cp,aT){try{if(typeof aK.account!=f6.K.L){bK.aa=ao.DS(ao.Pv(C,aK.account));bK.cb=ao.Dx(ao.Ny(C,aK.account.pendingOrders));bK.eh=ao.Uf(ao.Ny(C,aK.account.cancelledOrders));bK.cB=ao.LW(ao.PJ(C,aK.account.closedTrades));bK.aS=ao.Dv(ao.PJ(C,aK.account.openTrades));bK.cs=ao.zg(ao.Hu(aK.account.transferFundRecs));cp()}else{f6.au(f6.J.SH);f6.hF(f6.J.SH);aT()}}catch(e){f6.au(e.message);f6.hF(e.message);aT()}})}).then(function(){CU(bK)}).catch(function(){DB()})})},
 zd:function(V){if(f6.cg(V)){var be=[];for(var i in V){var af=V[i];if(typeof af.displayName==f6.K.O&&typeof af.symbolName==f6.K.O&&typeof af.basicCurrency==f6.K.O&&typeof af.tradableSymbol==f6.K.O&&f6.bp(af.toFixed)&&typeof af.toFixed!=f6.K.O&&f6.bp(af.cyBuySwap)&&typeof af.cyBuySwap!=f6.K.O&&f6.bp(af.cySellSwap)&&typeof af.cySellSwap!=f6.K.O&&f6.bp(af.trdBuySwap)&&typeof af.trdBuySwap!=f6.K.O&&f6.bp(af.trdSellSwap)&&typeof af.trdSellSwap!=f6.K.O&&f6.bp(af.leverage)&&typeof af.leverage!=f6.K.O&&f6.bp(af.lotsLimit)&&typeof af.lotsLimit!=f6.K.O&&f6.bp(af.cyBuyOpnCmmssn)&&typeof af.cyBuyOpnCmmssn!=f6.K.O&&f6.bp(af.cyBuyClsdCmmssn)&&typeof af.cyBuyClsdCmmssn!=f6.K.O&&f6.bp(af.cySellOpnCmmssn)&&typeof af.cySellOpnCmmssn!=f6.K.O&&f6.bp(af.cySellClsdCmmssn)&&typeof af.cySellClsdCmmssn!=f6.K.O&&f6.bp(af.cyBuyOpnCmmssn2)&&typeof af.cyBuyOpnCmmssn2!=f6.K.O&&f6.bp(af.cyBuyClsdCmmssn2)&&typeof af.cyBuyClsdCmmssn2!=f6.K.O&&f6.bp(af.cySellOpnCmmssn2)&&typeof af.cySellOpnCmmssn2!=f6.K.O&&f6.bp(af.cySellClsdCmmssn2)&&typeof af.cySellClsdCmmssn2!=f6.K.O&&f6.bp(af.bid)&&typeof af.bid!=f6.K.O&&f6.bp(af.ask)&&typeof af.ask!=f6.K.O&&f6.bp(af.bid2)&&typeof af.bid2!=f6.K.O&&f6.bp(af.ask2)&&typeof af.ask2!=f6.K.O&&f6.bp(af.trdBuyOpnCmmssn)&&typeof af.trdBuyOpnCmmssn!=f6.K.O&&f6.bp(af.trdBuyClsdCmmssn)&&typeof af.trdBuyClsdCmmssn!=f6.K.O&&f6.bp(af.trdSellOpnCmmssn)&&typeof af.trdSellOpnCmmssn!=f6.K.O&&f6.bp(af.trdSellClsdCmmssn)&&typeof af.trdSellClsdCmmssn!=f6.K.O&&f6.bp(af.lotsMinLimit)&&typeof af.lotsMinLimit!=f6.K.O&&f6.bp(af.lotsStep)&&typeof af.lotsStep!=f6.K.O&&f6.bp(af.limitStopMin)&&typeof af.limitStopMin!=f6.K.O&&f6.bp(af.spread)&&typeof af.spread!=f6.K.O){if(typeof af.bSpecialDay==f6.K.ec){if(af.bSpecialDay){if(!f6.bi(af.specialDay)||typeof af.specialDay==f6.K.O||af.specialDay<f6.mQ.FD||af.specialDay>f6.mQ.Mr){throw new Error(f6.J.pZ)}}else{af.specialDay=null}}else{throw new Error(f6.J.pZ)}be.push({bI:af.symbolName,av:af.displayName,eo:af.basicCurrency,jp:af.tradableSymbol,aN:af.toFixed,Hm:af.cyBuySwap,Hy:af.cySellSwap,QF:af.trdBuySwap,QX:af.trdSellSwap,Et:af.bSpecialDay,AS:af.specialDay,mj:af.leverage,tw:af.lotsLimit,GK:af.cyBuyOpnCmmssn,Il:af.cyBuyClsdCmmssn,HN:af.cySellOpnCmmssn,HL:af.cySellClsdCmmssn,azx:af.cyBuyOpnCmmssn2,aAx:af.cyBuyClsdCmmssn2,aAA:af.cySellOpnCmmssn2,azZ:af.cySellClsdCmmssn2,ci:af.bid,bX:af.ask,aEQ:af.bid2,aFS:af.ask2,afG:af.trdBuyOpnCmmssn,afn:af.trdBuyClsdCmmssn,aeH:af.trdSellOpnCmmssn,aei:af.trdSellClsdCmmssn,ts:af.lotsMinLimit,qm:af.lotsStep,qK:af.limitStopMin,eD:af.spread})}else{throw new Error(f6.J.pZ)}}return be}else{throw new Error(f6.J.pZ)}},
 uf:function(C,F){var ao=this;return new Promise(function(cp,aT){ao.kk.bh.xf(C,F,{}).then(function(aK){try{var bz=typeof aK.currency==f6.K.O?aK.currency:f6.Jx(C);var be=ao.zd(aK.instruments);cp({bz:bz,be:be})}catch(e){f6.au(e.message);f6.hF(e.message);aT()}}).catch(function(){aT()})})},
 Dh:function(C,F,vn){var ao=this;var aE={bU:null,db:null,ha:null,cs:null,be:null,gJ:null};return new Promise(function(CU,DB){ao.kk.Go.fW(C,F,vn).then(function(aK){return new Promise(function(cp,aT){try{aE.bU=ao.Sb(vn,aK.accounts);aE.db=ao.Sz(ao.afz(vn,aK.positions));aE.ha=ao.SA(ao.afz(vn,aK.groupedPositions));aE.be=ao.zd(aK.instruments);aE.cs=ao.zg(ao.Hu(aK.transferFundRecs));aE.ez=ao.CX(ao.abT(aK.ers));aE.gJ=ao.adN(ao.aEC(aK.brokers));cp()}catch(e){f6.au(e.message);f6.hF(e.message);aT()}})}).then(function(){CU(aE)}).catch(function(){DB()})})},
 aPr:function(C,V){var rO=this.pM(C,V);if(rO.H==null||rO.C==null||rO.F==null||rO.GD==null||rO.xc==null||rO.Ix==null||rO.ab==null){throw new Error(f6.J.lM)}return{H:rO.H,C:rO.C,F:rO.F,iF:rO.GD,dV:rO.xc,fA:0.0,pf:null,iL:false,fO:rO.Ix,mT:0.0,lZ:0.0,mP:0.0,mx:0.0,ci:0.0,bX:0.0,lD:rO.ab*1000}},
 aPp:function(C,V){var FK=this.pM(C,V);if(FK.H==null||FK.C==null||FK.F==null){throw new Error(f6.J.lM)}return{H:FK.H,C:FK.C,F:FK.F}},
 aOE:function(C,V){var xI=this.pM(C,V);var pf=null;if(xI.GD!=null){var alE=xI.GD.split(":::");if(alE.length==2){pf=alE[1]}}if(xI.H==null||xI.C==null||xI.F==null||pf==null||xI.ab==null){throw new Error(f6.J.lM)}return{H:xI.H,C:xI.C,F:xI.F,pf:pf,lD:xI.ab*1000}},
 aOB:function(C,V){var vF=this.pM(C,V);var iL=null;if(vF.bY==f6.K.ge){iL=true}else if(vF.bY==f6.K.oJ){iL=false}if(vF.H==null||vF.C==null||vF.F==null||iL==null||vF.ab==null){throw new Error(f6.J.lM)}return{H:vF.H,C:vF.C,F:vF.F,iL:iL,lD:vF.ab*1000}},
 aPM:function(C,V){var xb=this.pM(C,V);var jB=xb.bY.split(":::");var mT=null;var lZ=null;var mP=null;var mx=null;var ci=null;var bX=null;for(var i=0;i<jB.length;i += 1){if(f6.bp(jB[i])){if(i==0){mT=parseFloat(jB[i])}else if(i==1){lZ=parseFloat(jB[i])}else if(i==2){mP=parseFloat(jB[i])}else if(i==3){mx=parseFloat(jB[i])}else if(i==4){ci=parseFloat(jB[i])}else if(i==5){bX=parseFloat(jB[i])}else{throw new Error(f6.J.lM)}}else{throw new Error(f6.J.lM)}}if(xb.H==null||xb.C==null||xb.F==null||xb.Ix==null||mT==null||lZ==null||mP==null||mx==null||ci==null||bX==null||xb.ab==null){throw new Error(f6.J.lM)}return{H:xb.H,C:xb.C,F:xb.F,fO:xb.Ix,mT:mT,lZ:lZ,mP:mP,mx:mx,ci:ci,bX:bX,lD:xb.ab*1000}},
 aSn:function(um){var C=um.C,F=um.F,Gs=um.Gs;var ao=this;return new Promise(function(cp,aT){ao.kk.wv.apM(C,F,{id:Gs+""}).then(function(aK){if(f6.cg(aK.transactions)){for(var i in aK.transactions){ao.XW(C,F,aK.transactions[i])}cp()}else{f6.au(f6.J.TJ);f6.hF(f6.J.TJ);aT()}}).catch(function(){aT()})})},
 Dr:function(C,F){var ao=this;this.kk.Go.uo(C,F,{},function(V){var bo=null;var da=null;try{if(typeof V.type!=f6.K.L&&V.type){if(V.type==ao.eb.tc){bo={};da=f6.ca.tc}else if(V.type==ao.eb.Dk&&typeof V.reason!=f6.K.L&&(V.reason==ao.nN.we||V.reason==ao.nN.sd||V.reason==ao.nN.GF)){bo=ao.Mz(C,V);if(typeof V.er==f6.K.dP){var ez=ao.CX(ao.abT([V.er]));bo.qg=ez.length==1?ez[0]:null}da=f6.ca.aP}else if(V.type==ao.eb.Dk&&typeof V.reason!=f6.K.L&&(V.reason==ao.nN.SC||V.reason==ao.nN.Ft||V.reason==ao.nN.Gb)){bo=ao.St(C,V);if(typeof V.er==f6.K.dP){var ez=ao.CX(ao.abT([V.er]));bo.qg=ez.length==1?ez[0]:null}da=f6.ca.cU}else if(V.type==ao.eb.pV){bo=ao.wX(V);da=f6.ca.vN;throw new Error(f6.J.aum+"("+C+", "+bo.F+")")}else if(V.type==ao.eb.ta){bo=ao.wX(V);da=f6.ca.vN;throw new Error(f6.J.ann+"("+C+", "+bo.F+")")}else if(V.type==ao.eb.Cf){bo=ao.atw(C,V);da=f6.ca.Cf}else if(V.type==ao.eb.Ud){bo=ao.aOB(C,V);da=f6.ca.Ud}else if(V.type==ao.eb.OX){bo=ao.aPM(C,V);da=f6.ca.OX}else if(V.type==ao.eb.pE){bo=ao.aPr(C,V);da=f6.ca.pE}else if(V.type==ao.eb.qh){bo=ao.aPp(C,V);da=f6.ca.qh}else if(V.type==ao.eb.OS){bo=ao.aOE(C,V);da=f6.ca.OS}else if(V.type==ao.eb.sK){bo=ao.aqD(C,V);da=f6.ca.sK}else if(V.type==ao.eb.aAz){bo=ao.Oy(V);da=f6.ca.aph}else if(V.type==ao.eb.tX){bo={};da=f6.ca.tX}}}catch(e){f6.au(JSON.stringify(V)+" "+e.message);f6.hF(e.message)}if(bo!=null){ao.gE.UE({C:C,F:F,da:da,bo:bo})}})},
 zx:function(C,F){this.kk.Go.tC(C,F)}
};f6o.jX[f6.oB.AR]={
 kk:null,
 Us:function(kk){this.kk=kk},
 gE:null,
 XN:function(gE){this.gE=gE},
 aPm:[],
 bO:function(C,F,gr){return C+":::"+F+":::"+gr},
 eb:{tc:"HEARTBEAT",we:"MARKET_ORDER",sd:"LIMIT_ORDER",GF:"STOP_ORDER",Ft:"TAKE_PROFIT_ORDER",Gb:"STOP_LOSS_ORDER",SF:"ORDER_TRIGGERED",Dk:"ORDER_FILL",nj:"ORDER_CANCEL",adH:"DAILY_FINANCING",nH:"MARGIN_NOT_ENOUGH_REJECTED",qv:"MARKET_REJECTED",ta:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",pV:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",Cf:"TRANSFER_FUNDS",Ro:"SYNC_BALANCE",pE:"ACCOUNT_CREATED",qh:"ACCOUNT_REMOVED"},
 nN:{aIt:"CLIENT_ORDER",we:"MARKET_ORDER",SC:"MARKET_ORDER_TRADE_CLOSE",sd:"LIMIT_ORDER",GF:"STOP_ORDER",Ft:"TAKE_PROFIT_ORDER",Gb:"STOP_LOSS_ORDER",SF:"ORDER_TRIGGERED",aHx:"CLOSEOUT",axX:"SHOP_ORDER",acZ:"DASHBOARD_ORDER",acU:"CLIENT_REQUEST"},
 gm:{jL:"PENDING",wa:"FILLED",yB:"TRIGGERED",ti:"CANCELLED",vH:"REPLACED",nH:"MARGIN_NOT_ENOUGH_REJECTED",qv:"MARKET_REJECTED",ta:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",pV:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",rv:"ALL"},
 om:{eE:"OPEN",qW:"CLOSED",wd:"CLOSE_WHEN_TRADEABLE",vt:"TRANSFERRED",rv:"ALL"},
 TX:{rv:"ALL"},
 aDa:{dA:"B",eK:"S"},
 ja:{Iq:"MARKET",uJ:"LIMIT",ze:"STOP",cJ:"TAKE_PROFIT",cC:"STOP_LOSS"},
 aJE:500,
 axF:500,
 ahx:function(V){if(typeof V.state==f6.K.O){if(V.state==this.gm.jL){return f6.dU.jL}else if(V.state==this.gm.wa&&typeof V.tradeOpenedID!=f6.K.L){return f6.dU.Qy}else if(V.state==this.gm.wa&&typeof V.tradeClosedIDs!=f6.K.L){return f6.dU.Qb}else if(V.state==this.gm.yB){return f6.dU.yB}else if(V.state==this.gm.ti){return f6.dU.ti}else if(V.state==this.gm.vH){return f6.dU.vH}else if(V.state==this.gm.nH){return f6.dU.nH}else if(V.state==this.gm.qv){return f6.dU.qv}else if(V.state==this.gm.ta){return f6.dU.ta}else if(V.state==this.gm.pV){return f6.dU.pV}else{return V.state+""}}else{return null}},
 PQ:function(V){if(typeof V.state==f6.K.O){if(V.state==this.om.eE){return f6.kA.eE}else if(V.state==this.om.qW){return f6.kA.qW}else if(V.state==this.om.wd){return f6.kA.wd}else if(V.state==this.om.vt){return f6.kA.vt}else{return V.state+""}}else{return null}},
 aPn:function(iQ){if(iQ==f6.dU.jL){return this.gm.jL}else if(iQ==f6.dU.wa){return this.gm.wa}else if(iQ==f6.dU.yB){return this.gm.yB}else if(iQ==f6.dU.ti){return this.gm.ti}else if(iQ==f6.dU.vH){return this.gm.vH}else if(iQ==f6.dU.nH){return this.gm.nH}else if(iQ==f6.dU.qv){return this.gm.qv}else if(iQ==f6.dU.ta){return this.gm.ta}else if(iQ==f6.dU.pV){return this.gm.pV}else{return this.gm.rv}},
 aOD:function(iQ){if(iQ==f6.kA.eE){return this.om.eE}else if(iQ==f6.kA.qW){return this.om.qW}else if(iQ==f6.kA.wd){return this.om.wd}else if(iQ==f6.kA.vt){return this.om.vt}else{return this.om.rv}},
 agI:function(C,V){var cz=f6.mY(C);var dG=this.ahx(V);if(dG==f6.dU.jL){return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:null,tK:null,sz:null,bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?Math.abs((parseFloat(V.units)/cz)):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:null}}else if(dG==f6.dU.Qy){return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:typeof V.fillingTransactionID==f6.K.O?V.fillingTransactionID:null,tK:f6.bp(V.filledTime)?parseFloat(V.filledTime):null,sz:null,bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?(parseFloat(V.units)/cz):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:typeof V.acp==f6.K.O?V.acp:null}}else if(dG==f6.dU.Qb){return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:typeof V.fillingTransactionID==f6.K.O?V.fillingTransactionID:null,tK:f6.bp(V.filledTime)?parseFloat(V.filledTime):null,sz:f6.cg(V.tradeClosedIDs)?V.tradeClosedIDs:[],bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?(parseFloat(V.units)/cz):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:null}}else if(dG==f6.dU.ti){return{wB:typeof V.id==f6.K.O?V.id:null,na:f6.bp(V.createTime)?parseFloat(V.createTime):null,Ei:typeof V.cancellingTransactionID==f6.K.O?V.cancellingTransactionID:null,tK:f6.bp(V.cancelledTime)?parseFloat(V.cancelledTime):null,sz:null,bI:typeof V.instrument==f6.K.O?V.instrument:null,bS:f6.bp(V.units)?(parseFloat(V.units)/cz):null,dG:dG,cj:typeof V.type==f6.K.O?V.type:null,CF:typeof V.positionFill==f6.K.O?V.positionFill:null,EN:typeof V.timeInForce==f6.K.O?V.timeInForce:null,EH:null}}},
 agh:function(C,V){var cz=f6.mY(C);return{H:typeof V.id==f6.K.O?V.id:null,dG:this.PQ(V),bI:typeof V.instrument==f6.K.O?V.instrument:null,fE:f6.bp(V.openTime)?parseFloat(V.openTime):null,bn:f6.bp(V.price)?parseFloat(V.price):null,ij:f6.bp(V.currentUnits)?(parseFloat(V.currentUnits)/cz):null,hY:f6.bp(V.initialUnits)?(parseFloat(V.initialUnits)/cz):null,dR:f6.bp(V.financing)?parseFloat(V.financing):null,hd:f6.bp(V.realizedPL)?parseFloat(V.realizedPL):null,fZ:0.0,cL:f6.bp(V.commission)?parseFloat(V.commission):null,sz:f6.cg(V.tradeClosedIDs)?V.tradeClosedIDs:[]}},

 aeY:function(C,V){
  var cz=f6.mY(C);var Jf,VV,Vh,Uk,Ji,JT;if(typeof V.long!=f6.K.L){Jf=f6.bp(V.long.averagePrice)?parseFloat(V.long.averagePrice):null;VV=f6.bp(V.long.pl)?parseFloat(V.long.pl):null;Vh=f6.bp(V.long.resettablePL)?parseFloat(V.long.resettablePL):null;Uk=f6.cg(V.long.tradeIDs)?V.long.tradeIDs.join(","):null;Ji=f6.bp(V.long.units)?(parseFloat(V.long.units)/cz):null;JT=f6.bp(V.long.unrealizedPL)?parseFloat(V.long.unrealizedPL):null}var Kq,Wn,VG,XI,JD,JE;if(typeof V.short!=f6.K.L){Kq=f6.bp(V.short.averagePrice)?parseFloat(V.short.averagePrice):null;Wn=f6.bp(V.short.pl)?parseFloat(V.short.pl):null;VG=f6.bp(V.short.resettablePL)?parseFloat(V.short.resettablePL):null;XI=f6.cg(V.short.tradeIDs)?V.short.tradeIDs.join(","):null;JD=f6.bp(V.short.units)?(parseFloat(V.short.units)/cz):null;JE=f6.bp(V.short.unrealizedPL)?parseFloat(V.short.unrealizedPL):null}return{bI:typeof V.instrument==f6.K.O?V.instrument:null,cL:f6.bp(V.commission)?parseFloat(V.commission):null,fA:f6.bp(V.pl)?parseFloat(V.pl):null,Gt:f6.bp(V.resettablePL)?parseFloat(V.resettablePL):null,fZ:f6.bp(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,Jf:Jf,VV:VV,Vh:Vh,Uk:Uk,Ji:Ji,JT:JT,Kq:Kq,Wn:Wn,VG:VG,XI:XI,JD: -JD,JE:JE}
 },

 Pv:function(C,V){return{fz:f6.bp(V.NAV)?parseFloat(V.NAV):null,aIh:typeof V.alias==f6.K.O?V.alias:null,dV:f6.bp(V.balance)?parseFloat(V.balance):null,cL:f6.bp(V.commission)?parseFloat(V.commission):null,aCP:f6.bi(V.createdByUserID)?parseInt(V.createdByUserID, 10):null,aCj:f6.bp(V.createdTime)?parseFloat(V.createdTime):null,bz:typeof V.currency==f6.K.O?V.currency:f6.Jx(C),rq:typeof V.hedgingEnabled==f6.K.ec?V.hedgingEnabled:null,H:typeof V.id==f6.K.O?V.id:null,gr:typeof V.lastTransactionID==f6.K.O?V.lastTransactionID:null,jA:f6.bp(V.marginAvailable)?parseFloat(V.marginAvailable):null,aKZ:f6.bp(V.marginCallMarginUsed)?parseFloat(V.marginCallMarginUsed):null,aKS:f6.bp(V.marginCallPercent)?parseFloat(V.marginCallPercent):null,aLp:f6.bp(V.marginCloseoutMarginUsed)?parseFloat(V.marginCloseoutMarginUsed):null,aKC:f6.bp(V.marginCloseoutNAV)?parseFloat(V.marginCloseoutNAV):null,aMx:f6.bp(V.marginCloseoutPercent)?parseFloat(V.marginCloseoutPercent):null,aLf:f6.bp(V.marginCloseoutPositionValue)?parseFloat(V.marginCloseoutPositionValue):null,aKK:f6.bp(V.marginCloseoutUnrealizedPL)?parseFloat(V.marginCloseoutUnrealizedPL):null,aMw:f6.bp(V.marginRate)?parseFloat(V.marginRate):null,gN:f6.bp(V.marginUsed)?parseFloat(V.marginUsed):null,aLq:(f6.bi(V.openPositionCount)&&typeof V.openPositionCount!=f6.K.O)?V.openPositionCount:null,aIS:(f6.bi(V.openTradeCount)&&typeof V.openTradeCount!=f6.K.O)?V.openTradeCount:null,aNn:(f6.bi(V.pendingOrderCount)&&typeof V.pendingOrderCount!=f6.K.O)?V.pendingOrderCount:null,fA:f6.bp(V.pl)?parseFloat(V.pl):null,aNR:f6.bp(V.positionValue)?parseFloat(V.positionValue):null,Gt:f6.bp(V.resettablePL)?parseFloat(V.resettablePL):null,fZ:f6.bp(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,awY:f6.bp(V.withdrawalLimit)?parseFloat(V.withdrawalLimit):null,aN:f6.bp(V.toFixed)?parseFloat(V.toFixed):f6.wZ(C),mi:f6.bp(V.marginCallLevel)?parseFloat(V.marginCallLevel):null,qP:f6.bp(V.marginCloseoutLevel)?parseFloat(V.marginCloseoutLevel):null}},
 ahn:function(V){var mp={H:typeof V.id==f6.K.O?V.id:null,ab:f6.bp(V.time)?parseFloat(V.time):null};if(mp.H==null||mp.ab==null){throw new Error(f6.J.lM)}return{H:mp.H,ab:mp.ab}},
 pM:function(C,V){return{xc:f6.bp(V.accountBalance)?parseFloat(V.accountBalance):null,F:typeof V.accountID==f6.K.O?V.accountID:null,aFJ:typeof V.batchID==f6.K.O?V.batchID:null,cL:f6.bp(V.commission)?parseFloat(V.commission):null,dR:f6.bp(V.financing)?parseFloat(V.financing):null,aEE:null,H:typeof V.id==f6.K.O?V.id:null,bI:typeof V.instrument==f6.K.O?V.instrument:null,eH:typeof V.orderID==f6.K.O?V.orderID:null,fA:f6.bp(V.pl)?parseFloat(V.pl):null,bn:f6.bp(V.price)?parseFloat(V.price):null,hO:typeof V.reason==f6.K.O?V.reason:null,GD:typeof V.requestID==f6.K.O?V.requestID:null,ab:f6.bp(V.time)?parseFloat(V.time):null,cj:typeof V.type==f6.K.O?V.type:null,oK:f6.bp(V.units)?parseFloat(V.units):null,bS:f6.bp(V.units)?(parseFloat(V.units)/f6.mY(C)):null,Ix:f6.bi(V.userID)?parseInt(V.userID, 10):null}},
 Mz:function(C,V){var dh=this.pM(C,V);dh.ayZ=null;if(dh.H==null||dh.bI==null||dh.ab==null||dh.bn==null||dh.bS==null||dh.fA==null||dh.cL==null){throw new Error(f6.J.lM)}return{H:dh.H,bI:dh.bI,ar:dh.bS>0?f6.aw.dA:f6.aw.eK,fE:dh.ab,dS:dh.bn,ij:Math.abs(dh.bS),cl:null,dQ:null,dR:0.0,cL:dh.cL,fZ:0.0}},
 St:function(C,V){var dh=this.pM(C,V);dh.aiQ=null;dh.ft=null;if(f6.cg(V.tradesClosed)&&V.tradesClosed.length>0){if(typeof V.tradesClosed[0].tradeID==f6.K.O){dh.ft=V.tradesClosed[0].tradeID}}if(dh.H==null||dh.bI==null||dh.ab==null||dh.bn==null||dh.bS==null||dh.fA==null||dh.ft==null||dh.cL==null){throw new Error(f6.J.lM)}return{H:dh.ft,bI:dh.bI,ar:dh.bS<0?f6.aw.dA:f6.aw.eK,fE:null,dS:null,jO:dh.ab,lz:dh.bn,hY:Math.abs(dh.bS),dR:0.0,hd:dh.fA,cL:dh.cL,aiI:dh.H}},
 Oy:function(V){var po={H:typeof V.id==f6.K.O?V.id:null,ab:f6.bp(V.time)?parseFloat(V.time):null};if(po.H==null||po.ab==null){throw new Error(f6.J.lM)}return{H:po.H,ab:po.ab,dR:po.dR}},
 xo:function(C,F){var ao=this;this.kk.wv.uo(C,F,function(V){var bo=null;var da=null;try{if(typeof V.type!=f6.K.L&&V.type){if(V.type==ao.eb.tc){}else if(V.type==ao.eb.we){bo=ao.ahn(V);da=f6.ca.al;return}else if(V.type==ao.eb.nH){throw new Error(f6.J.GR)}else if(V.type==ao.eb.qv){throw new Error(f6.J.arM)}else if(V.type==ao.eb.Dk&&typeof V.reason!=f6.K.L&&V.reason==ao.nN.we){bo=ao.Mz(C,V);da=f6.ca.aP}else if(V.type==ao.eb.Dk&&typeof V.reason!=f6.K.L&&V.reason==ao.nN.SC){bo=ao.St(C,V);da=f6.ca.cU}else if(V.type==ao.eb.adH){bo=ao.Oy(V);da=f6.ca.dR}}}catch(e){f6.au(JSON.stringify(V)+" "+e.message);f6.hF(e.message)}if(bo!=null){ao.gE.uS({C:C,F:F,da:da,bo:bo})}})},
 wf:function(C,F){},

 Au:function(dj){var C=dj.C,F=dj.F,bI=dj.bI,ar=dj.ar,bn=dj.bn,fq=dj.fq,bu=dj.bu,cJ=dj.cJ,cC=dj.cC,bY=dj.bY;var ao=this;return new Promise(function(cp,aT){if(true){var cz=f6.mY(C);var aMg={
  instrument:bI,
  units:ar==f6.aw.dA?(bu*cz): -(bu*cz),

  clientExtensions:{
   id:"",
   tag:"",
   comment:bY
  },

  type:ao.ja.Iq
 };ao.kk.yn.auD(C,F,aMg).then(function(aK){cp("")}).catch(function(){aT()})}})},

 vY:function(dj){var C=dj.C,F=dj.F,ft=dj.ft,bn=0,Pg=this.TX.rv;var ao=this;return new Promise(function(cp,aT){ao.kk.uV.eR(C,F,ft,{units:Pg}).then(function(aK){cp("")}).catch(function(){aT()})})},
 DS:function(fF){var aa={dV:fF.dV,bz:fF.bz,aN:fF.aN,cL:fF.cL,rq:fF.rq,fA:fF.fA,mi:fF.mi,qP:fF.qP,fz:fF.fz,gN:fF.gN};if(aa.fz!=null&&aa.gN!=null){aa.jA=Math.round(fF.aN*(aa.fz-aa.gN))/fF.aN}else{aa.jA=null}return aa},
 Dv:function(nl){var aS=[];for(var i in nl){if(nl[i].dG==f6.kA.eE&&nl[i].hY!=null&&nl[i].hY!=0&&nl[i].H!=null&&nl[i].bI!=null&&nl[i].fE!=null&&nl[i].bn!=null&&nl[i].ij!=null){aS.push({H:nl[i].H,bI:nl[i].bI,ar:nl[i].hY>0?f6.aw.dA:f6.aw.eK,fE:nl[i].fE,dS:nl[i].bn,ij:Math.abs(nl[i].ij),cl:null,dQ:null,dR:nl[i].dR,cL:nl[i].cL,fZ:0.0})}}aS.sort(function(a,b){return a.fE-b.fE});return aS},
 LW:function(gW){var cB=[];for(var i in gW){if(gW[i].dG==f6.kA.qW&&gW[i].hY!=null&&gW[i].hY!=0){var jO=null;var lz=null;var EG=null;var hd=null;for(var j in gW){if(gW[j].dG==f6.kA.qW&&gW[j].sz.length>0&&gW[j].sz[0]+""===gW[i].H){jO=gW[j].fE;lz=gW[j].bn;EG=gW[j].cL;hd=gW[j].hd;break}}if(gW[i].H!=null&&gW[i].bI!=null&&gW[i].fE!=null&&gW[i].bn!=null&&jO!=null&&lz!=null&&EG!=null&&gW[i].dR!=null&&hd!=null&&gW[i].cL!=null){cB.push({H:gW[i].H,bI:gW[i].bI,ar:gW[i].hY>0?f6.aw.dA:f6.aw.eK,fE:gW[i].fE,dS:gW[i].bn,jO:jO,lz:lz,hY:Math.abs(gW[i].hY),dR:gW[i].dR,hd:hd,cL:gW[i].cL+EG})}}}cB.sort(function(a,b){return a.fE-b.fE});return cB},
 Dx:function(TQ){return TQ},
 Ny:function(C,V){if(f6.cg(V)){var Ik=[];for(var i in V){Ik.push(this.agI(C,V[i]))}return Ik}else{throw new Error(f6.J.atS)}},
 PJ:function(C,V){if(f6.cg(V)){var gW=[];for(var i in V){gW.push(this.agh(C,V[i]))}return gW}else{throw new Error(f6.J.atV)}},
 afz:function(C,V){if(f6.cg(V)){var mK=[];for(var i in V){mK.push(this.aeY(C,V[i]))}return mK}else{throw new Error(f6.J.aug)}},
 QL:function(C,F){var ao=this;var bK={aa:null,cb:null,aS:null,cB:null};return new Promise(function(CU,DB){ao.kk.bh.fW(C,F).then(function(aK){return new Promise(function(cp,aT){try{if(typeof aK.account!=f6.K.L){bK.aa=ao.DS(ao.Pv(C,aK.account));bK.cb=ao.Dx(ao.Ny(C,aK.account.orders));bK.cB=[];bK.aS=ao.Dv(ao.PJ(C,aK.account.trades));cp()}else{f6.au(f6.J.SH);f6.hF(f6.J.SH);aT()}}catch(e){f6.au(e.message);f6.hF(e.message);aT()}})}).then(function(){CU(bK)}).catch(function(){DB()})})},
 zd:function(C,V){if(f6.cg(V)){var be=[];var cz=f6.mY(C);for(var i in V){if(typeof V[i].displayName==f6.K.O&&typeof V[i].name==f6.K.O&&f6.bp(V[i].displayPrecision)&&typeof V[i].displayPrecision!=f6.K.O&&f6.bp(V[i].marginRate)&&typeof V[i].marginRate==f6.K.O&&f6.bp(V[i].maximumOrderUnits)&&typeof V[i].maximumOrderUnits==f6.K.O){var aG=V[i].name.split("_");if(aG.length!=2){throw new Error(f6.J.pZ)}be.push({bI:V[i].name,av:V[i].displayName,eo:aG[1],jp:aG[0],aN:Math.pow(10,V[i].displayPrecision),Hm:0.0,Hy:0.0,QF:0.0,QX:0.0,Et:true,AS:3,mj:1.0/parseFloat(V[i].marginRate),tw:parseFloat(V[i].maximumOrderUnits)/cz,GK:0.0,Il:0.0,HN:0.0,HL:0.0,afG:0.0,afn:0.0,aeH:0.0,aei:0.0,ts:parseFloat(V[i].minimumTradeSize)/cz,qm:parseFloat(V[i].minimumTradeSize)/cz,qK:0.0})}else{throw new Error(f6.J.pZ)}}return be}else{throw new Error(f6.J.pZ)}},
 uf:function(C,F){var ao=this;return new Promise(function(cp,aT){ao.kk.bh.xf(C,F,{}).then(function(aK){try{cp(ao.zd(C,aK.instruments))}catch(e){f6.au(e.message);f6.hF(e.message);aT()}}).catch(function(){aT()})})}
};f6o.ev={};f6o.ev.lB=function(sR,iG,mJ,tn,cP){return new Promise(function(cp,aT){try{var du=new XMLHttpRequest();if(mJ===f6.bf.hj||mJ===f6.bf.zc){du.open(mJ,sR+iG,true);du.setRequestHeader(f6.bf.agc,f6.bf.agS);du.setRequestHeader(f6.bf.Hf,f6.bf.zP+" "+cP);du.send(JSON.stringify(tn))}else if(mJ===f6.bf.fW){du.open(mJ,sR+iG+"?"+f6.JW(tn),true);du.setRequestHeader(f6.bf.Hf,f6.bf.zP+" "+cP);du.send(null)}else{throw new Error(f6.J.IP)}du.onreadystatechange=function(){if(du.readyState==4){if(du.status==200||du.status==0){try{if(du.responseText!=""){cp(JSON.parse(du.responseText))}else{cp(du.responseText)}}catch(e){f6.au(e.message);f6.hF(e.message);aT()}}else{f6.au(du.status+" "+du.responseText);f6.hF(du.status+" "+du.responseText);aT()}}};du.onerror=function(){f6.au(f6.J.LM);aT()}}catch(e){f6.au(e.message);f6.hF(e.message);aT()}})};f6o.ev.pQ=[];f6o.ev.uo=function(qz,iG,mJ,tn,bJ){try{if(mJ===f6.bf.fW){if(! !self.EventSource){this.tC(qz,iG);this.pQ[qz+iG]=new self.EventSource(qz+iG+"?"+f6.JW(tn),{withCredentials:true});this.pQ[qz+iG].addEventListener(f6.dF.mX,function(e){try{bJ(JSON.parse(e.data))}catch(e){f6.au(e.message);f6.hF(e.message)}},false);this.pQ[qz+iG].addEventListener(f6.dF.eE,function(e){},false);this.pQ[qz+iG].addEventListener(f6.dF.nJ,function(e){if(e.readyState==self.EventSource.CLOSED){}f6.au(f6.J.LM+" ("+qz+iG+")");bJ({type:f6.ca.tX})},false)}else{}}else{throw new Error(f6.J.IP)}}catch(e){f6.au(e.message);f6.hF(e.message)}};f6o.ev.tC=function(sR,iG){if(typeof this.pQ[sR+iG]!=f6.K.L){this.pQ[sR+iG].close();delete this.pQ[sR+iG]}};f6o.ev.bh={};f6o.ev.bh.xf=function(C,F,Iv){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/instruments",f6.bf.fW,Iv,f6.la(C,F))};f6o.ev.bh.fW=function(C,F){return f6o.ev.lB(f6.ea(C),"/accounts/"+F,f6.bf.fW,{},f6.la(C,F))};f6o.ev.wv={};f6o.ev.wv.XU=function(C,F,lf){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/transactions",f6.bf.fW,lf,f6.la(C,F))};f6o.ev.wv.apM=function(C,F,lf){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/transactions/sinceid",f6.bf.fW,lf,f6.la(C,F))};f6o.ev.wv.fW=function(C,F,avF){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/transactions/"+avF,f6.bf.fW,{},f6.la(C,F))};f6o.ev.wv.uo=function(C,F,lf,bJ){f6o.ev.uo(f6.Oj(C),"/accounts/"+F+"/transactions/stream",f6.bf.fW,{aH:f6.bf.zP+" "+f6.la(C,F)},bJ)};f6o.ev.wv.tC=function(C,F){f6o.ev.tC(f6.Oj(C),"/accounts/"+F+"/transactions/stream")};f6o.ev.uV={};f6o.ev.uV.XU=function(C,F,lf){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/trades",f6.bf.fW,lf,f6.la(C,F))};f6o.ev.uV.aOQ=function(C,F){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/openTrades",f6.bf.fW,{},f6.la(C,F))};f6o.ev.uV.fW=function(C,F,LU){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/trades/"+LU,f6.bf.fW,{},f6.la(C,F))};f6o.ev.uV.eR=function(C,F,LU,abd){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/trades/"+LU+"/close",f6.bf.zc,abd,f6.la(C,F))};f6o.ev.uV.aMo=function(C,F,LU,IL){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/trades/"+LU+"/orders",f6.bf.zc,IL,f6.la(C,F))};f6o.ev.yn={};f6o.ev.yn.XU=function(C,F,lf){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/orders",f6.bf.fW,lf,f6.la(C,F))};f6o.ev.yn.aTG=function(C,F){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/pendingOrders",f6.bf.fW,{},f6.la(C,F))};f6o.ev.yn.fW=function(C,F,HE){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/orders/"+HE,f6.bf.fW,{},f6.la(C,F))};f6o.ev.yn.auD=function(C,F,IL){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/orders",f6.bf.hj,IL,f6.la(C,F))};f6o.ev.yn.aIs=function(C,F,HE){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/orders/"+HE+"/cancel",f6.bf.zc,{},f6.la(C,F))};f6o.ev.yn.zE=function(C,F,HE,IL){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/orders/"+HE,f6.bf.zc,IL,f6.la(C,F))};f6o.ev.Sf={};f6o.ev.Sf.XU=function(C,F){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/positions",f6.bf.fW,{},f6.la(C,F))};f6o.ev.Sf.aOQ=function(C,F){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/openPositions",f6.bf.fW,{},f6.la(C,F))};f6o.ev.Sf.fW=function(C,F,VM){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/positions/"+VM,f6.bf.fW,{},f6.la(C,F))};f6o.ev.Sf.eR=function(C,F,VM,abd){return f6o.ev.lB(f6.ea(C),"/accounts/"+F+"/positions/"+VM+"/close",f6.bf.zc,abd,f6.la(C,F))};
