/*
 *
 *  Shi Nai Jun (Mark Sea) CONFIDENTIAL
 * __________________
 *
 *  Shi Nai Jun (Mark Sea)
 *  All Rights Reserved.
 *
 * NOTICE:  All information and all copyrights contained herein are,
 * and remain the property of Shi Nai Jun, if any.
 * The intellectual and technical concepts contained herein are
 * proprietary to Shi Nai Jun and may be covered by patents, patents
 * in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Shi Nai Jun.
 *
 */
self.importScripts("lang/en.js")
self.importScripts("brokers.js")
var f6o={};var f6=f6o;
f6.R={
 auY:dict.m1,
 axb:dict.m2,
 aDG:dict.m3,
 FA:dict.m4,
 rN:dict.m5,
 Zi:dict.m6,
 auy:dict.m7,
 aEd:dict.m8,
 aqF:dict.m9,
 aIs:dict.m10,
 aDM:dict.m11,
 aJQ:dict.m12,
 aGW:dict.m13,
 aDX:dict.m14,
 aoR:dict.m15,
 aBh:dict.m16,
 aKe:dict.m17,
 aIk:dict.m18,
 aEB:dict.m19,
 aDF:dict.m20,
 zE:dict.m21,
 apv:dict.m22,
 aCW:dict.m23,
 aTM:dict.m24,
 aSZ:dict.m25,
 Kc:dict.m26,
 JS:dict.m27,
 PD:dict.m28,
 aGT:dict.m29,
 amJ:dict.m30,
 atV:dict.m31,
 aDx:dict.m32,
 aEw:dict.m33,
 aHq:dict.m34,
 aEu:dict.m35,
 aMX:dict.m36,
 aJM:dict.m37,
 aCv:dict.m38,
 aDm:dict.m39,
 atr:dict.m40,
 el:dict.m41,
 ahS:dict.m42,
 aIo:dict.m43,
 aJS:dict.m44,
 aIR:dict.m45,
 aLk:dict.m46,
 LW:dict.m47,
 apP:dict.m48,
 atC:dict.m49,
 aup:dict.m50,
 atM:dict.m51,
 att:dict.m52,
 atK:dict.m53,
 NL:dict.m54,
 pN:dict.m55,
 ava:dict.m56,
 atD:dict.m57,
 aEx:dict.m58,
 atJ:dict.m59,
 aDs:dict.m60,
 NM:dict.m61,
 mY:dict.m62,
 uV:dict.m63,
 aJc:dict.m64,
 HU:dict.m65,
 aQy:dict.m66,
 avg:dict.m67,
 vj:dict.m68,
 agI:dict.m69,
 atq:dict.m70,
 Iv:dict.m71,
 aSA:dict.m72,
 Om:dict.m73,
 ajl:dict.m74,
 aRd:dict.m75,
 arw:dict.m76,
 tJ:dict.m77,
 Hl:dict.m78,
 ahN:dict.m79,
 agg:dict.m80,
 aga:dict.m81,
 agp:dict.m82,
 RJ:dict.m83,
 Rh:dict.m84,
 uv:dict.m85,
 oP:dict.m86,
 aRN:dict.m87,
 aQk:dict.m88,
 ajx:dict.m89,
 ahY:dict.m90,
 asW:dict.m91,
 aak:dict.m92,
 Ie:dict.m93,
 aqA:dict.m94,
 aqz:dict.m95,
 aFR:dict.m96,
 QZ:dict.m97,
 Vj:dict.m98,
 or:dict.m99,
 aGm:dict.m100,
 aGF:dict.m101,
 aJX:dict.m102,
 qp:dict.m103,
 ahn:dict.m104,
 aPN:dict.m105,
 aSj:dict.m106,
 aHP:dict.m107,
 Nc:dict.m108,
 aNU:dict.m109,
 Mi:dict.m110,
 asG:dict.m111,
 XJ:dict.m112,
 aQP:dict.m113,
 aEE:dict.m114,
 akc:dict.m115,
 UO:dict.m116,
 aPu:dict.m117,
 aoi:dict.m118,
 aiu:dict.m119,
 aFh:dict.m120,
 Ny:dict.m121,
 Oh:dict.m122,
 eb:dict.m123,
 hn:dict.m124,
 gZ:dict.m125,
 aua:dict.m126,
 TI:dict.m127,
 apx:dict.m128,
 GW:dict.m129,
 azG:dict.m130,
 axw:dict.m131,
 axg:dict.m132,
 axp:dict.m133,
 Yf:dict.m134,
 nN:dict.m135,
 FR:dict.m136,
 aku:dict.m137,
 akJ:dict.m138,
 auq:dict.m139,
 amB:dict.m140,
 arZ:dict.m141,
 aEm:dict.m142,
 abX:dict.m143,
 vb:dict.m144,
 vG:dict.m145,
 aQZ:dict.m146,
 aRV:dict.m147,
 aEX:dict.m148,
 aQO:dict.m149,
 aRG:dict.m150,
 aRK:dict.m151,
 PG:dict.m152,
 Wy:dict.m153,
 avm:dict.m154,
 adg:dict.m155,
 amk:dict.m156,
 aqN:dict.m157,
 cE:dict.m158,
 nx:dict.m159,
 Kf:dict.m160,
 anN:dict.m161,
 amz:dict.m162,
 apn:dict.m163,
 apg:dict.m164,
 aqI:dict.m165,
 arh:dict.m166,
 aql:dict.m167,
 aqU:dict.m168,
 gL:dict.m169,
 apG:dict.m170,
 nQ:dict.m171,
 aeX:dict.m172,
 qS:dict.m173,
 EK:dict.m174,
 qP:dict.m175,
 qQ:dict.m176,
 JN:dict.m177,
 afR:dict.m178,
 DS:dict.m179,
 Np:dict.m180,
 GA:dict.m181,
 FP:dict.m182,
 awG:dict.m183,
 vS:dict.m184,
 aRp:dict.m185,
 atI:dict.m186,
 aFB:dict.m187,
 aPc:dict.m188,
 alZ:dict.m189,
 aks:dict.m190,
 Qj:dict.m191,
 OP:dict.m192,
 VY:dict.m193,
 OA:dict.m194,
 WW:dict.m195,
 We:dict.m196,
 Wg:dict.m197,
 LQ:dict.m198,
 ud:dict.m199,
 aAC:dict.m200,
 ali:dict.m201,
 FT:dict.m202,
 xj:dict.m203,
 afX:dict.m204,
 akB:dict.m205,
 Rr:dict.m206,
 RI:dict.m207,
 aqk:dict.m208,
 aJq:dict.m209,
 aJi:dict.m210,
 aKb:dict.m211,
 aIG:dict.m212,
 axX:dict.m213,
 aNi:dict.m214,
 aCS:dict.m215,
 aNk:dict.m216,
 aPI:dict.m217,
 ayV:dict.m218,
 ayy:dict.m219,
 nP:dict.m220,
 zO:dict.m221,
 zR:dict.m222,
 avY:dict.m223,
 auE:dict.m224,
 aD:dict.m225,
 aKr:dict.m226,
 aRe:dict.m227,
 aAo:dict.m228,
 PQ:dict.m229,
 avA:dict.m230,
 aPd:dict.m231,
 auv:dict.m232,
 Kz:dict.m233,
 nz:dict.m234,
 Jl:dict.m235,
 ve:dict.m236,
 AO:dict.m237,
 zF:dict.m238,
 aqp:dict.m239,
 aqG:dict.m240,
 aeP:dict.m241,
 aSu:dict.m242,
 Vq:dict.m243,
 avU:dict.m244,
 aEg:dict.m245,
 anF:dict.m246,
 anC:dict.m247,
 amL:dict.m248,
 aGs:dict.m249,
 aoU:dict.m250,
 azr:dict.m251,
 aRu:dict.m252,
 aRB:dict.m253,
 aKR:dict.m254,
 aNs:dict.m255,
 aiF:dict.m256,
 Fx:dict.m257,
 aBG:dict.m258,
 aIM:dict.m259,
 ayn:dict.m260,
 axJ:dict.m261,
 aAY:dict.m262,
 aCV:dict.m263,
 aix:dict.m264,
 are:dict.m265,
 aoB:dict.m266,
 ML:dict.m267,
 arM:dict.m268,
 aqO:dict.m269,
 SI:dict.m270,
 aEi:dict.m271,
 auI:dict.m272,
 ays:dict.m273,
 ayu:dict.m274,
 akQ:dict.m275,
 alK:dict.m276,
 anW:dict.m277,
 apF:dict.m278,
 aFK:dict.m279,
 afM:dict.m280,
 aIX:dict.m281,
 Fu:dict.m282,
 aDJ:dict.m283,
 aKB:dict.m284,
 aJA:dict.m285,
 apC:dict.m286
};f6.az=function(bv){var lC=new Date(Date.now()).toString()+" "+f6.R.auY+bv;console.error(lC)};f6.cf=function(bv){var lC=new Date(Date.now()).toString()+" "+bv;console.log(lC)};f6.ho=function(bv){var lC=new Date(Date.now()).toString()+" "+bv;console.log(lC)};f6.iX={Dr:"cc_s_m",Eb:"cc_e_m",Ef:"cc_w_m",aRq:"cc_s_m_b",aQB:"cc_e_m_b",aSk:"cc_w_m_b",aSL:".header",EH:".p",aGI:".message .close",atm:".message",Fa:"transition",Fw:"hidden",aBn:"fade",UE:"<br>",UH:"padding-left",Jo:"5em",ayX:'<div class="ui overlay success message transition hidden" style="position:fixed!important;overflow-y:scroll" id="cc_s_m">'+'<i class="close icon" style="font-size:1.5rem" id="cc_s_m_b"></i>'+'<div class="header">'+'Success Message'+'</div>'+'<p class="p"></p>'+'</div>',aFg:'<div class="ui overlay error message transition hidden" style="position:fixed!important;overflow-y:scroll" id="cc_e_m">'+'<i class="close icon" style="font-size:1.5rem" id="cc_e_m_b"></i>'+'<div class="header">'+'Error Message'+'</div>'+'<p class="p"></p>'+'</div>',awS:'<div class="ui overlay warning message transition hidden" style="position:fixed!important;overflow-y:scroll" id="cc_w_m">'+'<i class="close icon" style="font-size:1.5rem" id="cc_w_m_b"></i>'+'<div class="header">'+'Warning Message'+'</div>'+'<p class="p"></p>'+'</div>',BI:true,Yo:true,VH:"",Xc:function(bv){if(this.Yo){$(document).attr(f6.O.iu,this.VH)}else{$(document).attr(f6.O.iu,bv)}},jo:function(BI,EL,EB,DC){if (typeof BI!=f6.L.fI) {
 return;
}if (typeof EL!=f6.L.C) {
 return;
}if (typeof EB!=f6.L.C) {
 return;
}if (typeof DC!=f6.L.C) {
 return;
}this.BI=BI;this.anU(EL,EB,DC,this.Jo);this.VH=$(document).attr(f6.O.iu);var F=this;window.addEventListener(f6.cS.aJk,function(){F.Yo=true});window.addEventListener(f6.cS.aPp,function(){F.Yo=false})},anU:function(EL,EB,DC,Jo){$("#"+EL).append(this.ayX);$("#"+EB).append(this.aFg);$("#"+DC).append(this.awS);$("#"+this.Dr).css(this.UH,Jo);$("#"+this.Eb).css(this.UH,Jo);$("#"+this.Ef).css(this.UH,Jo);var F=this;$(this.aGI).on(f6.cS.eG,function(){$(this).closest(F.atm).transition(F.aBn);$(this).closest(F.atm).find(F.EH).html("");$(document).attr(f6.O.iu,F.VH)})},ajN:function(){$("#"+this.Dr).addClass(this.Fa);$("#"+this.Dr).addClass(this.Fw);$("#"+this.Dr).find(this.EH).html("");$("#"+this.Eb).addClass(this.Fa);$("#"+this.Eb).addClass(this.Fw);$("#"+this.Eb).find(this.EH).html("");$("#"+this.Ef).addClass(this.Fa);$("#"+this.Ef).addClass(this.Fw);$("#"+this.Ef).find(this.EH).html("")}};f6.hs=function(bv){if(f6.iX.BI){$("#"+f6.iX.Dr+" > "+f6.iX.EH).append(bv+f6.iX.UE);$("#"+f6.iX.Dr).removeClass(f6.iX.Fa);$("#"+f6.iX.Dr).removeClass(f6.iX.Fw);f6.iX.Xc(bv)}};f6.af=function(bv){if(f6.iX.BI){$("#"+f6.iX.Eb+" > "+f6.iX.EH).append(bv+f6.iX.UE);$("#"+f6.iX.Eb).removeClass(f6.iX.Fa);$("#"+f6.iX.Eb).removeClass(f6.iX.Fw);f6.iX.Xc(bv)}};f6.dj=function(bv){if(f6.iX.BI){$("#"+f6.iX.Ef+" > "+f6.iX.EH).append(bv+f6.iX.UE);$("#"+f6.iX.Ef).removeClass(f6.iX.Fa);$("#"+f6.iX.Ef).removeClass(f6.iX.Fw);f6.iX.Xc(bv)}};f6.cV={mk:"e",Ru:"i_s",ahV:"k_s",ahX:"s_s",WU:"q_s",Xz:"q_bt_s",aaM:"uq_s",aeM:"as_s",akM:"o_s",atE:"mo_s",aqH:"co_s",atX:"mt_s",ahR:"ct_s",WZ:"t_s",aag:"ut_s",Yx:"tm_s",aaX:"um_s",atd:"a_s",auD:"m_s",Oa:"tk_s",asQ:"y_s",Ub:"rtk_s",QW:"ss_s",aqe:"gt_s",KZ:"r_c",ajE:"r_bt_c",aia:"k_c",aji:"q_c",aiA:"q_bt_c",Pb:"s_c",ajj:"t_c",ajt:"tm_c",aiJ:"a_c",aiw:"m_c",Qc:"ts_c",zl:"tf_c",Qh:"rts_c",zT:"rtf_c"};f6.hJ=function(Zh,IQ){this.et=Zh;this.bE=IQ};f6.gE=function(IQ){postMessage(new f6.hJ(f6.cV.mk,f6.R.auY+IQ))};f6.mn=function(Zh,IQ){postMessage(new f6.hJ(Zh,IQ))};f6.KQ={PD:"i_i_ok",aHq:"g_o_b_g_ok",aMX:"s_o_b_ok",aCv:"l_o_b_ok",aIo:"g_h_q_ok",aJS:"d_o_p_ok",aIR:"d_o_a_ok",aLk:"r_s_d",arY:"o_i_ok"};f6.cs={eB:"t",gJ:"b"};f6.fK=f6.cs.eB;f6.aDV=false;f6.tN=false;f6.kU={kG:1,aGx:2};f6.jL=f6.kU.kG;f6.ez=true;f6.Ac=false;f6.aD=10000;f6.gB=true;f6.yN={Bk:"r",Xv:"m"};f6.pu={nY:"p",cj:"t",apl:"m"};f6.eK={ql:"m",cL:"b",dR:"a",oT:"ba"};f6.L={K:"undefined",aGh:"[object Function]",C:"string",gr:"index",ap:"key",fI:"boolean",dk:"object",aja:"_blank",gM:"true",lV:"false",ase:"null",Dm:"_",anZ:Number.MIN_SAFE_INTEGER,zQ:Number.MAX_SAFE_INTEGER,aoP: -Number.MAX_VALUE,aSm:Number.MAX_VALUE,aoF: -9999999999,aTh:9999999999};f6.O={Te:"svg",T:"id",LU:"div",cX:"class",fQ:"g",acP:"url",afb:"clipPath",afh:"clip-path",jP:"rect",eD:"line",qK:"circle",eY:"x",eo:"y",nA:"dx",mX:"dy",cw:"x1",dG:"x2",bX:"y1",dM:"y2",gm:"cx",fW:"cy",jF:"r",fm:"width",eT:"height",gz:"opacity",ea:"fill",dc:"stroke",jD:"stroke-width",AL:"stroke-dasharray",jr:"transform",kn:"translate",aQQ:"rotate",ni:"text",fb:"font-size",lZ:"text-anchor",eZ:"start",aTt:"middle",jt:"end",pi:"drag",tY:"path",qO:"round",bE:"d",aii:"stroke-linejoin",air:"stroke-linecap",tu:"none",aQM:"svg-container",aRP:"svg-content-responsive",aQH:"viewBox",aTG:"preserveAspectRatio",aRb:"xMinYMin",aSr:"meet",BE:"active",bU:"cursor",aSy:"pointer",lL:"background-color",sH:"color",RH:"border",xY:"display",aiY:"block",aRz:"important",yw:"style",CJ:"src",aTC:"margin",iu:"title"};f6.aQs={aQK:"b",aQU:"d"};f6.ek={lb:"p",wW:"f",OX:"f_o",PN:"f_c",wQ:"t",su:"c",wE:"r",oJ:"m_c",rM:"m_r",sz:"b_c",qf:"m_n",sv:"a"};f6.rS=function(aws,mC,avi){if (mC) {
 return null;
}return aws.encode(avi)};f6.jJ={eP:"o",qi:"c",wb:"c_w_t",wC:"t",sv:"a"};f6.dh={bc:"o",cN:"h",bF:"p",cW:"s",nv:"c",rA:"m",Ah:"t",RC:"b",ra:"a",tc:"r",PE:"i",Rg:"f",TX:"l",qM:"k",ajH:"d",vs:"z",cZ:"e",uh:"x",qE:"v"};f6.yJ={nv:"Cancelled",rA:"Rejected",aRL:"Unknown",cZ:"Expired",bF:"Order Pending",bc:"Open Trade",cN:"Trade Closed",cW:"Swap Done"};f6.cS={lC:"message",mk:"error",eP:"open",qw:"resize",eG:"click",aSB:"submit",aty:"mousedown",atG:"mousemove",DR:"mouseup",aTL:"orientationchange",aKv:"change",azu:"customevent",GD:"touchstart",aJk:"focus",aPp:"blur"};f6.bd={oq:11,nk:0,MV:1,MW:2,Lt:3,LE:4,OC:5,PL:6,KR:7,Mw:8,PU:9,Zo:10,lU:7,lc:0,xF:1,yE:2,xg:3,ya:4,xR:5,Fz:6};f6.wt=function(NU){if (typeof NU==f6.L.K||NU==null) {
 return false;
}var wk={};return NU&&wk.toString.call(NU)===f6.L.aGh;};f6.bI=function(yM){if (typeof yM==f6.L.K||yM==null) {
 return false;
}return!isNaN(parseFloat(yM))&&isFinite(yM);};f6.by=function(yM){return!isNaN(yM)&&parseInt(Number(yM), 10)==yM&& !isNaN(parseInt(yM,10))};f6.cQ=function(adZ){if (typeof adZ==f6.L.K||adZ==null) {
 return false;
}return adZ.constructor===Array};f6.sL=function(EQ){
 if (typeof EQ!=f6.L.C) {
  return false;
 }if(EQ===""){return false}if(EQ==="inherit"){return false}if(EQ==="transparent"){return false}var GE=document.createElement("img");GE.style.color="rgb(0, 0, 0)";GE.style.color=EQ;if(GE.style.color!=="rgb(0, 0, 0)"){return true}GE.style.color="rgb(255, 255, 255)";GE.style.color=EQ;return GE.style.color!=="rgb(255, 255, 255)";
};f6.aqZ=function(axV){return!isNaN(new Date(axV).getTime())};f6.Mo=function(ajS){var Ij=[];for(var ap in ajS){Ij.push(encodeURIComponent(ap)+"="+encodeURIComponent(ajS[ap]))}return Ij.join("&")};f6.MB=function(bm){var jv=[];for(var i in bm){if(bm.hasOwnProperty(i)){if(typeof bm[i]==f6.L.C){jv.push(i+': "'+bm[i]+'"')}else if(f6.cQ(bm[i])){var QE=JSON.parse(JSON.stringify(bm[i]));for(var j in QE){if(QE[j]==null){QE[j]="null"}}jv.push(i+': ['+QE.join(', ')+']')}else{jv.push(i+": "+bm[i])}}}return jv};f6.bh={kA:"s1",kB:"s2",ln:"s3",kX:"s4",kD:"m1",kI:"m2",ks:"m3",kw:"m4",oj:"m5",kv:"m6",la:"m7",jN:"h1",mD:"h2",mb:"h3",kk:"h4",kJ:"h5",nj:"h6",lQ:"h7",lB:"d",lh:"w",lj:"m"};f6.dr={kA:"S5",kB:"S10",ln:"S15",kX:"S30",kD:"M1",kI:"M2",ks:"M4",kw:"M5",oj:"M10",kv:"M15",la:"M30",jN:"H1",mD:"H2",mb:"H3",kk:"H4",kJ:"H6",nj:"H8",lQ:"H12",lB:"D",lh:"W",lj:"M"};f6.rh=function(ao){if(ao==f6.bh.kA){return 5}else if(ao==f6.bh.kB){return 10}else if(ao==f6.bh.ln){return 15}else if(ao==f6.bh.kX){return 30}else if(ao==f6.bh.kD){return 60}else if(ao==f6.bh.kI){return 120}else if(ao==f6.bh.ks){return 240}else if(ao==f6.bh.kw){return 300}else if(ao==f6.bh.oj){return 600}else if(ao==f6.bh.kv){return 900}else if(ao==f6.bh.la){return 1800}else if(ao==f6.bh.jN){return 3600}else if(ao==f6.bh.mD){return 7200}else if(ao==f6.bh.mb){return 10800}else if(ao==f6.bh.kk){return 14400}else if(ao==f6.bh.kJ){return 21600}else if(ao==f6.bh.nj){return 28800}else if(ao==f6.bh.lQ){return 43200}else if(ao==f6.bh.lB){return 86400}else{return null}};f6.uE=function(ao){if(ao==f6.bh.kA){return f6.dr.kA}else if(ao==f6.bh.kB){return f6.dr.kB}else if(ao==f6.bh.ln){return f6.dr.ln}else if(ao==f6.bh.kX){return f6.dr.kX}else if(ao==f6.bh.kD){return f6.dr.kD}else if(ao==f6.bh.kI){return f6.dr.kI}else if(ao==f6.bh.ks){return f6.dr.ks}else if(ao==f6.bh.kw){return f6.dr.kw}else if(ao==f6.bh.oj){return f6.dr.oj}else if(ao==f6.bh.kv){return f6.dr.kv}else if(ao==f6.bh.la){return f6.dr.la}else if(ao==f6.bh.jN){return f6.dr.jN}else if(ao==f6.bh.mD){return f6.dr.mD}else if(ao==f6.bh.mb){return f6.dr.mb}else if(ao==f6.bh.kk){return f6.dr.kk}else if(ao==f6.bh.kJ){return f6.dr.kJ}else if(ao==f6.bh.nj){return f6.dr.nj}else if(ao==f6.bh.lQ){return f6.dr.lQ}else if(ao==f6.bh.lB){return f6.dr.lB}else if(ao==f6.bh.lh){return f6.dr.lh}else if(ao==f6.bh.lj){return f6.dr.lj}else{return null}};f6.MF=function(dS){if(dS==f6.dr.kA){return f6.bh.kA}else if(dS==f6.dr.kB){return f6.bh.kB}else if(dS==f6.dr.ln){return f6.bh.ln}else if(dS==f6.dr.kX){return f6.bh.kX}else if(dS==f6.dr.kD){return f6.bh.kD}else if(dS==f6.dr.kI){return f6.bh.kI}else if(dS==f6.dr.ks){return f6.bh.ks}else if(dS==f6.dr.kw){return f6.bh.kw}else if(dS==f6.dr.oj){return f6.bh.oj}else if(dS==f6.dr.kv){return f6.bh.kv}else if(dS==f6.dr.la){return f6.bh.la}else if(dS==f6.dr.jN){return f6.bh.jN}else if(dS==f6.dr.mD){return f6.bh.mD}else if(dS==f6.dr.mb){return f6.bh.mb}else if(dS==f6.dr.kk){return f6.bh.kk}else if(dS==f6.dr.kJ){return f6.bh.kJ}else if(dS==f6.dr.nj){return f6.bh.nj}else if(dS==f6.dr.lQ){return f6.bh.lQ}else if(dS==f6.dr.lB){return f6.bh.lB}else if(dS==f6.dr.lh){return f6.bh.lh}else if(dS==f6.dr.lj){return f6.bh.lj}else{return null}};f6.ti=function(mC,abq){if (mC) {
 return null;
}return abq.replace(/\r?\n|\r/g,"").trim()};f6.TJ=function(ao){if(ao==f6.bh.lh||ao==f6.bh.lj){return true}else{return false}};f6.aEC=function(ao){if(ao==f6.bh.lh){return true}else{return false}};f6.aUe=function(ao){if(ao==f6.bh.lj){return true}else{return false}};f6.Cl=function(ao){if(ao!=f6.bh.lh&&ao!=f6.bh.lj&&ao!=f6.bh.kA&&ao!=f6.bh.kB&&ao!=f6.bh.ln&&ao!=f6.bh.kX){return true}else{return false}};f6.aee=function(ao){if(ao==f6.bh.kA){return true}else if(ao==f6.bh.kB){return true}else if(ao==f6.bh.ln){return true}else if(ao==f6.bh.kX){return true}else if(ao==f6.bh.kD){return true}else if(ao==f6.bh.kI){return true}else if(ao==f6.bh.ks){return true}else if(ao==f6.bh.kw){return true}else if(ao==f6.bh.oj){return true}else if(ao==f6.bh.kv){return true}else if(ao==f6.bh.la){return true}else if(ao==f6.bh.jN){return true}else if(ao==f6.bh.mD){return true}else if(ao==f6.bh.mb){return true}else if(ao==f6.bh.kk){return true}else if(ao==f6.bh.kJ){return true}else if(ao==f6.bh.nj){return true}else if(ao==f6.bh.lQ){return true}else if(ao==f6.bh.lB){return true}else if(ao==f6.bh.lh){return true}else if(ao==f6.bh.lj){return true}else{return false}};f6.fR={sN:"%m-%d %H:%M",BA:"%y-%m-%d",nr:"%y-%m-%d %H:%M"};f6.Ov=function(ao){if(ao==f6.bh.kA){return f6.fR.sN}else if(ao==f6.bh.kB){return f6.fR.sN}else if(ao==f6.bh.ln){return f6.fR.sN}else if(ao==f6.bh.kX){return f6.fR.sN}else if(ao==f6.bh.kD){return f6.fR.sN}else if(ao==f6.bh.kI){return f6.fR.sN}else if(ao==f6.bh.ks){return f6.fR.sN}else if(ao==f6.bh.kw){return f6.fR.sN}else if(ao==f6.bh.oj){return f6.fR.sN}else if(ao==f6.bh.kv){return f6.fR.sN}else if(ao==f6.bh.la){return f6.fR.sN}else if(ao==f6.bh.jN){return f6.fR.sN}else if(ao==f6.bh.mD){return f6.fR.sN}else if(ao==f6.bh.mb){return f6.fR.BA}else if(ao==f6.bh.kk){return f6.fR.BA}else if(ao==f6.bh.kJ){return f6.fR.BA}else if(ao==f6.bh.nj){return f6.fR.BA}else if(ao==f6.bh.lQ){return f6.fR.BA}else if(ao==f6.bh.lB){return f6.fR.BA}else{return f6.fR.BA}};f6.ae={Ic:"Authorization",AU:"Bearer",arp:"Content-Type",atz:"Accept-Datetime-Format",auT:"UNIX",ajB:"application/json",iF:"application/json; charset=utf-8",gH:"POST",Af:"PUT",fh:"GET",hO:"json",aD:"timeout"};f6.ab={dN:1,fk:2,gs:3,ir:4,gP:5,iq:6,GI:7,Fb:8,Gg:9,EU:10};f6.ku={dN:"BUY",fk:"SELL",gs:"BUY LIMIT",ir:"SELL LIMIT",gP:"BUY STOP",iq:"SELL STOP"};f6.FI={dN:"B",fk:"S",gs:"B L",ir:"S L",gP:"B S",iq:"S S"};f6.ss=function(abq,mC,avu){if (mC) {
 return null;
}return abq.charCodeAt(avu)};f6.aGX=function(){return[f6.ab.dN,f6.ab.fk,f6.ab.gs,f6.ab.ir,f6.ab.gP,f6.ab.iq]};f6.pY=function(aj){if(aj==f6.ab.dN){return f6.ku.dN}else if(aj==f6.ab.fk){return f6.ku.fk}else if(aj==f6.ab.gs){return f6.ku.gs}else if(aj==f6.ab.ir){return f6.ku.ir}else if(aj==f6.ab.gP){return f6.ku.gP}else if(aj==f6.ab.iq){return f6.ku.iq}else{return ""}};f6.vL=function(aj){if(aj==f6.ab.dN){return f6.FI.dN}else if(aj==f6.ab.fk){return f6.FI.fk}else if(aj==f6.ab.gs){return f6.FI.gs}else if(aj==f6.ab.ir){return f6.FI.ir}else if(aj==f6.ab.gP){return f6.FI.gP}else if(aj==f6.ab.iq){return f6.FI.iq}else{return ""}};f6.aoM=function(eL){if(eL==f6.ku.dN){return f6.ab.dN}else if(eL==f6.ku.fk){return f6.ab.fk}else if(eL==f6.ku.gs){return f6.ab.gs}else if(eL==f6.ku.ir){return f6.ab.ir}else if(eL==f6.ku.gP){return f6.ab.gP}else if(eL==f6.ku.iq){return f6.ab.iq}else{return null}};f6.asX={uU:"L",zX:"S"};f6.aRx={uU:"Limit",zX:"Stop"};f6.Lm={UG:"L",vl:"H"};f6.mx={HC:0,auW:1,aqJ:2,avQ:3,auz:4,apa:5,LT:6};f6.aHF=function(vK){if(vK==f6.mx.HC){return "Sunday"}else if(vK==f6.mx.auW){return "Monday"}else if(vK==f6.mx.aqJ){return "Tuesday"}else if(vK==f6.mx.avQ){return "Wednesday"}else if(vK==f6.mx.auz){return "Thursday"}else if(vK==f6.mx.apa){return "Friday"}else if(vK==f6.mx.LT){return "Saturday"}else{return ""}};f6.Lf={agP:1,agc:2};f6.ci=function(aeO,aEL){var aGY=aeO.callee.name;var aiz=[];for(var i=0;i<aeO.length;i += 1){aiz.push(aeO[i])}return f6.R.axb+aGY+"("+aiz.join(", ")+")"+", "+f6.R.aDG+aEL};f6.ig={sC:"n",fI:"b",C:"s",te:"i"};f6.ub={sC:"Number",fI:"Boolean",C:"String",te:"Integer"};f6.afQ=function(hi){if(hi==f6.ig.sC){return f6.ub.sC}else if(hi==f6.ig.fI){return f6.ub.fI}else if(hi==f6.ig.C){return f6.ub.C}else if(hi==f6.ig.te){return f6.ub.te}else{return null}};f6.ajD=function(Tf){if(Tf==f6.ub.sC){return f6.ig.sC}else if(Tf==f6.ub.fI){return f6.ig.fI}else if(Tf==f6.ub.C){return f6.ig.C}else if(Tf==f6.ub.te){return f6.ig.te}else{return null}};f6.Ao={jg:"shift"};f6.NQ={iA:"A",ahT:"B"};f6.oI={Is:function(context){},LA:function(context){},Kl:function(context){},VQ:function(context){}};f6.Gt={aT:"fintechee.cloud",jC:"fintechee.cloud",jz:"fintechee.cloud"};f6.Gr={aT:"",jC:"",jz:""};f6.Bb={aT:"https://",jC:"https://",jz:"https://"};f6.arr={aQL:"Channel-Sea",amA:"Chart-Coaster"};f6.Sn={Oi:"0"};f6.aqB=function(){return[f6.bh.kD,f6.bh.kw,f6.bh.kv,f6.bh.la,f6.bh.jN,f6.bh.kk,f6.bh.lB,f6.bh.lh,f6.bh.lj]};f6.ast=function(){return f6.bh.kD};f6.aHG=function(){return[500,1000,2000,5000,10000,20000,50000,100000,1000000]};f6.VW={aT:"channel-sea.cc",jC:"channel-sea.cc",jz:"channel-sea.cc"};f6.aY={aT:"fe",jC:"od",jz:"ol"};f6.Vf={aT:"Fintechee Demo",jC:"Oanda Demo (Browser must be Firefox)",jz:"Oanda Live (Browser must be Firefox)"};f6.Lc={aT:"Fintechee Demo",jC:"Oanda Demo",jz:"Oanda Live"};f6.oR={aT:"c",zt:"o"};f6.FE=[];f6.FE[f6.aY.aT]=f6.oR.aT;f6.FE[f6.aY.jC]=f6.oR.zt;f6.FE[f6.aY.jz]=f6.oR.zt;f6.ad=[];f6.ad[f6.aY.aT]={bQ:[],Sf:false,G:f6.aY.aT,adt:f6.Bb.aT+f6.Gt.aT+f6.Gr.aT,acw:f6.Bb.aT+f6.Gt.aT+f6.Gr.aT,XE:f6.Bb.aT+f6.Gt.aT+f6.Gr.aT,XM:f6.Bb.aT+f6.Gt.aT+f6.Gr.aT,afo:f6.Bb.aT+f6.VW.aT,Ts:"/images/logo.png",kf:["EUR/USD"],hc:"Technology Service Provider",qm:21,lO:21,qj:100,ou:true,aV:"USD",ce:100000,bG:100,rj:50,qk:0.01,oO:false,uf:null,ru:null,eR: -1,oX:false,nJ:false,lA:false,oV:false,oM:0,TL:"/getSS",Ph:"/signinByTradeToken",Pn:"/signinToTrade",Pm:"/signinToWatch",Sq:"/quickRegister",Sx:"/register",NA:"/changePassword",RO:"/sendResetPwMail",Nx:"/resetPassword",OI:"/getDefaultAccForInvestor",Rw:"/setWatchable",OK:"/setNotWatchable",SU:"/acceptOneClick",Tq:"/rejectOneClick",TU:"/triggerMfa",QH:"/setMfaEnabled",QM:"/setMfaDisabled",MR:"/verifyMfa"};f6.mI={eB:"TRADE",rq:"INVESTOR"};f6.anI=[];f6.aLa=function(ay){f6.anI=ay};f6.HS=function(){return f6.anI};f6.yV=function(G,H){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null&&f6.cQ(f6.ad[G].bQ)){var dz=null;for(var i in f6.ad[G].bQ){if(f6.ad[G].bQ[i].H==H){if(typeof f6.ad[G].bQ[i].cj==f6.L.C){return f6.mI.eB}else if(typeof f6.ad[G].bQ[i].dW==f6.L.C){return f6.mI.rq}else{return f6.mI.rq}}}return f6.mI.rq}else{return f6.mI.rq}};f6.kH=function(G,H){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null&&f6.cQ(f6.ad[G].bQ)){var dz=null;for(var i in f6.ad[G].bQ){if(f6.ad[G].bQ[i].H==H){dz={cj:f6.ad[G].bQ[i].cj,dW:f6.ad[G].bQ[i].dW,fr:f6.ad[G].bQ[i].fr};break}}return dz}else{return null}};f6.oH=function(G,H){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null&&f6.cQ(f6.ad[G].bQ)){var J=null;for(var i in f6.ad[G].bQ){if(f6.ad[G].bQ[i].H==H){J=f6.ad[G].bQ[i].J;break}}return J}else{return null}};f6.aiO=function(G,H,J){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null&&f6.cQ(f6.ad[G].bQ)){for(var i in f6.ad[G].bQ){if(f6.ad[G].bQ[i].H==H){f6.ad[G].bQ[i].J=J;return true}}}return false};f6.iL=function(G,H){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null&&f6.cQ(f6.ad[G].bQ)){var bS=null;for(var i in f6.ad[G].bQ){if(f6.ad[G].bQ[i].H==H){bS={cj:f6.ad[G].bQ[i].cj,dW:f6.ad[G].bQ[i].dW};break}}if(bS!=null){if(bS.cj!=null){return f6.mI.eB+" "+bS.cj}else if(bS.dW!=null){return f6.mI.rq+" "+bS.dW}else{return f6.mI.rq}}else{return f6.mI.rq}}else{return f6.mI.rq}};f6.aGV=function(){var bQ=[];for(var i in f6.ad){for(var j in f6.ad[i].bQ){bQ.push({G:f6.ad[i].bQ[j].G,H:f6.ad[i].bQ[j].H})}}return bQ};f6.HE=function(G,H,cj,dW,fr,J){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null&&f6.cQ(f6.ad[G].bQ)){for(var i in f6.ad[G].bQ){if(f6.ad[G].bQ[i].H==H){f6.ad[G].bQ[i]={G:G,H:H,cj:cj,dW:dW,fr:fr,J:J};return f6.ad[G].bQ[i]}}f6.ad[G].bQ.push({G:G,H:H,cj:cj,dW:dW,fr:fr,J:J});return true}return false};f6.FX=function(G,H){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null&&f6.cQ(f6.ad[G].bQ)){for(var i in f6.ad[G].bQ){if(f6.ad[G].bQ[i].H==H){f6.ad[G].bQ.splice(parseInt(i, 10),1);return true}}}return false};f6.oS=function(G){if(typeof f6.FE[G]!=f6.L.K){return f6.FE[G]}else{return f6.oR.aT}};f6.arU=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].adt}else{return f6.ad[f6.aY.aT].adt}};f6.abM=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].acw}else{return f6.ad[f6.aY.aT].acw}};f6.NX=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].XE}else{return f6.ad[f6.aY.aT].XE}};f6.fw=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].XM}else{return f6.ad[f6.aY.aT].XM}};f6.amx=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].afo}else{return f6.ad[f6.aY.aT].afo}};f6.DK=function(){var gD=[];for(var i in f6.ad){gD.push(f6.ad[i].G)}return gD};f6.ev=function(G){for(var i in f6.aY){if(G==f6.aY[i]){return f6.Lc[i]}}return null};f6.OU=function(G){for(var i in f6.aY){if(G==f6.aY[i]){return f6.Vf[i]}}return null};f6.AD=function(am){for(var i in f6.Lc){if(am==f6.Lc[i]){return f6.aY[i]}}return null};f6.QN=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Ts}else{return f6.ad[f6.aY.aT].Ts}};f6.aHd=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].kf}else{return f6.ad[f6.aY.aT].kf}};f6.aHO=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].hc}else{return f6.ad[f6.aY.aT].hc}};f6.aTo=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].qm}else{return f6.ad[f6.aY.aT].qm}};f6.aTn=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].lO}else{return f6.ad[f6.aY.aT].lO}};f6.aKo=function(){var zq=[];for(var i in f6.ad){for(var j in f6.ad[i].bQ){zq.push({G:f6.ad[i].bQ[j].G,H:f6.ad[i].bQ[j].H,lO:f6.ad[i].lO})}}return zq};f6.aHK=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].qj}else{return f6.ad[f6.aY.aT].qj}};f6.aqu=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].ou}else{return f6.ad[f6.aY.aT].ou}};f6.IC=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].aV}else{return f6.ad[f6.aY.aT].aV}};f6.na=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].ce}else{return f6.ad[f6.aY.aT].ce}};f6.uD=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].bG}else{return f6.ad[f6.aY.aT].bG}};f6.aGZ=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].rj}else{return f6.ad[f6.aY.aT].rj}};f6.Tz=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].qk}else{return f6.ad[f6.aY.aT].qk}};f6.apE=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].oO}else{return f6.ad[f6.aY.aT].oO}};f6.aHv=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].uf}else{return f6.ad[f6.aY.aT].uf}};f6.aGO=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].ru}else{return f6.ad[f6.aY.aT].ru}};f6.FQ=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].eR}else{return f6.ad[f6.aY.aT].eR}};f6.nq=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].oX}else{return f6.ad[f6.aY.aT].oX}};f6.aem=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].nJ}else{return f6.ad[f6.aY.aT].nJ}};f6.aUa=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].lA}else{return f6.ad[f6.aY.aT].lA}};f6.yf=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].oV}else{return f6.ad[f6.aY.aT].oV}};f6.ahA=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].oM}else{return f6.ad[f6.aY.aT].oM}};f6.aIQ=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Ph}else{return f6.ad[f6.aY.aT].Ph}};f6.aJI=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Pn}else{return f6.ad[f6.aY.aT].Pn}};f6.aJm=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Pm}else{return f6.ad[f6.aY.aT].Pm}};f6.aIm=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Sq}else{return f6.ad[f6.aY.aT].Sq}};f6.alV=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Sx}else{return f6.ad[f6.aY.aT].Sx}};f6.aHk=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].NA}else{return f6.ad[f6.aY.aT].NA}};f6.aIc=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].RO}else{return f6.ad[f6.aY.aT].RO}};f6.aIx=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Nx}else{return f6.ad[f6.aY.aT].Nx}};f6.aHT=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].OI}else{return f6.ad[f6.aY.aT].OI}};f6.aIU=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Rw}else{return f6.ad[f6.aY.aT].Rw}};f6.aJj=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].OK}else{return f6.ad[f6.aY.aT].OK}};f6.aIr=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].SU}else{return f6.ad[f6.aY.aT].SU}};f6.aHM=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Tq}else{return f6.ad[f6.aY.aT].Tq}};f6.aIK=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].TU}else{return f6.ad[f6.aY.aT].TU}};f6.aKk=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].QH}else{return f6.ad[f6.aY.aT].QH}};f6.aKw=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].QM}else{return f6.ad[f6.aY.aT].QM}};f6.aJf=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].MR}else{return f6.ad[f6.aY.aT].MR}};f6.aKh=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].Sf}else{return f6.ad[f6.aY.aT].Sf}};f6.FY=function(G,ei){if(typeof f6.ad[G]!=f6.L.K){f6.ad[G].Sf=ei}};f6.aHa=function(G){if(typeof f6.ad[G]!=f6.L.K){return f6.ad[G].TL}else{return f6.ad[f6.aY.aT].TL}};f6.anj=function(G){var F=this;return new Promise(function(cC,aW){var am=f6.ev(G);var aF=function(aM){var bv=null;if(typeof aM.brokerName==f6.L.C&&aM.brokerName==G&&typeof aM.defaultSymbolNames==f6.L.C&&typeof aM.desc==f6.L.C&&typeof aM.startEndHour==f6.L.C&&typeof aM.swapCalcHour==f6.L.C&&typeof aM.pendingOdrsOpenTrdsNumLimit==f6.L.C&&typeof aM.demoMode==f6.L.C&&typeof aM.currency==f6.L.C&&typeof aM.lotsUnit==f6.L.C&&typeof aM.toFixed==f6.L.C&&typeof aM.commentLengthLimit==f6.L.C&&typeof aM.lotsPerOrder==f6.L.C&&typeof aM.externalData==f6.L.C&&typeof aM.externalURL==f6.L.C&&typeof aM.externalTk==f6.L.C&&typeof aM.externalMode==f6.L.C&&typeof aM.spreadBetting==f6.L.C&&typeof aM.brokerless==f6.L.C&&typeof aM.creditsOnboard==f6.L.C&&typeof aM.localHostMode==f6.L.C){try{
 var kf=JSON.parse(aM.defaultSymbolNames);if(f6.cQ(kf)){for(var i in kf){if(typeof kf[i]!=f6.L.C){throw new Error(f6.R.nP+"(defaultSymbolNames, "+am+", "+aM.defaultSymbolNames+")")}}}else{throw new Error(f6.R.nP+"(defaultSymbolNames, "+am+", "+aM.defaultSymbolNames+")")}var qm=null;if(f6.by(aM.startEndHour)){qm=parseInt(aM.startEndHour, 10)}else{throw new Error(f6.R.nP+"(startEndHour, "+am+", "+aM.startEndHour+")")}var lO=null;if(f6.by(aM.swapCalcHour)){lO=parseInt(aM.swapCalcHour, 10)}else{throw new Error(f6.R.nP+"(swapCalcHour, "+am+", "+aM.swapCalcHour+")")}var qj=null;if(f6.by(aM.pendingOdrsOpenTrdsNumLimit)){qj=parseInt(aM.pendingOdrsOpenTrdsNumLimit, 10)}else{throw new Error(f6.R.nP+"(pendingOdrsOpenTrdsNumLimit, "+am+", "+aM.pendingOdrsOpenTrdsNumLimit+")")}var ou=null;if(aM.demoMode==f6.L.gM){ou=true}else if(aM.demoMode==f6.L.lV){ou=false}else{throw new Error(f6.R.nP+"(demoMode, "+am+", "+aM.demoMode+")")}var ce=null;if(f6.bI(aM.lotsUnit)){ce=parseFloat(aM.lotsUnit)}else{throw new Error(f6.R.nP+"(lotsUnit, "+am+", "+aM.lotsUnit+")")}var bG=null;if(f6.by(aM.toFixed)){bG=parseInt(aM.toFixed, 10)}else{throw new Error(f6.R.nP+"(toFixed, "+am+", "+aM.toFixed+")")}var rj=null;if(f6.by(aM.commentLengthLimit)){rj=parseInt(aM.commentLengthLimit, 10)}else{throw new Error(f6.R.nP+"(commentLengthLimit, "+am+", "+aM.commentLengthLimit+")")}var qk=null;if(f6.bI(aM.lotsPerOrder)){qk=parseFloat(aM.lotsPerOrder)}else{throw new Error(f6.R.nP+"(lotsPerOrder, "+am+", "+aM.lotsPerOrder+")")}var oO=null;if(aM.externalData==f6.L.gM){oO=true}else if(aM.externalData==f6.L.lV){oO=false}else{throw new Error(f6.R.nP+"(externalData, "+am+", "+aM.externalData+")")}var eR=null;if(f6.by(aM.externalMode)){eR=parseInt(aM.externalMode, 10)}else{throw new Error(f6.R.nP+"(toFixed, "+am+", "+aM.externalMode+")")}var oX=null;if(aM.spreadBetting==f6.L.gM){oX=true}else if(aM.spreadBetting==f6.L.lV){oX=false}else{throw new Error(f6.R.nP+"(spreadBetting, "+am+", "+aM.spreadBetting+")")}var nJ=null;if(aM.brokerless==f6.L.gM){nJ=true}else if(aM.brokerless==f6.L.lV){nJ=false}else{throw new Error(f6.R.nP+"(brokerless, "+am+", "+aM.brokerless+")")}var lA=null;if(aM.creditsOnboard==f6.L.gM){lA=true}else if(aM.creditsOnboard==f6.L.lV){lA=false}else{throw new Error(f6.R.nP+"(creditsOnboard, "+am+", "+aM.creditsOnboard+")")}var oV=null;if(aM.localHostMode==f6.L.gM){oV=true}else if(aM.localHostMode==f6.L.lV){oV=false}else{throw new Error(f6.R.nP+"(localHostMode, "+am+", "+aM.localHostMode+")")}var oM=0;if(f6.by(aM.customMode)){oM=parseInt(aM.customMode, 10)}f6.ad[G].kf=kf;f6.ad[G].hc=aM.desc;f6.ad[G].qm=qm;f6.ad[G].lO=lO;f6.ad[G].qj=qj;f6.ad[G].ou=ou;f6.ad[G].aV=aM.currency;f6.ad[G].ce=ce;f6.ad[G].bG=bG;f6.ad[G].rj=rj;f6.ad[G].qk=qk;f6.ad[G].oO=oO;f6.ad[G].uf=aM.externalURL;f6.ad[G].ru=aM.externalTk;f6.ad[G].eR=eR;f6.ad[G].oX=oX;f6.ad[G].nJ=nJ;f6.ad[G].lA=lA;f6.ad[G].oV=oV;f6.ad[G].oM=oM;f6.FY(G,true);cC();
}catch(e){f6.FY(G,true);f6.af(e.message);f6.az(e.message);aW()}}else{f6.FY(G,true);bv=f6.R.nP+"("+am+")";f6.af(bv);f6.az(bv);aW()}};$.ajax({url:f6.fw(G)+f6.aHa(G),type:f6.ae.gH,data:JSON.stringify({brokerName:G}),contentType:f6.ae.iF,dataType:f6.ae.hO,timeout:f6.aD,success:aF,error:function(dO,ei,bv){if(ei===f6.ae.aD){f6.FY(G,true);f6.af(f6.R.aD+"("+am+")");f6.az(f6.R.aD+"("+am+")")}else{f6.FY(G,true);f6.af(bv+"("+am+")");f6.az(bv+"("+am+")")}aW()}})})};f6.aKu=function(){var ja=[];for(var i in f6.ad){ja.push({G:f6.ad[i].G,kf:f6.ad[i].kf,hc:f6.ad[i].hc,qm:f6.ad[i].qm,lO:f6.ad[i].lO,qj:f6.ad[i].qj,ou:f6.ad[i].ou,aV:f6.ad[i].aV,ce:f6.ad[i].ce,bG:f6.ad[i].bG,rj:f6.ad[i].rj,qk:f6.ad[i].qk,oO:f6.ad[i].oO,uf:f6.ad[i].uf,ru:f6.ad[i].ru,eR:f6.ad[i].eR,oX:f6.ad[i].oX,nJ:f6.ad[i].nJ,lA:f6.ad[i].lA,oV:f6.ad[i].oV,oM:f6.ad[i].oM})}return ja};f6.aOq=function(ja){for(var i in ja){var G=ja[i].G;if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null){f6.ad[G].kf=ja[i].kf;f6.ad[G].hc=ja[i].hc;f6.ad[G].qm=ja[i].qm;f6.ad[G].lO=ja[i].lO;f6.ad[G].qj=ja[i].qj;f6.ad[G].ou=ja[i].ou;f6.ad[G].aV=ja[i].aV;f6.ad[G].ce=ja[i].ce;f6.ad[G].bG=ja[i].bG;f6.ad[G].rj=ja[i].rj;f6.ad[G].qk=ja[i].qk;f6.ad[G].oO=ja[i].oO;f6.ad[G].uf=ja[i].uf;f6.ad[G].ru=ja[i].ru;f6.ad[G].eR=ja[i].eR;f6.ad[G].oX=ja[i].oX;f6.ad[G].nJ=ja[i].nJ;f6.ad[G].lA=ja[i].lA;f6.ad[G].oV=ja[i].oV;f6.ad[G].oM=ja[i].oM;f6.FY(G,true)}}};f6.Ig=function(G){var dZ=null;for(var i in f6.ad){if(G==f6.ad[i].G){dZ={kf:f6.ad[G].kf,hc:f6.ad[G].hc,qm:f6.ad[G].qm,lO:f6.ad[G].lO,qj:f6.ad[G].qj,ou:f6.ad[G].ou,aV:f6.ad[G].aV,ce:f6.ad[G].ce,bG:f6.ad[G].bG,rj:f6.ad[G].rj,qk:f6.ad[G].qk,oO:f6.ad[G].oO,uf:f6.ad[G].uf,ru:f6.ad[G].ru,eR:f6.ad[G].eR,oX:f6.ad[G].oX,nJ:f6.ad[G].nJ,lA:f6.ad[G].lA,oV:f6.ad[G].oV,oM:f6.ad[G].oM};break}}return dZ};f6.Re=function(G,dZ){if(typeof f6.ad[G]!=f6.L.K&&f6.ad[G]!=null){f6.ad[G].kf=dZ.kf;f6.ad[G].hc=dZ.hc;f6.ad[G].qm=dZ.qm;f6.ad[G].lO=dZ.lO;f6.ad[G].qj=dZ.qj;f6.ad[G].ou=dZ.ou;f6.ad[G].aV=dZ.aV;f6.ad[G].ce=dZ.ce;f6.ad[G].bG=dZ.bG;f6.ad[G].rj=dZ.rj;f6.ad[G].qk=dZ.qk;f6.ad[G].oO=dZ.oO;f6.ad[G].uf=dZ.uf;f6.ad[G].ru=dZ.ru;f6.ad[G].eR=dZ.eR;f6.ad[G].oX=dZ.oX;f6.ad[G].nJ=dZ.nJ;f6.ad[G].lA=dZ.lA;f6.ad[G].oV=dZ.oV;f6.ad[G].oM=dZ.oM}};f6.aRM=function(){var nV=0;for(var i in f6.ad){nV += 1}return nV};f6.aHl=function(){return f6.aY.aT};f6.IE=function(){try{if(typeof brokerDomain!=f6.L.K){for(var i in brokerDomain){if(typeof f6.Gt[i]==f6.L.K){f6.Gt[i]=brokerDomain[i]}else{throw new Error(f6.R.zO+"(brokerDomain."+i+")")}}}if(typeof brokerPort!=f6.L.K){for(var i in brokerPort){if(typeof f6.Gr[i]==f6.L.K){f6.Gr[i]=brokerPort[i]}else{throw new Error(f6.R.zO+"(brokerPort."+i+")")}}}if(typeof brokerProtocol!=f6.L.K){for(var i in brokerProtocol){if(typeof f6.Bb[i]==f6.L.K){f6.Bb[i]=brokerProtocol[i]}else{throw new Error(f6.R.zO+"(brokerProtocol."+i+")")}}}if(typeof shopDomain!=f6.L.K){for(var i in shopDomain){if(typeof f6.VW[i]==f6.L.K){f6.VW[i]=shopDomain[i]}else{throw new Error(f6.R.zO+"(shopDomain."+i+")")}}}if(typeof brokerName!=f6.L.K){for(var i in brokerName){if(typeof f6.aY[i]==f6.L.K){f6.aY[i]=brokerName[i]}else{throw new Error(f6.R.zO+"(brokerName."+i+")")}}}if(typeof signInShownBrokerName!=f6.L.K){for(var i in signInShownBrokerName){if(typeof f6.Vf[i]==f6.L.K){f6.Vf[i]=signInShownBrokerName[i]}else{throw new Error(f6.R.zO+"(signInShownBrokerName."+i+")")}}}if(typeof shownBrokerName!=f6.L.K){for(var i in shownBrokerName){if(typeof f6.Lc[i]==f6.L.K){f6.Lc[i]=shownBrokerName[i]}else{throw new Error(f6.R.zO+"(shownBrokerName."+i+")")}}}if(typeof brokerCtx!=f6.L.K){for(var i in brokerCtx){if(typeof f6.ad[i]==f6.L.K){f6.ad[i]={bQ:[],Sf:false,G:brokerCtx[i].brokerName,adt:brokerCtx[i].dataStreamURL,acw:brokerCtx[i].dataBaseURL,XE:brokerCtx[i].orderStreamURL,XM:brokerCtx[i].orderBaseURL,afo:brokerCtx[i].shopURL,Ts:brokerCtx[i].logoURL,kf:brokerCtx[i].defaultSymbolNames,hc:brokerCtx[i].desc,qm:brokerCtx[i].startEndHour,lO:brokerCtx[i].swapCalcHour,qj:brokerCtx[i].pendingOdrsOpenTrdsNumLimit,ou:brokerCtx[i].demoMode,aV:brokerCtx[i].currency,ce:brokerCtx[i].lotsUnit,bG:brokerCtx[i].toFixed,rj:brokerCtx[i].commentLengthLimit,qk:brokerCtx[i].lotsPerOrder,oO:brokerCtx[i].externalData,uf:brokerCtx[i].externalURL,ru:brokerCtx[i].externalTk,eR:brokerCtx[i].externalMode,oX:brokerCtx[i].oX,nJ:brokerCtx[i].nJ,lA:brokerCtx[i].lA,oV:brokerCtx[i].oV,oM:brokerCtx[i].oM,TL:f6.ad[f6.aY.aT].TL,Ph:f6.ad[f6.aY.aT].Ph,Pn:f6.ad[f6.aY.aT].Pn,Pm:f6.ad[f6.aY.aT].Pm,Sq:f6.ad[f6.aY.aT].Sq,Sx:f6.ad[f6.aY.aT].Sx,NA:f6.ad[f6.aY.aT].NA,RO:f6.ad[f6.aY.aT].RO,Nx:f6.ad[f6.aY.aT].Nx,OI:f6.ad[f6.aY.aT].OI,Rw:f6.ad[f6.aY.aT].Rw,OK:f6.ad[f6.aY.aT].OK,SU:f6.ad[f6.aY.aT].SU,Tq:f6.ad[f6.aY.aT].Tq,TU:f6.ad[f6.aY.aT].TU,QH:f6.ad[f6.aY.aT].QH,QM:f6.ad[f6.aY.aT].QM,MR:f6.ad[f6.aY.aT].MR};f6.FE[i]=f6.oR.aT}else{throw new Error(f6.R.zO+"(brokerCtx."+i+")")}}}return true}catch(e){f6.af(e.message);f6.az(e.message);return false}};f6.zf="FINTECHEE";self.addEventListener(f6.cS.mk,function(aI){});self.addEventListener(f6.cS.lC,function(aI){if(aI.data.et==f6.cV.Ru){f6.IE();f6.fK=aI.data.bE.jq;f6o.jH[f6.oR.aT].aaq(f6o.fo);f6o.jH[f6.oR.aT].agC(f6o.hA);if(typeof AG!=f6.L.K&&AG!=null){f6o.jH[f6.oR.zt].aaq(AG)}f6o.jH[f6.oR.zt].agC(f6o.hA);f6o.hA.aOj(f6o.jH);f6.mn(f6.cV.KZ,f6.KQ.arY)}else if(aI.data.et==f6.cV.WZ){f6o.hA.xi(aI.data.bE)}else if(aI.data.et==f6.cV.aag){f6o.hA.yp(aI.data.bE)}else if(aI.data.et==f6.cV.Yx){f6o.hA.Eu(aI.data.bE)}else if(aI.data.et==f6.cV.aaX){f6o.hA.zM(aI.data.bE)}else if(aI.data.et==f6.cV.aqe){f6o.hA.abh(aI.data.bE)}else if(aI.data.et==f6.cV.akM){f6o.hA.zo(aI.data.bE)}else if(aI.data.et==f6.cV.atE){f6o.hA.Ey(aI.data.bE)}else if(aI.data.et==f6.cV.aqH){f6o.hA.DP(aI.data.bE)}else if(aI.data.et==f6.cV.atX){f6o.hA.CX(aI.data.bE)}else if(aI.data.et==f6.cV.ahR){f6o.hA.wF(aI.data.bE)}else if(aI.data.et==f6.cV.aeM){f6o.hA.vf(aI.data.bE)}else if(aI.data.et==f6.cV.atd){f6o.hA.SM(aI.data.bE)}else if(aI.data.et==f6.cV.auD){f6o.hA.Dn(aI.data.bE)}else if(aI.data.et==f6.cV.Oa){var eS=aI.data.bE;var ah=f6.HE(eS.G,eS.H,eS.cj,eS.dW,eS.fr,eS.J);if(typeof ah==f6.L.dk||ah){if(eS.G==f6.aY.jC||eS.G==f6.aY.jz){var XC=eS.cj!=null?eS.cj:eS.dW;if(typeof AG!=f6.L.K&&AG!=null){AG.yi(eS.G,eS.H,XC)}}f6.Re(eS.G,eS.dZ);f6.mn(f6.cV.Qc,{G:eS.G,H:eS.H,cj:eS.cj,dW:eS.dW,fr:eS.fr,J:eS.J,dZ:eS.dZ})}else{f6.mn(f6.cV.zl,{G:eS.G,H:eS.H})}}else if(aI.data.et==f6.cV.Ub){var eS=aI.data.bE;if(f6.FX(eS.G,eS.H)){if(eS.G==f6.aY.jC||eS.G==f6.aY.jz){if(typeof AG!=f6.L.K&&AG!=null){AG.wY(eS.G,eS.H)}}f6.mn(f6.cV.Qh,{G:eS.G,H:eS.H})}else{f6.mn(f6.cV.zT,{G:eS.G,H:eS.H})}}else if(aI.data.et==f6.cV.QW){var dZ=aI.data.bE;f6.Re(dZ.G,dZ.dZ)}},false);f6o.hA={jH:null,aOj:function(jH){this.jH=jH},aDp:[],bx:function(G,H){return G+":::"+H},xi:function(kt){var G=kt.G,H=kt.H;if(f6.fK==f6.cs.eB){this.jH[f6.oS(G)].xi(G,H)}else{var ap=this.bx(G,H);this.aDp[ap]={G:G,H:H}}},yp:function(kt){var G=kt.G,H=kt.H;this.jH[f6.oS(G)].yp(G,H)},ut:function(aA){f6.mn(f6.cV.ajj,aA)},vf:function(tW){var G=tW.G,H=tW.H;this.jH[f6.oS(G)].vf(G,H).then(function(bn){f6.mn(f6.cV.Pb,{G:G,H:H,aV:bn.aV,bn:bn.bn})}).catch(function(){})},abh:function(uY){this.jH[f6.oS(uY.G)].abh(uY).then(function(){}).catch(function(){})},SM:function(tW){var G=tW.G,H=tW.H;this.jH[f6.oS(G)].SM(G,H).then(function(aw){f6.mn(f6.cV.aiJ,{G:G,H:H,aw:aw})}).catch(function(){})},zo:function(df){this.jH[f6.oS(df.G)].zo(df).then(function(QS){}).catch(function(){})},Ey:function(df){this.jH[f6.oS(df.G)].Ey(df).then(function(QS){}).catch(function(){})},DP:function(df){this.jH[f6.oS(df.G)].DP(df).then(function(QS){}).catch(function(){})},CX:function(df){this.jH[f6.oS(df.G)].CX(df).then(function(QS){}).catch(function(){})},wF:function(df){this.jH[f6.oS(df.G)].wF(df).then(function(QS){}).catch(function(){})},Eu:function(kt){var G=kt.G,H=kt.H;this.jH[f6.oS(G)].Eu(G,H)},zM:function(kt){var G=kt.G,H=kt.H;this.jH[f6.oS(G)].zM(G,H)},VT:function(aA){f6.mn(f6.cV.ajt,aA)},Dn:function(tW){var G=tW.G,H=tW.H,wf=tW.wf;this.jH[f6.oS(G)].Dn(G,H,wf).then(function(aP){f6.mn(f6.cV.aiw,{G:wf,H:H,aP:aP})}).catch(function(){})}};f6o.jH=[];f6o.jH[f6.oR.aT]={
 iJ:null,
 aaq:function(iJ){this.iJ=iJ},
 hA:null,
 agC:function(hA){this.hA=hA},
 aAW:[],
 bx:function(G,H,gn){return G+":::"+H+":::"+gn},
 dU:{qE:"HEARTBEAT",wI:"MARKET_ORDER",sd:"LIMIT_ORDER",Gj:"STOP_ORDER",Fs:"TAKE_PROFIT_ORDER",FO:"STOP_LOSS_ORDER",QT:"ORDER_TRIGGERED",CP:"ORDER_FILL",nv:"ORDER_CANCEL",aaI:"DAILY_FINANCING",oJ:"MARGIN_NOT_ENOUGH_REJECTED",rM:"MARKET_REJECTED",sz:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",qf:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",Ah:"TRANSFER_FUNDS",RC:"SYNC_BALANCE",ra:"ACCOUNT_CREATED",tc:"ACCOUNT_REMOVED",PE:"ACCOUNT_BOUND",aTU:"100014",aUc:"100015",Rg:"100016",TX:"100017",qM:"ORDERBOOK",avM:"DAILY_FINANCING_DONE",uh:"x"},
 nD:{aKF:"CLIENT_ORDER",wI:"MARKET_ORDER",Qe:"MARKET_ORDER_TRADE_CLOSE",sd:"LIMIT_ORDER",Gj:"STOP_ORDER",Fs:"TAKE_PROFIT_ORDER",FO:"STOP_LOSS_ORDER",QT:"ORDER_TRIGGERED",aAc:"CLOSEOUT",aOb:"SHOP_ORDER",abL:"DASHBOARD_ORDER",aTR:"CRYPTO_ORDER",abe:"CLIENT_REQUEST",cZ:"EXPIRATION"},
 hz:{lb:"PENDING",wW:"FILLED",wQ:"TRIGGERED",su:"CANCELLED",wE:"REPLACED",oJ:"MARGIN_NOT_ENOUGH_REJECTED",rM:"MARKET_REJECTED",sz:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",qf:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",sv:"ALL"},
 mQ:{eP:"OPEN",qi:"CLOSED",wb:"CLOSE_WHEN_TRADEABLE",wC:"TRANSFERRED",sv:"ALL"},
 SC:{sv:"ALL"},
 aQN:{dN:"B",fk:"S"},
 iE:{Dp:"MARKET",uU:"LIMIT",zX:"STOP",cB:"TAKE_PROFIT",cz:"STOP_LOSS"},
 ata:{atA: -1},
 aQu:500,
 aCN:500,
 adR:function(V){if(typeof V.state==f6.L.C){if(V.state==this.hz.lb){return f6.ek.lb}else if(V.state==this.hz.wW&&typeof V.tradeOpenedID!=f6.L.K){return f6.ek.OX}else if(V.state==this.hz.wW&&typeof V.tradeClosedIDs!=f6.L.K){return f6.ek.PN}else if(V.state==this.hz.wQ){return f6.ek.wQ}else if(V.state==this.hz.su){return f6.ek.su}else if(V.state==this.hz.wE){return f6.ek.wE}else if(V.state==this.hz.oJ){return f6.ek.oJ}else if(V.state==this.hz.rM){return f6.ek.rM}else if(V.state==this.hz.sz){return f6.ek.sz}else if(V.state==this.hz.qf){return f6.ek.qf}else{return V.state+""}}else{return null}},
 OE:function(V){if(typeof V.state==f6.L.C){if(V.state==this.mQ.eP){return f6.jJ.eP}else if(V.state==this.mQ.qi){return f6.jJ.qi}else if(V.state==this.mQ.wb){return f6.jJ.wb}else if(V.state==this.mQ.wC){return f6.jJ.wC}else{return V.state+""}}else{return null}},
 aIF:function(iZ){if(iZ==f6.ek.lb){return this.hz.lb}else if(iZ==f6.ek.wW){return this.hz.wW}else if(iZ==f6.ek.wQ){return this.hz.wQ}else if(iZ==f6.ek.su){return this.hz.su}else if(iZ==f6.ek.wE){return this.hz.wE}else if(iZ==f6.ek.oJ){return this.hz.oJ}else if(iZ==f6.ek.rM){return this.hz.rM}else if(iZ==f6.ek.sz){return this.hz.sz}else if(iZ==f6.ek.qf){return this.hz.qf}else{return this.hz.sv}},
 aKt:function(iZ){if(iZ==f6.jJ.eP){return this.mQ.eP}else if(iZ==f6.jJ.qi){return this.mQ.qi}else if(iZ==f6.jJ.wb){return this.mQ.wb}else if(iZ==f6.jJ.wC){return this.mQ.wC}else{return this.mQ.sv}},

 aal:function(G,V){
  var cb=this.adR(V);var db=0.0;var cD=0.0;if(typeof V.takeProfitOnFill!=f6.L.K&&V.takeProfitOnFill!=null){db=f6.bI(V.takeProfitOnFill.price)?parseFloat(V.takeProfitOnFill.price):0.0}if(typeof V.stopLossOnFill!=f6.L.K&&V.stopLossOnFill!=null){cD=f6.bI(V.stopLossOnFill.price)?parseFloat(V.stopLossOnFill.price):0.0}var ce=f6.na(G);if(cb==f6.ek.lb){return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:null,vd:null,sx:null,bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?(parseFloat(V.units)/ce):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:null,bu:f6.bI(V.price)?parseFloat(V.price):null,rD:null,db:db,cD:cD,cJ:typeof V.comment==f6.L.C?V.comment:null,dn:f6.by(V.magicNumber)?parseInt(V.magicNumber, 10):null,cZ:f6.by(V.expiration)?parseInt(V.expiration, 10):null}}else if(cb==f6.ek.OX){return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:typeof V.fillingTransactionID==f6.L.C?V.fillingTransactionID:null,vd:f6.bI(V.filledTime)?parseFloat(V.filledTime):null,sx:null,bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?(parseFloat(V.units)/ce):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:typeof V.Ur==f6.L.C?V.Ur:null,rD:f6.bI(V.donePrice)?parseFloat(V.donePrice):null,cJ:typeof V.comment==f6.L.C?V.comment:null,dn:f6.by(V.magicNumber)?parseInt(V.magicNumber, 10):null,cZ:f6.by(V.expiration)?parseInt(V.expiration, 10):null}}else if(cb==f6.ek.PN){return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:typeof V.fillingTransactionID==f6.L.C?V.fillingTransactionID:null,vd:f6.bI(V.filledTime)?parseFloat(V.filledTime):null,sx:f6.cQ(V.tradeClosedIDs)?V.tradeClosedIDs:[],bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?(parseFloat(V.units)/ce):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:null,rD:f6.bI(V.donePrice)?parseFloat(V.donePrice):null}}else if(cb==f6.ek.su||cb==f6.ek.oJ){var ji=null;if(typeof V.reason==f6.L.C){if(V.reason==this.nD.abe){ji=f6.dh.nv}else if(V.reason==this.nD.cZ){ji=f6.dh.cZ}}if(cb==f6.ek.oJ){ji=f6.dh.rA}return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:typeof V.cancellingTransactionID==f6.L.C?V.cancellingTransactionID:null,vd:f6.bI(V.cancelledTime)?parseFloat(V.cancelledTime):null,sx:f6.cQ(V.tradeClosedIDs)?V.tradeClosedIDs:[],bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?(parseFloat(V.units)/ce):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:null,bu:f6.bI(V.price)?parseFloat(V.price):null,rD:f6.bI(V.donePrice)?parseFloat(V.donePrice):null,db:db,cD:cD,ji:ji,cJ:typeof V.comment==f6.L.C?V.comment:null,dn:f6.by(V.magicNumber)?parseInt(V.magicNumber, 10):null,cZ:f6.by(V.expiration)?parseInt(V.expiration, 10):null}}
 },

 YN:function(G,V){
  var db=0.0;var cD=0.0;if(typeof V.takeProfit!=f6.L.K&&V.takeProfit!=null){db=f6.bI(V.takeProfit.price)?parseFloat(V.takeProfit.price):0.0}if(typeof V.stopLoss!=f6.L.K&&V.stopLoss!=null){cD=f6.bI(V.stopLoss.price)?parseFloat(V.stopLoss.price):0.0}var ce=f6.na(G);return{T:typeof V.id==f6.L.C?V.id:null,cb:this.OE(V),bJ:typeof V.instrument==f6.L.C?V.instrument:null,eC:f6.bI(V.openTime)?parseFloat(V.openTime):null,bu:f6.bI(V.price)?parseFloat(V.price):null,io:f6.bI(V.currentUnits)?(parseFloat(V.currentUnits)/ce):null,iv:f6.bI(V.initialUnits)?(parseFloat(V.initialUnits)/ce):null,cW:f6.bI(V.financing)?parseFloat(V.financing):null,fZ:f6.bI(V.realizedPL)?parseFloat(V.realizedPL):null,gw:0.0,ck:f6.bI(V.commission)?parseFloat(V.commission):null,sx:f6.cQ(V.tradeClosedIDs)?V.tradeClosedIDs:[],db:db,cD:cD,cJ:typeof V.comment==f6.L.C?V.comment:null,dn:f6.by(V.magicNumber)?parseInt(V.magicNumber, 10):null}
 },

 aJH:function(V){return{H:typeof V.accountID==f6.L.C?V.accountID:null,T:typeof V.id==f6.L.C?V.id:null,vn:typeof V.clOrderID==f6.L.C?V.clOrderID:null,cb:this.OE(V),bV:f6.bI(V.openTime)?parseFloat(V.openTime):null,ob:f6.bI(V.initialUnits)?parseFloat(V.initialUnits):null,ck:f6.bI(V.commission)?parseFloat(V.commission):null,cJ:typeof V.comment==f6.L.C?V.comment:null,Dz:typeof V.tradeClosedIds==f6.L.C?V.tradeClosedIds:null}},
 acG:function(G,V){return{H:typeof V.accountId==f6.L.C?V.accountId:null,bJ:typeof V.instrument==f6.L.C?V.instrument:null,zN:f6.bI(V.averagePrice)?parseFloat(V.averagePrice):null,ck:f6.bI(V.commission)?parseFloat(V.commission):null,bO:f6.bI(V.units)?(parseFloat(V.units)/f6.na(G)):null,fc:f6.bI(V.pl)?parseFloat(V.pl):null,ET:f6.bI(V.resettablePL)?parseFloat(V.resettablePL):null,gw:f6.bI(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,cW:f6.bI(V.financing)?parseFloat(V.financing):null}},
 aGN:function(V){return{Ed:typeof V.lN==f6.L.C?V.lN:null,Cs:f6.by(V.sendingTime)?parseInt(V.sendingTime, 10):null,KG:typeof V.cOID==f6.L.C?V.cOID:null,Sd:typeof V.orderID==f6.L.C?V.orderID:null,Oo:typeof V.eID==f6.L.C?V.eID:null,an:typeof V.symbol==f6.L.C?V.symbol:null,IA:typeof V.side==f6.L.C?V.side:null,Ln:f6.bI(V.px)?parseFloat(V.px):null,KP:f6.bI(V.qty)?parseFloat(V.qty):null,iA:typeof V.a==f6.L.fI?V.a:null,G:typeof V.brokerName==f6.L.C?V.brokerName:null}},
 adn:function(V){return{G:typeof V.brokerName==f6.L.C?V.brokerName:null,hc:typeof V.brokerDesc==f6.L.C?V.brokerDesc:null,aV:typeof V.currency==f6.L.C?V.currency:null,bG:f6.bI(V.toFixed)?parseFloat(V.toFixed):null}},
 MO:function(G,V){return{fg:f6.bI(V.nav)?parseFloat(V.nav):null,aCy:typeof V.alias==f6.L.C?V.alias:null,eJ:f6.bI(V.balance)?parseFloat(V.balance):null,ck:f6.bI(V.commission)?parseFloat(V.commission):null,aBg:f6.by(V.createdByUserID)?parseInt(V.createdByUserID, 10):null,aCo:f6.bI(V.createdTime)?parseFloat(V.createdTime):null,aV:typeof V.currency==f6.L.C?V.currency:f6.IC(G),rk:typeof V.hedgingEnabled==f6.L.fI?V.hedgingEnabled:null,T:typeof V.id==f6.L.C?V.id:null,gn:typeof V.lastTransactionID==f6.L.C?V.lastTransactionID:null,jm:f6.bI(V.marginAvailable)?parseFloat(V.marginAvailable):null,aET:f6.bI(V.marginCallMarginUsed)?parseFloat(V.marginCallMarginUsed):null,aGv:f6.bI(V.marginCallPercent)?parseFloat(V.marginCallPercent):null,aFl:f6.bI(V.marginCloseoutMarginUsed)?parseFloat(V.marginCloseoutMarginUsed):null,aFx:f6.bI(V.marginCloseoutNAV)?parseFloat(V.marginCloseoutNAV):null,aFV:f6.bI(V.marginCloseoutPercent)?parseFloat(V.marginCloseoutPercent):null,aGG:f6.bI(V.marginCloseoutPositionValue)?parseFloat(V.marginCloseoutPositionValue):null,aFY:f6.bI(V.marginCloseoutUnrealizedPL)?parseFloat(V.marginCloseoutUnrealizedPL):null,aFM:f6.bI(V.marginRate)?parseFloat(V.marginRate):null,hh:f6.bI(V.marginUsed)?parseFloat(V.marginUsed):null,aFj:(f6.by(V.openPositionCount)&&typeof V.openPositionCount!=f6.L.C)?V.openPositionCount:null,aGC:(f6.by(V.openTradeCount)&&typeof V.openTradeCount!=f6.L.C)?V.openTradeCount:null,aRh:(f6.by(V.pendingOrderCount)&&typeof V.pendingOrderCount!=f6.L.C)?V.pendingOrderCount:null,fc:f6.bI(V.pl)?parseFloat(V.pl):null,aPH:f6.bI(V.positionValue)?parseFloat(V.positionValue):null,ET:f6.bI(V.resettablePL)?parseFloat(V.resettablePL):null,gw:f6.bI(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,avZ:f6.bI(V.withdrawalLimit)?parseFloat(V.withdrawalLimit):null,bG:f6.bI(V.toFixed)?parseFloat(V.toFixed):f6.uD(G),mO:f6.bI(V.marginCallLevel)?parseFloat(V.marginCallLevel):null,ri:f6.bI(V.marginCloseoutLevel)?parseFloat(V.marginCloseoutLevel):null,H:typeof V.accountId==f6.L.C?V.accountId:null,ik:typeof V.email==f6.L.C?V.email:null,fp:typeof V.bWatchable==f6.L.fI?V.bWatchable:null,fd:typeof V.bOneClickAccepted==f6.L.fI?V.bOneClickAccepted:null,eQ:typeof V.bMfaEnabled==f6.L.fI?V.bMfaEnabled:null,nF:typeof V.identifier==f6.L.C?V.identifier:null,iA:typeof V.bt==f6.L.fI?V.bt:null,gY:f6.by(V.level)?parseInt(V.level, 10):null,lJ:f6.bI(V.buyOpnCmmssn)?parseFloat(V.buyOpnCmmssn):null,mJ:f6.bI(V.buyClsdCmmssn)?parseFloat(V.buyClsdCmmssn):null,mT:f6.bI(V.sellOpnCmmssn)?parseFloat(V.sellOpnCmmssn):null,mj:f6.bI(V.sellClsdCmmssn)?parseFloat(V.sellClsdCmmssn):null,cL:f6.bI(V.bid)?parseFloat(V.bid):null,dR:f6.bI(V.ask)?parseFloat(V.ask):null,mw:f6.bI(V.latestUpdatedDate)?parseFloat(V.latestUpdatedDate):null}},
 qI:function(G,V){var db=0.0;var cD=0.0;if(typeof V.takeProfitOnFill!=f6.L.K&&V.takeProfitOnFill!=null){db=f6.bI(V.takeProfitOnFill.price)?parseFloat(V.takeProfitOnFill.price):0.0}if(typeof V.stopLossOnFill!=f6.L.K&&V.stopLossOnFill!=null){cD=f6.bI(V.stopLossOnFill.price)?parseFloat(V.stopLossOnFill.price):0.0}return{uW:f6.bI(V.accountBalance)?parseFloat(V.accountBalance):null,H:typeof V.accountID==f6.L.C?V.accountID:null,aKH:typeof V.batchID==f6.L.C?V.batchID:null,ck:f6.bI(V.commission)?parseFloat(V.commission):null,cW:f6.bI(V.financing)?parseFloat(V.financing):null,aHV:null,T:typeof V.id==f6.L.C?V.id:null,hZ:f6.by(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,bJ:typeof V.instrument==f6.L.C?V.instrument:null,cG:typeof V.orderID==f6.L.C?V.orderID:null,fc:f6.bI(V.pl)?parseFloat(V.pl):null,bu:f6.bI(V.price)?parseFloat(V.price):null,ji:typeof V.reason==f6.L.C?V.reason:null,Gl:typeof V.requestID==f6.L.C?V.requestID:null,bV:f6.bI(V.time)?parseFloat(V.time):null,ct:typeof V.type==f6.L.C?V.type:null,nS:f6.bI(V.units)?parseFloat(V.units):null,bO:f6.bI(V.units)?(parseFloat(V.units)/f6.na(G)):null,IV:f6.by(V.userID)?parseInt(V.userID, 10):null,db:db,cD:cD,vn:typeof V.clOrderID==f6.L.C?V.clOrderID:null,cJ:typeof V.comment==f6.L.C?V.comment:null,dn:f6.by(V.magicNumber)?parseInt(V.magicNumber, 10):null,fL:f6.by(V.slippage)?parseInt(V.slippage, 10):null,cZ:f6.by(V.expiration)?parseInt(V.expiration, 10):null,G:typeof V.brokerName==f6.L.C?V.brokerName:null}},

 vD:function(V){
  var mP={gd:typeof V.id==f6.L.C?V.id:null,hZ:f6.by(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,G:typeof V.brokerName==f6.L.C?V.brokerName:null,H:typeof V.accountID==f6.L.C?V.accountID:null,bV:f6.bI(V.time)?parseFloat(V.time):null};if(mP.gd==null||mP.bV==null){throw new Error(f6.R.mY)}var gd=f6.by(mP.gd)?parseInt(mP.gd, 10):null;gd=(gd!=null&&gd==this.ata.atA)?null:gd;return{gd:gd,hZ:mP.hZ,G:mP.G,H:mP.H,bV:mP.bV}
 },

 Mz:function(qM,ce){var asI=[];if(f6.cQ(qM)){for(var i in qM){var Ge=qM[i];var bu=null;var bO=null;var Bm=null;var Rq=null;bu=f6.bI(Ge.price)?parseFloat(Ge.price):null;bO=f6.bI(Ge.units)?(parseFloat(Ge.units)/ce):null;Bm=typeof Ge.type==f6.L.C?Ge.type:null;if(Bm!=f6.asX.uU&&Bm!=f6.asX.zX){Bm=null}Rq=bO>0?f6.ab.dN:f6.ab.fk;bO=Math.abs(bO);if(bu!=null&&bO!=null&&Bm!=null&&Rq!=null){asI.push({Bm:Bm,Rq:Rq,bu:bu,bO:bO})}}}return asI},

 aoY:function(G,V){
  var mP={
   gd:typeof V.id==f6.L.C?V.id:null,
   hZ:f6.by(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,
   G:typeof V.brokerName==f6.L.C?V.brokerName:null,
   bV:f6.bI(V.time)?parseFloat(V.time):null,
   bs:typeof V.instrument==f6.L.C?V.instrument:null
  };var ce=f6.na(G);var EI=this.Mz(V.orderBookBuyLimit,ce);var Ct=this.Mz(V.orderBookSellLimit,ce);var Dq=this.Mz(V.orderBookBuyStop,ce);var BH=this.Mz(V.orderBookSellStop,ce);if(mP.gd==null||mP.G==null||mP.bV==null||mP.bs==null){throw new Error(f6.R.mY)}var un=null;if(EI.length>0){EI.sort(function(a,b){return a.bu-b.bu});un=0;for(var i=EI.length-1;i>=0;i -= 1){EI[i].bO+=un;un=EI[i].bO}}if(Ct.length>0){Ct.sort(function(a,b){return a.bu-b.bu});un=0;for(var i=Ct.length-1;i>=0;i -= 1){Ct[i].bO+=un;un=Ct[i].bO}}if(Dq.length>0){Dq.sort(function(a,b){return a.bu-b.bu});un=0;for(var i=Dq.length-1;i>=0;i -= 1){Dq[i].bO+=un;un=Dq[i].bO}}if(BH.length>0){BH.sort(function(a,b){return a.bu-b.bu});un=0;for(var i=BH.length-1;i>=0;i -= 1){BH[i].bO+=un;un=BH[i].bO}}var gd=f6.by(mP.gd)?parseInt(mP.gd, 10):null;gd=(gd!=null&&gd==this.ata.atA)?null:gd;return{gd:gd,hZ:mP.hZ,G:mP.G,bV:mP.bV,bs:mP.bs,EI:EI,Ct:Ct,Dq:Dq,BH:BH}
 },

 abB:function(V){var mo={G:typeof V.brokerName==f6.L.C?V.brokerName:null,H:typeof V.accountID==f6.L.C?V.accountID:null,T:typeof V.id==f6.L.C?V.id:null,hZ:f6.by(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,cG:typeof V.orderID==f6.L.C?V.orderID:null,bV:f6.bI(V.time)?parseFloat(V.time):null};if(mo.T==null||mo.G==null||mo.H==null||mo.cG==null||mo.bV==null){throw new Error(f6.R.mY)}return{gd:f6.by(mo.T)?parseInt(mo.T, 10):null,hZ:mo.hZ,T:mo.cG,bV:mo.bV,hM:mo.T==mo.cG,G:mo.G,H:mo.H}},
 aqw:function(G,V){var bF=this.qI(G,V);if(bF.G==null||bF.H==null||bF.T==null||bF.cG==null||bF.bJ==null||bF.bV==null||bF.bu==null||bF.bO==null){throw new Error(f6.R.mY)}return{gd:f6.by(bF.T)?parseInt(bF.T, 10):null,hZ:bF.hZ,T:bF.cG,bJ:bF.bJ,aj:bF.bO>0?(bF.ct==this.dU.sd?f6.ab.gs:f6.ab.gP):(bF.ct==this.dU.sd?f6.ab.ir:f6.ab.iq),bV:bF.bV,bu:bF.bu,bO:Math.abs(bF.bO),db:bF.db,cD:bF.cD,hM:bF.T==bF.cG,G:bF.G,H:bF.H,cJ:bF.cJ,dn:bF.dn,cZ:bF.cZ}},
 aKc:function(G,V){var pp=this.qI(G,V);if(pp.G==null||pp.H==null||pp.T==null||pp.cG==null||pp.bV==null||pp.bu==null||pp.ji==null){throw new Error(f6.R.mY)}return{gd:f6.by(pp.T)?parseInt(pp.T, 10):null,hZ:pp.hZ,T:pp.cG,xq:pp.bV,rD:pp.bu,ji:pp.ji==this.nD.abe?f6.dh.nv:(pp.ji==this.dU.cZ?f6.dh.cZ:null),hM:false,G:pp.G,H:pp.H}},
 aJb:function(G,V){var ha=this.qI(G,V);if(ha.G==null||ha.H==null||ha.T==null||ha.cG==null||ha.bJ==null||ha.bV==null||ha.bu==null||ha.bO==null){throw new Error(f6.R.mY)}return{gd:f6.by(ha.T)?parseInt(ha.T, 10):null,hZ:ha.hZ,T:ha.cG,bJ:ha.bJ,aj:ha.bO>0?(ha.ct==this.dU.wI?f6.ab.dN:(ha.ct==this.dU.sd?f6.ab.gs:f6.ab.gP)):(ha.ct==this.dU.wI?f6.ab.fk:(ha.ct==this.dU.sd?f6.ab.ir:f6.ab.iq)),xq:ha.bV,bu:ha.bu,rD:ha.bu,bO:Math.abs(ha.bO),db:ha.db,cD:ha.cD,ji:f6.dh.rA,hM:ha.T==ha.cG,G:ha.G,H:ha.H}},
 ara:function(G,V){var oW=this.qI(G,V);oW.amR=null;oW.fz=null;if(f6.cQ(V.tradesClosed)&&V.tradesClosed.length>0){if(typeof V.tradesClosed[0].tradeID==f6.L.C){oW.fz=V.tradesClosed[0].tradeID}}if(oW.G==null||oW.H==null||oW.T==null||oW.fz==null||oW.bV==null){throw new Error(f6.R.mY)}return{gd:f6.by(oW.T)?parseInt(oW.T, 10):null,hZ:oW.hZ,T:oW.fz,bV:oW.bV,db:oW.db,cD:oW.cD,hM:false,G:oW.G,H:oW.H}},
 Uf:function(G,V){var dv=this.qI(G,V);dv.aBM=null;if(dv.G==null||dv.H==null||dv.T==null||dv.bJ==null||dv.bV==null||dv.bu==null||dv.bO==null||dv.fc==null||dv.ck==null||dv.cG==null){throw new Error(f6.R.mY)}return{gd:f6.by(dv.T)?parseInt(dv.T, 10):null,hZ:dv.hZ,T:dv.T,bJ:dv.bJ,aj:dv.bO>0?f6.ab.dN:f6.ab.fk,eC:dv.bV,dX:dv.bu,io:Math.abs(dv.bO),db:dv.db,cD:dv.cD,cW:0.0,ck:dv.ck,gw:0.0,cG:dv.cG,hM:true,G:dv.G,H:dv.H,cJ:dv.cJ,dn:dv.dn}},
 Sa:function(G,V){var dv=this.qI(G,V);dv.amR=null;dv.fz=null;if(f6.cQ(V.tradesClosed)&&V.tradesClosed.length>0){if(typeof V.tradesClosed[0].tradeID==f6.L.C){dv.fz=V.tradesClosed[0].tradeID}}if(dv.G==null||dv.H==null||dv.T==null||dv.bJ==null||dv.bV==null||dv.bu==null||dv.bO==null||dv.fc==null||dv.fz==null||dv.ck==null||dv.cW==null){throw new Error(f6.R.mY)}return{gd:f6.by(dv.T)?parseInt(dv.T, 10):null,hZ:dv.hZ,T:dv.fz,bJ:dv.bJ,aj:dv.bO<0?f6.ab.dN:f6.ab.fk,eC:null,dX:null,jT:dv.bV,ke:dv.bu,iv:Math.abs(dv.bO),cW:dv.cW,fZ:dv.fc,ck:dv.ck,apD:dv.T,hM:true,G:dv.G,H:dv.H,cJ:dv.cJ,dn:dv.dn}},
 Pk:function(V){var og={G:typeof V.brokerName==f6.L.C?V.brokerName:null,H:typeof V.accountID==f6.L.C?V.accountID:null,T:typeof V.id==f6.L.C?V.id:null,hZ:f6.by(V.syncTransStep)?parseInt(V.syncTransStep, 10):0,bV:f6.bI(V.time)?parseFloat(V.time):null};if(og.G==null||og.H==null||og.T==null||og.bV==null){throw new Error(f6.R.mY)}return{gd:f6.by(og.T)?parseInt(og.T, 10):null,hZ:og.hZ,T:og.T,bV:og.bV,hM:true,G:og.G,H:og.H}},
 apz:function(G,V){var nR=this.qI(G,V);if(nR.G==null||nR.H==null||nR.T==null||nR.bV==null||nR.nS==null||nR.ck==null){throw new Error(f6.R.mY)}return{gd:f6.by(nR.T)?parseInt(nR.T, 10):null,hZ:nR.hZ,G:nR.G,H:nR.H,T:nR.T,vn:nR.vn,bV:nR.bV,ob:nR.nS,ck:nR.ck,hM:true,cJ:nR.cJ,Dz:nR.Gl}},
 Zn:function(G,H,V){var aA=null;var cT=null;try{if(typeof V.type!=f6.L.K&&V.type){if(V.type==this.dU.qE){aA=this.vD(V);aA.H=H;cT=f6.dh.qE}else if(V.type==this.dU.wI){aA=this.abB(V);cT=f6.dh.vs}else if(V.type==this.dU.QT){aA=this.vD(V);cT=f6.dh.vs}else if(V.type==this.dU.sd){aA=this.aqw(G,V);cT=f6.dh.bF}else if(V.type==this.dU.Gj){aA=this.aqw(G,V);cT=f6.dh.bF}else if(V.type==this.dU.Fs){aA=this.ara(G,V);cT=f6.dh.bc}else if(V.type==this.dU.FO){aA=this.ara(G,V);cT=f6.dh.bc}else if(V.type==this.dU.nv){aA=this.aKc(G,V);cT=f6.dh.nv}else if(V.type==this.dU.oJ){aA=this.aJb(G,V);cT=f6.dh.rA}else if(V.type==this.dU.rM){aA=this.vD(V);cT=f6.dh.vs;throw new Error(f6.R.anN+"("+f6.ev(G)+", "+H+")")}else if(V.type==this.dU.CP&&typeof V.reason!=f6.L.K&&(V.reason==this.nD.wI||V.reason==this.nD.sd||V.reason==this.nD.Gj)){aA=this.Uf(G,V);cT=f6.dh.bc}else if(V.type==this.dU.CP&&typeof V.reason!=f6.L.K&&(V.reason==this.nD.Qe||V.reason==this.nD.Fs||V.reason==this.nD.FO)){aA=this.Sa(G,V);cT=f6.dh.cN}else if(V.type==this.dU.aaI){aA=this.Pk(V);cT=f6.dh.cW}else if(V.type==this.dU.qf){aA=this.vD(V);cT=f6.dh.vs;throw new Error(f6.R.apn+"("+f6.ev(G)+", "+H+")")}else if(V.type==this.dU.sz){aA=this.vD(V);cT=f6.dh.vs;throw new Error(f6.R.amz+"("+f6.ev(G)+", "+H+")")}else if(V.type==this.dU.Ah){aA=this.apz(G,V);cT=f6.dh.Ah}else if(V.type==this.dU.RC){aA=this.vD(V);cT=f6.dh.vs}else if(V.type==this.dU.tc){aA=this.vD(V);cT=f6.dh.vs;throw new Error(f6.R.avY+"("+f6.ev(G)+", "+H+")")}else if(V.type==this.dU.qM){aA=this.aoY(G,V);cT=f6.dh.qM}else if(V.type==this.dU.uh){aA={};cT=f6.dh.uh}else{aA=this.vD(V);cT=f6.dh.vs}}}catch(e){f6.az(JSON.stringify(V)+" "+e.message);f6.gE(e.message)}if(aA!=null){this.hA.ut({G:G,H:H,cT:cT,aA:aA})}},
 xi:function(G,H){var aB=this;this.iJ.vH.uT(G,H,{},function(V){aB.Zn(G,H,V)})},
 abh:function(uY){var G=uY.G,H=uY.H,Fp=uY.Fp;var aB=this;return new Promise(function(cC,aW){aB.iJ.vH.ail(G,H,{id:Fp+""}).then(function(aM){if(f6.cQ(aM.transactions)){for(var i in aM.transactions){aB.Zn(G,H,aM.transactions[i])}cC()}else{f6.az(f6.R.NM);f6.gE(f6.R.NM);aW()}}).catch(function(){aW()})})},
 yp:function(G,H){this.iJ.vH.ur(G,H)},

 zo:function(df){
  var G=df.G,H=df.H,bJ=df.bJ,nS=null,ct=null,bu=df.bu,fL=df.fL,bL=df.bL,cB=df.cB,cz=df.cz,cJ=df.cJ,dn=df.dn,cZ=df.cZ;var ce=f6.na(G);if(df.aj==f6.ab.dN){ct=this.iE.Dp;nS=bL*ce}else if(df.aj==f6.ab.fk){ct=this.iE.Dp;nS= -(bL*ce)}else if(df.aj==f6.ab.gs){ct=this.iE.uU;nS=bL*ce}else if(df.aj==f6.ab.ir){ct=this.iE.uU;nS= -(bL*ce)}else if(df.aj==f6.ab.gP){ct=this.iE.zX;nS=bL*ce}else if(df.aj==f6.ab.iq){ct=this.iE.zX;nS= -(bL*ce)}var aB=this;return new Promise(function(cC,aW){
   var It=null;var GL=null;if(cB>0.0){It={price:cB}}if(cz>0.0){GL={price:cz}}var JM={instrument:bJ,units:nS,clientExtensions:{id:"",tag:"",comment:cJ,magicNumber:dn,slippage:fL,expiration:cZ},price:bu,type:ct,takeProfitOnFill:It,stopLossOnFill:GL};aB.iJ.wT.aqa(G,H,JM).then(function(aM){if(typeof aM.id!=f6.L.K){cC(aM.id+"")}else{f6.az(f6.R.atC);f6.gE(f6.R.atC);aW()}}).catch(function(){aW()});
  });
 },

 Ey:function(df){
  var G=df.G,H=df.H,cG=df.cG,bJ=df.bJ,nS=null,ct=null,bu=df.bu,fL=df.fL,bL=df.bL,cB=df.cB,cz=df.cz,cJ=df.cJ,dn=df.dn,cZ=df.cZ;var ce=f6.na(G);if(df.aj==f6.ab.dN){ct=this.iE.Dp;nS=bL*ce}else if(df.aj==f6.ab.fk){ct=this.iE.Dp;nS= -(bL*ce)}else if(df.aj==f6.ab.gs){ct=this.iE.uU;nS=bL*ce}else if(df.aj==f6.ab.ir){ct=this.iE.uU;nS= -(bL*ce)}else if(df.aj==f6.ab.gP){ct=this.iE.zX;nS=bL*ce}else if(df.aj==f6.ab.iq){ct=this.iE.zX;nS= -(bL*ce)}var aB=this;return new Promise(function(cC,aW){
   var It=null;var GL=null;if(cB>0.0){It={price:cB}}if(cz>0.0){GL={price:cz}}var JM={instrument:bJ,units:nS,clientExtensions:{id:"",tag:"",comment:cJ,magicNumber:dn,slippage:fL,expiration:cZ},price:bu,type:ct,takeProfitOnFill:It,stopLossOnFill:GL};aB.iJ.wT.Bk(G,H,cG,JM).then(function(aM){if(typeof aM.id!=f6.L.K){cC(aM.id+"")}else{f6.az(f6.R.aup);f6.gE(f6.R.aup);aW()}}).catch(function(){aW()});
  });
 },

 DP:function(df){var G=df.G,H=df.H,cG=df.cG;var aB=this;return new Promise(function(cC,aW){aB.iJ.wT.aGS(G,H,cG).then(function(aM){if(typeof aM.id!=f6.L.K){cC(aM.id+"")}else{f6.az(f6.R.atM);f6.gE(f6.R.atM);aW()}}).catch(function(){aW()})})},

 CX:function(df){var G=df.G,H=df.H,fz=df.fz,cB=df.cB,cz=df.cz,Sl=this.SC.sv;var aB=this;return new Promise(function(cC,aW){
  var avc=null;var akl=null;if(cB>0.0){avc={price:cB}}if(cz>0.0){akl={price:cz}}var JM={takeProfit:avc,stopLoss:akl};aB.iJ.vp.aEQ(G,H,fz,JM).then(function(aM){if(typeof aM.id!=f6.L.K){cC(aM.id+"")}else{f6.az(f6.R.atK);f6.gE(f6.R.atK);aW()}}).catch(function(){aW()});
 })},

 wF:function(df){var G=df.G,H=df.H,fz=df.fz,Sl=this.SC.sv,bu=df.bu,fL=df.fL;var aB=this;return new Promise(function(cC,aW){aB.iJ.vp.ep(G,H,fz,{units:Sl,price:bu,slippage:fL}).then(function(aM){if(typeof aM.id!=f6.L.K){cC(aM.id+"")}else{f6.az(f6.R.att);f6.gE(f6.R.att);aW()}}).catch(function(){aW()})})},
 Df:function(dY){var ai={H:dY.H,ik:dY.ik,eJ:dY.eJ,aV:dY.aV,bG:dY.bG,ck:dY.ck,rk:dY.rk,fc:dY.fc,mO:dY.mO,ri:dY.ri,fg:dY.fg,hh:dY.hh,Sk:parseInt(dY.gn, 10),fp:dY.fp,fd:dY.fd,eQ:dY.eQ};if(ai.fg!=null&&ai.hh!=null){ai.jm=Math.round(dY.bG*(ai.fg-ai.hh))/dY.bG}else{ai.jm=null}return ai},
 aDq:function(G,dY){var ai={G:G,H:dY.H,ik:dY.ik,eJ:dY.eJ,fc:dY.fc,fg:dY.fg,hh:dY.hh,aV:dY.aV,nF:dY.nF,iA:dY.iA,gY:dY.gY,lJ:dY.lJ,mJ:dY.mJ,mT:dY.mT,mj:dY.mj,cL:dY.cL,dR:dY.dR,bG:dY.bG,mw:dY.mw};if(ai.fg!=null&&ai.hh!=null){ai.jm=Math.round(dY.bG*(ai.fg-ai.hh))/dY.bG}else{ai.jm=null}return ai},
 Ej:function(Nb){var du=[];for(var i in Nb){var bF=Nb[i];if(bF.cb==f6.ek.lb&&bF.bO!=null&&bF.bO!=0&&bF.vo!=null&&bF.bJ!=null&&bF.mU!=null&&bF.bu!=null&&bF.ct!=null){du.push({T:bF.vo,bJ:bF.bJ,aj:bF.bO>0?(bF.ct==this.iE.uU?f6.ab.gs:f6.ab.gP):(bF.ct==this.iE.uU?f6.ab.ir:f6.ab.iq),bV:bF.mU,bu:bF.bu,bO:Math.abs(bF.bO),db:bF.db,cD:bF.cD,cJ:bF.cJ,dn:bF.dn,cZ:bF.cZ})}}du.sort(function(a,b){return a.bV-b.bV});return du},
 Ql:function(apj){var eI=[];for(var i in apj){var bk=apj[i];if(bk.cb==f6.ek.su&&bk.bO!=null&&bk.bO!=0&&bk.vo!=null&&bk.bJ!=null&&bk.mU!=null&&bk.vd!=null&&bk.bu!=null&&bk.rD!=null&&bk.ct!=null&&bk.ji!=null){eI.push({T:bk.vo,bJ:bk.bJ,aj:bk.bO>0?(bk.ct==this.iE.uU?f6.ab.gs:f6.ab.gP):(bk.ct==this.iE.uU?f6.ab.ir:f6.ab.iq),mU:bk.mU,xq:bk.vd,bu:bk.bu,bO:Math.abs(bk.bO),db:bk.db,cD:bk.cD,rD:bk.rD,ji:bk.ji,cJ:bk.cJ,dn:bk.dn,cZ:bk.cZ})}}eI.sort(function(a,b){return a.mU-b.mU});return eI},
 DI:function(nc){var ac=[];for(var i in nc){var bc=nc[i];if(bc.cb==f6.jJ.eP&&bc.iv!=null&&bc.iv!=0&&bc.T!=null&&bc.bJ!=null&&bc.eC!=null&&bc.bu!=null&&bc.io!=null&&bc.cW!=null&&bc.ck!=null){ac.push({T:bc.T,bJ:bc.bJ,aj:bc.iv>0?f6.ab.dN:f6.ab.fk,eC:bc.eC,dX:bc.bu,io:Math.abs(bc.io),db:bc.db,cD:bc.cD,cW:bc.cW,ck:bc.ck,gw:0.0,cJ:bc.cJ,dn:bc.dn})}}ac.sort(function(a,b){return a.eC-b.eC});return ac},
 Lp:function(fP){var de=[];for(var i in fP){var fN=fP[i];if(fN.cb==f6.jJ.qi&&fN.iv!=null&&fN.iv!=0){var jT=null;var ke=null;var Ei=null;var fZ=null;for(var j in fP){var Ek=fP[j];if(Ek.cb==f6.jJ.qi&&Ek.sx.length>0&&Ek.sx[0]+""===fN.T){jT=Ek.eC;ke=Ek.bu;Ei=Ek.ck;fZ=Ek.fZ;break}}if(fN.T!=null&&fN.bJ!=null&&fN.eC!=null&&fN.bu!=null&&jT!=null&&ke!=null&&Ei!=null&&fN.cW!=null&&fZ!=null&&fN.ck!=null){de.push({T:fN.T,bJ:fN.bJ,aj:fN.iv>0?f6.ab.dN:f6.ab.fk,eC:fN.eC,dX:fN.bu,jT:jT,ke:ke,iv:Math.abs(fN.iv),cW:fN.cW,fZ:fZ,ck:fN.ck+Ei,db:fN.db,cD:fN.cD,cJ:fN.cJ,dn:fN.dn})}}}de.sort(function(a,b){return a.eC-b.eC});return de},
 zL:function(vY){var ca=[];for(var i in vY){var qo=vY[i];if(qo.cb==f6.jJ.wC&&qo.H!=null&&qo.T!=null&&qo.bV!=null&&qo.ob!=null&&qo.ck!=null){ca.push({H:qo.H,T:qo.T,vn:qo.vn,bV:qo.bV,ob:qo.ob,ck:qo.ck,cJ:qo.cJ,Dz:qo.Dz})}}ca.sort(function(a,b){return a.bV-b.bV});return ca},
 NG:function(ds){var CK=[];for(var i in ds){var fj=ds[i];if(fj.H!=null&&fj.bJ!=null&&fj.zN!=null&&fj.ck!=null&&fj.bO!=null&&fj.bO!=0&&fj.gw!=null&&fj.cW!=null){CK.push({H:fj.H,bJ:fj.bJ,zN:fj.zN,ck:fj.ck,bO:Math.abs(fj.bO),fc:fj.fc,ET:fj.ET,gw:fj.gw,cW:fj.cW,ty:fj.bO>0?f6.ab.dN:f6.ab.fk})}}CK.sort(function(a,b){return b.bO-a.bO});return CK},
 NB:function(ds){var CK=[];for(var i in ds){var fj=ds[i];if(fj.bJ!=null&&fj.bO!=null&&fj.bO!=0){CK.push({bJ:fj.bJ,bO:fj.bO})}}CK.sort(function(a,b){return b.bO-a.bO});return CK},
 CY:function(Kd){var ew=[];for(var i in Kd){var lK=Kd[i];if(lK.Ed!=null&&lK.Cs!=null&&lK.KG!=null&&lK.an!=null&&lK.IA!=null&&lK.Ln!=0&&lK.KP!=null){ew.push({Ed:lK.Ed,Cs:lK.Cs,KG:lK.KG,Sd:lK.Sd,Oo:lK.Oo,an:lK.an,IA:lK.IA,Ln:lK.Ln,KP:lK.KP,iA:lK.iA,G:lK.G})}}ew.sort(function(a,b){return a.Cs-b.Cs});return ew},
 Wc:function(hg){var Jj=[];for(var i in hg){var kE=hg[i];if(kE.G!=null&&kE.hc!=null&&kE.aV!=null&&kE.bG!=null){Jj.push({G:kE.G,hc:kE.hc,aV:kE.aV,bG:kE.bG})}}return Jj},
 Ok:function(G,V){if(f6.cQ(V)){var JH=[];for(var i in V){JH.push(this.aal(G,V[i]))}return JH}else{throw new Error(f6.R.ava)}},
 PB:function(G,V){if(f6.cQ(V)){var fP=[];for(var i in V){fP.push(this.YN(G,V[i]))}return fP}else{throw new Error(f6.R.atD)}},
 HW:function(V){if(f6.cQ(V)){var fP=[];for(var i in V){fP.push(this.aJH(V[i]))}return fP}else{throw new Error(f6.R.aEx)}},
 acI:function(G,V){if(f6.cQ(V)){var ng=[];for(var i in V){ng.push(this.acG(G,V[i]))}return ng}else{throw new Error(f6.R.atJ)}},
 YD:function(V){if(f6.cQ(V)){var ew=[];for(var i in V){ew.push(this.aGN(V[i]))}return ew}else{throw new Error(f6.R.aEy)}},
 aHN:function(V){if(f6.cQ(V)){var hg=[];for(var i in V){hg.push(this.adn(V[i]))}return hg}else{throw new Error(f6.R.aEt)}},
 Ud:function(G,V){if(f6.cQ(V)){var bj=[];for(var i in V){bj.push(this.aDq(G,this.MO(G,V[i])))}return bj}else{throw new Error(f6.R.aDs)}},
 SM:function(G,H){var aB=this;var aw={ai:null,du:null,eI:null,ac:null,de:null,ca:null};return new Promise(function(CO,Bu){aB.iJ.bQ.fh(G,H).then(function(aM){return new Promise(function(cC,aW){try{if(typeof aM.account!=f6.L.K){aw.ai=aB.Df(aB.MO(G,aM.account));aw.du=aB.Ej(aB.Ok(G,aM.account.pendingOrders));aw.eI=aB.Ql(aB.Ok(G,aM.account.cancelledOrders));aw.de=aB.Lp(aB.PB(G,aM.account.closedTrades));aw.ac=aB.DI(aB.PB(G,aM.account.openTrades));aw.ca=aB.zL(aB.HW(aM.account.transferFundRecs));cC()}else{f6.az(f6.R.NL);f6.gE(f6.R.NL);aW()}}catch(e){f6.az(e.message);f6.gE(e.message);aW()}})}).then(function(){CO(aw)}).catch(function(){Bu()})})},
 AS:function(V){if(f6.cQ(V)){var bn=[];for(var i in V){var bm=V[i];if(typeof bm.displayName==f6.L.C&&typeof bm.symbolName==f6.L.C&&typeof bm.basicCurrency==f6.L.C&&typeof bm.tradableSymbol==f6.L.C&&f6.bI(bm.toFixed)&&typeof bm.toFixed!=f6.L.C&&f6.bI(bm.cyBuySwap)&&typeof bm.cyBuySwap!=f6.L.C&&f6.bI(bm.cySellSwap)&&typeof bm.cySellSwap!=f6.L.C&&f6.bI(bm.trdBuySwap)&&typeof bm.trdBuySwap!=f6.L.C&&f6.bI(bm.trdSellSwap)&&typeof bm.trdSellSwap!=f6.L.C&&f6.bI(bm.leverage)&&typeof bm.leverage!=f6.L.C&&f6.bI(bm.lotsLimit)&&typeof bm.lotsLimit!=f6.L.C&&f6.bI(bm.cyBuyOpnCmmssn)&&typeof bm.cyBuyOpnCmmssn!=f6.L.C&&f6.bI(bm.cyBuyClsdCmmssn)&&typeof bm.cyBuyClsdCmmssn!=f6.L.C&&f6.bI(bm.cySellOpnCmmssn)&&typeof bm.cySellOpnCmmssn!=f6.L.C&&f6.bI(bm.cySellClsdCmmssn)&&typeof bm.cySellClsdCmmssn!=f6.L.C&&f6.bI(bm.cyBuyOpnCmmssn2)&&typeof bm.cyBuyOpnCmmssn2!=f6.L.C&&f6.bI(bm.cyBuyClsdCmmssn2)&&typeof bm.cyBuyClsdCmmssn2!=f6.L.C&&f6.bI(bm.cySellOpnCmmssn2)&&typeof bm.cySellOpnCmmssn2!=f6.L.C&&f6.bI(bm.cySellClsdCmmssn2)&&typeof bm.cySellClsdCmmssn2!=f6.L.C&&f6.bI(bm.bid)&&typeof bm.bid!=f6.L.C&&f6.bI(bm.ask)&&typeof bm.ask!=f6.L.C&&f6.bI(bm.bid2)&&typeof bm.bid2!=f6.L.C&&f6.bI(bm.ask2)&&typeof bm.ask2!=f6.L.C&&f6.bI(bm.trdBuyOpnCmmssn)&&typeof bm.trdBuyOpnCmmssn!=f6.L.C&&f6.bI(bm.trdBuyClsdCmmssn)&&typeof bm.trdBuyClsdCmmssn!=f6.L.C&&f6.bI(bm.trdSellOpnCmmssn)&&typeof bm.trdSellOpnCmmssn!=f6.L.C&&f6.bI(bm.trdSellClsdCmmssn)&&typeof bm.trdSellClsdCmmssn!=f6.L.C&&f6.bI(bm.lotsMinLimit)&&typeof bm.lotsMinLimit!=f6.L.C&&f6.bI(bm.lotsStep)&&typeof bm.lotsStep!=f6.L.C&&f6.bI(bm.limitStopMin)&&typeof bm.limitStopMin!=f6.L.C&&f6.bI(bm.spread)&&typeof bm.spread!=f6.L.C){if(typeof bm.bSpecialDay==f6.L.fI){if(bm.bSpecialDay){if(!f6.by(bm.specialDay)||typeof bm.specialDay==f6.L.C||bm.specialDay<f6.mx.HC||bm.specialDay>f6.mx.LT){throw new Error(f6.R.pN)}}else{bm.specialDay=null}}else{throw new Error(f6.R.pN)}bn.push({bJ:bm.symbolName,bs:bm.displayName,eH:bm.basicCurrency,jA:bm.tradableSymbol,bG:bm.toFixed,LV:bm.cyBuySwap,LL:bm.cySellSwap,Ps:bm.trdBuySwap,QG:bm.trdSellSwap,EA:bm.bSpecialDay,zu:bm.specialDay,mv:bm.leverage,uH:bm.lotsLimit,KC:bm.cyBuyOpnCmmssn,Mb:bm.cyBuyClsdCmmssn,KS:bm.cySellOpnCmmssn,Mu:bm.cySellClsdCmmssn,azA:bm.cyBuyOpnCmmssn2,aAR:bm.cyBuyClsdCmmssn2,awI:bm.cySellOpnCmmssn2,awj:bm.cySellClsdCmmssn2,cL:bm.bid,dR:bm.ask,aPs:bm.bid2,azc:bm.ask2,afn:bm.trdBuyOpnCmmssn,aeW:bm.trdBuyClsdCmmssn,adu:bm.trdSellOpnCmmssn,acR:bm.trdSellClsdCmmssn,rZ:bm.lotsMinLimit,re:bm.lotsStep,qa:bm.limitStopMin,fC:bm.spread})}else{throw new Error(f6.R.pN)}}return bn}else{throw new Error(f6.R.pN)}},
 vf:function(G,H){var aB=this;return new Promise(function(cC,aW){aB.iJ.bQ.xs(G,H,{}).then(function(aM){try{var aV=typeof aM.currency==f6.L.C?aM.currency:f6.IC(G);var bn=aB.AS(aM.instruments);cC({aV:aV,bn:bn})}catch(e){f6.az(e.message);f6.gE(e.message);aW()}}).catch(function(){aW()})})},
 Dn:function(G,H,wf){var aB=this;var aP={bj:null,ds:null,gQ:null,ca:null,bn:null,hg:null};return new Promise(function(CO,Bu){aB.iJ.Da.fh(G,H,wf).then(function(aM){return new Promise(function(cC,aW){try{aP.bj=aB.Ud(wf,aM.accounts);aP.ds=aB.NG(aB.acI(wf,aM.positions));aP.gQ=aB.NB(aB.acI(wf,aM.groupedPositions));aP.bn=aB.AS(aM.instruments);aP.ca=aB.zL(aB.HW(aM.transferFundRecs));aP.ew=aB.CY(aB.YD(aM.ers));aP.hg=aB.Wc(aB.aHN(aM.brokers));cC()}catch(e){f6.az(e.message);f6.gE(e.message);aW()}})}).then(function(){CO(aP)}).catch(function(){Bu()})})},
 aKg:function(G,V){var sc=this.qI(G,V);if(sc.T==null||sc.G==null||sc.H==null||sc.Gl==null||sc.uW==null||sc.IV==null||sc.bV==null){throw new Error(f6.R.mY)}return{T:sc.T,G:sc.G,H:sc.H,ik:sc.Gl,eJ:sc.uW,fc:0.0,nF:null,iA:false,gY:sc.IV,lJ:0.0,mJ:0.0,mT:0.0,mj:0.0,cL:0.0,dR:0.0,mw:sc.bV*1000}},
 aJh:function(G,V){var Gs=this.qI(G,V);if(Gs.T==null||Gs.G==null||Gs.H==null){throw new Error(f6.R.mY)}return{T:Gs.T,G:Gs.G,H:Gs.H}},
 aJv:function(G,V){var vB=this.qI(G,V);var nF=null;if(vB.Gl!=null){var ajg=vB.Gl.split(":::");if(ajg.length==2){nF=ajg[1]}}if(vB.T==null||vB.G==null||vB.H==null||nF==null||vB.bV==null){throw new Error(f6.R.mY)}return{T:vB.T,G:vB.G,H:vB.H,nF:nF,mw:vB.bV*1000}},
 aJN:function(G,V){var vO=this.qI(G,V);var iA=null;if(vO.cJ==f6.L.gM){iA=true}else if(vO.cJ==f6.L.lV){iA=false}if(vO.T==null||vO.G==null||vO.H==null||iA==null||vO.bV==null){throw new Error(f6.R.mY)}return{T:vO.T,G:vO.G,H:vO.H,iA:iA,mw:vO.bV*1000}},
 aKA:function(G,V){var uI=this.qI(G,V);var jv=uI.cJ.split(":::");var lJ=null;var mJ=null;var mT=null;var mj=null;var cL=null;var dR=null;for(var i=0;i<jv.length;i += 1){if(f6.bI(jv[i])){if(i==0){lJ=parseFloat(jv[i])}else if(i==1){mJ=parseFloat(jv[i])}else if(i==2){mT=parseFloat(jv[i])}else if(i==3){mj=parseFloat(jv[i])}else if(i==4){cL=parseFloat(jv[i])}else if(i==5){dR=parseFloat(jv[i])}else{throw new Error(f6.R.mY)}}else{throw new Error(f6.R.mY)}}if(uI.T==null||uI.G==null||uI.H==null||uI.IV==null||lJ==null||mJ==null||mT==null||mj==null||cL==null||dR==null||uI.bV==null){throw new Error(f6.R.mY)}return{T:uI.T,G:uI.G,H:uI.H,gY:uI.IV,lJ:lJ,mJ:mJ,mT:mT,mj:mj,cL:cL,dR:dR,mw:uI.bV*1000}},
 aSq:function(uY){var G=uY.G,H=uY.H,Fp=uY.Fp;var aB=this;return new Promise(function(cC,aW){aB.iJ.vH.ail(G,H,{id:Fp+""}).then(function(aM){if(f6.cQ(aM.transactions)){for(var i in aM.transactions){aB.Zn(G,H,aM.transactions[i])}cC()}else{f6.az(f6.R.NM);f6.gE(f6.R.NM);aW()}}).catch(function(){aW()})})},
 Eu:function(G,H){var aB=this;this.iJ.Da.uT(G,H,{},function(V){var aA=null;var cT=null;try{if(typeof V.type!=f6.L.K&&V.type){if(V.type==aB.dU.qE){aA={};cT=f6.dh.qE}else if(V.type==aB.dU.CP&&typeof V.reason!=f6.L.K&&(V.reason==aB.nD.wI||V.reason==aB.nD.sd||V.reason==aB.nD.Gj)){aA=aB.Uf(G,V);if(typeof V.er==f6.L.dk){var ew=aB.CY(aB.YD([V.er]));aA.pI=ew.length==1?ew[0]:null}cT=f6.dh.bc}else if(V.type==aB.dU.CP&&typeof V.reason!=f6.L.K&&(V.reason==aB.nD.Qe||V.reason==aB.nD.Fs||V.reason==aB.nD.FO)){aA=aB.Sa(G,V);if(typeof V.er==f6.L.dk){var ew=aB.CY(aB.YD([V.er]));aA.pI=ew.length==1?ew[0]:null}cT=f6.dh.cN}else if(V.type==aB.dU.qf){aA=aB.vD(V);cT=f6.dh.vs;throw new Error(f6.R.apn+"("+G+", "+aA.H+")")}else if(V.type==aB.dU.sz){aA=aB.vD(V);cT=f6.dh.vs;throw new Error(f6.R.amz+"("+G+", "+aA.H+")")}else if(V.type==aB.dU.Ah){aA=aB.apz(G,V);cT=f6.dh.Ah}else if(V.type==aB.dU.Rg){aA=aB.aJN(G,V);cT=f6.dh.Rg}else if(V.type==aB.dU.TX){aA=aB.aKA(G,V);cT=f6.dh.TX}else if(V.type==aB.dU.ra){aA=aB.aKg(G,V);cT=f6.dh.ra}else if(V.type==aB.dU.tc){aA=aB.aJh(G,V);cT=f6.dh.tc}else if(V.type==aB.dU.PE){aA=aB.aJv(G,V);cT=f6.dh.PE}else if(V.type==aB.dU.qM){aA=aB.aoY(G,V);cT=f6.dh.qM}else if(V.type==aB.dU.avM){aA=aB.Pk(V);cT=f6.dh.ajH}else if(V.type==aB.dU.uh){aA={};cT=f6.dh.uh}}}catch(e){f6.az(JSON.stringify(V)+" "+e.message);f6.gE(e.message)}if(aA!=null){aB.hA.VT({G:G,H:H,cT:cT,aA:aA})}})},
 zM:function(G,H){this.iJ.Da.ur(G,H)}
};f6o.jH[f6.oR.zt]={
 iJ:null,
 aaq:function(iJ){this.iJ=iJ},
 hA:null,
 agC:function(hA){this.hA=hA},
 aAW:[],
 bx:function(G,H,gn){return G+":::"+H+":::"+gn},
 dU:{qE:"HEARTBEAT",wI:"MARKET_ORDER",sd:"LIMIT_ORDER",Gj:"STOP_ORDER",Fs:"TAKE_PROFIT_ORDER",FO:"STOP_LOSS_ORDER",QT:"ORDER_TRIGGERED",CP:"ORDER_FILL",nv:"ORDER_CANCEL",aaI:"DAILY_FINANCING",oJ:"MARGIN_NOT_ENOUGH_REJECTED",rM:"MARKET_REJECTED",sz:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",qf:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",Ah:"TRANSFER_FUNDS",RC:"SYNC_BALANCE",ra:"ACCOUNT_CREATED",tc:"ACCOUNT_REMOVED"},
 nD:{aKF:"CLIENT_ORDER",wI:"MARKET_ORDER",Qe:"MARKET_ORDER_TRADE_CLOSE",sd:"LIMIT_ORDER",Gj:"STOP_ORDER",Fs:"TAKE_PROFIT_ORDER",FO:"STOP_LOSS_ORDER",QT:"ORDER_TRIGGERED",aAc:"CLOSEOUT",aOb:"SHOP_ORDER",abL:"DASHBOARD_ORDER",abe:"CLIENT_REQUEST"},
 hz:{lb:"PENDING",wW:"FILLED",wQ:"TRIGGERED",su:"CANCELLED",wE:"REPLACED",oJ:"MARGIN_NOT_ENOUGH_REJECTED",rM:"MARKET_REJECTED",sz:"BALANCE_NOT_ENOUGH_TO_WITHDRAW",qf:"MARGIN_NOT_ENOUGH_TO_WITHDRAW",sv:"ALL"},
 mQ:{eP:"OPEN",qi:"CLOSED",wb:"CLOSE_WHEN_TRADEABLE",wC:"TRANSFERRED",sv:"ALL"},
 SC:{sv:"ALL"},
 aQN:{dN:"B",fk:"S"},
 iE:{Dp:"MARKET",uU:"LIMIT",zX:"STOP",cB:"TAKE_PROFIT",cz:"STOP_LOSS"},
 aQu:500,
 aCN:500,
 adR:function(V){if(typeof V.state==f6.L.C){if(V.state==this.hz.lb){return f6.ek.lb}else if(V.state==this.hz.wW&&typeof V.tradeOpenedID!=f6.L.K){return f6.ek.OX}else if(V.state==this.hz.wW&&typeof V.tradeClosedIDs!=f6.L.K){return f6.ek.PN}else if(V.state==this.hz.wQ){return f6.ek.wQ}else if(V.state==this.hz.su){return f6.ek.su}else if(V.state==this.hz.wE){return f6.ek.wE}else if(V.state==this.hz.oJ){return f6.ek.oJ}else if(V.state==this.hz.rM){return f6.ek.rM}else if(V.state==this.hz.sz){return f6.ek.sz}else if(V.state==this.hz.qf){return f6.ek.qf}else{return V.state+""}}else{return null}},
 OE:function(V){if(typeof V.state==f6.L.C){if(V.state==this.mQ.eP){return f6.jJ.eP}else if(V.state==this.mQ.qi){return f6.jJ.qi}else if(V.state==this.mQ.wb){return f6.jJ.wb}else if(V.state==this.mQ.wC){return f6.jJ.wC}else{return V.state+""}}else{return null}},
 aIF:function(iZ){if(iZ==f6.ek.lb){return this.hz.lb}else if(iZ==f6.ek.wW){return this.hz.wW}else if(iZ==f6.ek.wQ){return this.hz.wQ}else if(iZ==f6.ek.su){return this.hz.su}else if(iZ==f6.ek.wE){return this.hz.wE}else if(iZ==f6.ek.oJ){return this.hz.oJ}else if(iZ==f6.ek.rM){return this.hz.rM}else if(iZ==f6.ek.sz){return this.hz.sz}else if(iZ==f6.ek.qf){return this.hz.qf}else{return this.hz.sv}},
 aKt:function(iZ){if(iZ==f6.jJ.eP){return this.mQ.eP}else if(iZ==f6.jJ.qi){return this.mQ.qi}else if(iZ==f6.jJ.wb){return this.mQ.wb}else if(iZ==f6.jJ.wC){return this.mQ.wC}else{return this.mQ.sv}},
 aal:function(G,V){var ce=f6.na(G);var cb=this.adR(V);if(cb==f6.ek.lb){return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:null,vd:null,sx:null,bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?Math.abs((parseFloat(V.units)/ce)):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:null}}else if(cb==f6.ek.OX){return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:typeof V.fillingTransactionID==f6.L.C?V.fillingTransactionID:null,vd:f6.bI(V.filledTime)?parseFloat(V.filledTime):null,sx:null,bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?(parseFloat(V.units)/ce):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:typeof V.Ur==f6.L.C?V.Ur:null}}else if(cb==f6.ek.PN){return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:typeof V.fillingTransactionID==f6.L.C?V.fillingTransactionID:null,vd:f6.bI(V.filledTime)?parseFloat(V.filledTime):null,sx:f6.cQ(V.tradeClosedIDs)?V.tradeClosedIDs:[],bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?(parseFloat(V.units)/ce):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:null}}else if(cb==f6.ek.su){return{vo:typeof V.id==f6.L.C?V.id:null,mU:f6.bI(V.createTime)?parseFloat(V.createTime):null,Cy:typeof V.cancellingTransactionID==f6.L.C?V.cancellingTransactionID:null,vd:f6.bI(V.cancelledTime)?parseFloat(V.cancelledTime):null,sx:null,bJ:typeof V.instrument==f6.L.C?V.instrument:null,bO:f6.bI(V.units)?(parseFloat(V.units)/ce):null,cb:cb,ct:typeof V.type==f6.L.C?V.type:null,De:typeof V.positionFill==f6.L.C?V.positionFill:null,Bo:typeof V.timeInForce==f6.L.C?V.timeInForce:null,BC:null}}},
 YN:function(G,V){var ce=f6.na(G);return{T:typeof V.id==f6.L.C?V.id:null,cb:this.OE(V),bJ:typeof V.instrument==f6.L.C?V.instrument:null,eC:f6.bI(V.openTime)?parseFloat(V.openTime):null,bu:f6.bI(V.price)?parseFloat(V.price):null,io:f6.bI(V.currentUnits)?(parseFloat(V.currentUnits)/ce):null,iv:f6.bI(V.initialUnits)?(parseFloat(V.initialUnits)/ce):null,cW:f6.bI(V.financing)?parseFloat(V.financing):null,fZ:f6.bI(V.realizedPL)?parseFloat(V.realizedPL):null,gw:0.0,ck:f6.bI(V.commission)?parseFloat(V.commission):null,sx:f6.cQ(V.tradeClosedIDs)?V.tradeClosedIDs:[]}},

 acG:function(G,V){
  var ce=f6.na(G);var IK,TM,Tw,Yy,Jx,Jy;if(typeof V.long!=f6.L.K){IK=f6.bI(V.long.averagePrice)?parseFloat(V.long.averagePrice):null;TM=f6.bI(V.long.pl)?parseFloat(V.long.pl):null;Tw=f6.bI(V.long.resettablePL)?parseFloat(V.long.resettablePL):null;Yy=f6.cQ(V.long.tradeIDs)?V.long.tradeIDs.join(","):null;Jx=f6.bI(V.long.units)?(parseFloat(V.long.units)/ce):null;Jy=f6.bI(V.long.unrealizedPL)?parseFloat(V.long.unrealizedPL):null}var He,aeQ,aeE,aed,Hd,Io;if(typeof V.short!=f6.L.K){He=f6.bI(V.short.averagePrice)?parseFloat(V.short.averagePrice):null;aeQ=f6.bI(V.short.pl)?parseFloat(V.short.pl):null;aeE=f6.bI(V.short.resettablePL)?parseFloat(V.short.resettablePL):null;aed=f6.cQ(V.short.tradeIDs)?V.short.tradeIDs.join(","):null;Hd=f6.bI(V.short.units)?(parseFloat(V.short.units)/ce):null;Io=f6.bI(V.short.unrealizedPL)?parseFloat(V.short.unrealizedPL):null}return{bJ:typeof V.instrument==f6.L.C?V.instrument:null,ck:f6.bI(V.commission)?parseFloat(V.commission):null,fc:f6.bI(V.pl)?parseFloat(V.pl):null,ET:f6.bI(V.resettablePL)?parseFloat(V.resettablePL):null,gw:f6.bI(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,IK:IK,TM:TM,Tw:Tw,Yy:Yy,Jx:Jx,Jy:Jy,He:He,aeQ:aeQ,aeE:aeE,aed:aed,Hd: -Hd,Io:Io}
 },

 MO:function(G,V){return{fg:f6.bI(V.NAV)?parseFloat(V.NAV):null,aCy:typeof V.alias==f6.L.C?V.alias:null,eJ:f6.bI(V.balance)?parseFloat(V.balance):null,ck:f6.bI(V.commission)?parseFloat(V.commission):null,aBg:f6.by(V.createdByUserID)?parseInt(V.createdByUserID, 10):null,aCo:f6.bI(V.createdTime)?parseFloat(V.createdTime):null,aV:typeof V.currency==f6.L.C?V.currency:f6.IC(G),rk:typeof V.hedgingEnabled==f6.L.fI?V.hedgingEnabled:null,T:typeof V.id==f6.L.C?V.id:null,gn:typeof V.lastTransactionID==f6.L.C?V.lastTransactionID:null,jm:f6.bI(V.marginAvailable)?parseFloat(V.marginAvailable):null,aET:f6.bI(V.marginCallMarginUsed)?parseFloat(V.marginCallMarginUsed):null,aGv:f6.bI(V.marginCallPercent)?parseFloat(V.marginCallPercent):null,aFl:f6.bI(V.marginCloseoutMarginUsed)?parseFloat(V.marginCloseoutMarginUsed):null,aFx:f6.bI(V.marginCloseoutNAV)?parseFloat(V.marginCloseoutNAV):null,aFV:f6.bI(V.marginCloseoutPercent)?parseFloat(V.marginCloseoutPercent):null,aGG:f6.bI(V.marginCloseoutPositionValue)?parseFloat(V.marginCloseoutPositionValue):null,aFY:f6.bI(V.marginCloseoutUnrealizedPL)?parseFloat(V.marginCloseoutUnrealizedPL):null,aFM:f6.bI(V.marginRate)?parseFloat(V.marginRate):null,hh:f6.bI(V.marginUsed)?parseFloat(V.marginUsed):null,aFj:(f6.by(V.openPositionCount)&&typeof V.openPositionCount!=f6.L.C)?V.openPositionCount:null,aGC:(f6.by(V.openTradeCount)&&typeof V.openTradeCount!=f6.L.C)?V.openTradeCount:null,aRh:(f6.by(V.pendingOrderCount)&&typeof V.pendingOrderCount!=f6.L.C)?V.pendingOrderCount:null,fc:f6.bI(V.pl)?parseFloat(V.pl):null,aPH:f6.bI(V.positionValue)?parseFloat(V.positionValue):null,ET:f6.bI(V.resettablePL)?parseFloat(V.resettablePL):null,gw:f6.bI(V.unrealizedPL)?parseFloat(V.unrealizedPL):null,avZ:f6.bI(V.withdrawalLimit)?parseFloat(V.withdrawalLimit):null,bG:f6.bI(V.toFixed)?parseFloat(V.toFixed):f6.uD(G),mO:f6.bI(V.marginCallLevel)?parseFloat(V.marginCallLevel):null,ri:f6.bI(V.marginCloseoutLevel)?parseFloat(V.marginCloseoutLevel):null}},
 abB:function(V){var mo={T:typeof V.id==f6.L.C?V.id:null,bV:f6.bI(V.time)?parseFloat(V.time):null};if(mo.T==null||mo.bV==null){throw new Error(f6.R.mY)}return{T:mo.T,bV:mo.bV}},
 qI:function(G,V){return{uW:f6.bI(V.accountBalance)?parseFloat(V.accountBalance):null,H:typeof V.accountID==f6.L.C?V.accountID:null,aKH:typeof V.batchID==f6.L.C?V.batchID:null,ck:f6.bI(V.commission)?parseFloat(V.commission):null,cW:f6.bI(V.financing)?parseFloat(V.financing):null,aHV:null,T:typeof V.id==f6.L.C?V.id:null,bJ:typeof V.instrument==f6.L.C?V.instrument:null,cG:typeof V.orderID==f6.L.C?V.orderID:null,fc:f6.bI(V.pl)?parseFloat(V.pl):null,bu:f6.bI(V.price)?parseFloat(V.price):null,ji:typeof V.reason==f6.L.C?V.reason:null,Gl:typeof V.requestID==f6.L.C?V.requestID:null,bV:f6.bI(V.time)?parseFloat(V.time):null,ct:typeof V.type==f6.L.C?V.type:null,nS:f6.bI(V.units)?parseFloat(V.units):null,bO:f6.bI(V.units)?(parseFloat(V.units)/f6.na(G)):null,IV:f6.by(V.userID)?parseInt(V.userID, 10):null}},
 Uf:function(G,V){var dv=this.qI(G,V);dv.aBM=null;if(dv.T==null||dv.bJ==null||dv.bV==null||dv.bu==null||dv.bO==null||dv.fc==null||dv.ck==null){throw new Error(f6.R.mY)}return{T:dv.T,bJ:dv.bJ,aj:dv.bO>0?f6.ab.dN:f6.ab.fk,eC:dv.bV,dX:dv.bu,io:Math.abs(dv.bO),db:null,cD:null,cW:0.0,ck:dv.ck,gw:0.0}},
 Sa:function(G,V){var dv=this.qI(G,V);dv.amR=null;dv.fz=null;if(f6.cQ(V.tradesClosed)&&V.tradesClosed.length>0){if(typeof V.tradesClosed[0].tradeID==f6.L.C){dv.fz=V.tradesClosed[0].tradeID}}if(dv.T==null||dv.bJ==null||dv.bV==null||dv.bu==null||dv.bO==null||dv.fc==null||dv.fz==null||dv.ck==null){throw new Error(f6.R.mY)}return{T:dv.fz,bJ:dv.bJ,aj:dv.bO<0?f6.ab.dN:f6.ab.fk,eC:null,dX:null,jT:dv.bV,ke:dv.bu,iv:Math.abs(dv.bO),cW:0.0,fZ:dv.fc,ck:dv.ck,apD:dv.T}},
 Pk:function(V){var og={T:typeof V.id==f6.L.C?V.id:null,bV:f6.bI(V.time)?parseFloat(V.time):null};if(og.T==null||og.bV==null){throw new Error(f6.R.mY)}return{T:og.T,bV:og.bV,cW:og.cW}},
 xi:function(G,H){var aB=this;this.iJ.vH.uT(G,H,function(V){var aA=null;var cT=null;try{if(typeof V.type!=f6.L.K&&V.type){if(V.type==aB.dU.qE){}else if(V.type==aB.dU.wI){aA=aB.abB(V);cT=f6.dh.bF;return}else if(V.type==aB.dU.oJ){throw new Error(f6.R.Kf)}else if(V.type==aB.dU.rM){throw new Error(f6.R.anN)}else if(V.type==aB.dU.CP&&typeof V.reason!=f6.L.K&&V.reason==aB.nD.wI){aA=aB.Uf(G,V);cT=f6.dh.bc}else if(V.type==aB.dU.CP&&typeof V.reason!=f6.L.K&&V.reason==aB.nD.Qe){aA=aB.Sa(G,V);cT=f6.dh.cN}else if(V.type==aB.dU.aaI){aA=aB.Pk(V);cT=f6.dh.cW}}}catch(e){f6.az(JSON.stringify(V)+" "+e.message);f6.gE(e.message)}if(aA!=null){aB.hA.ut({G:G,H:H,cT:cT,aA:aA})}})},
 yp:function(G,H){},

 zo:function(df){var G=df.G,H=df.H,bJ=df.bJ,aj=df.aj,bu=df.bu,fL=df.fL,bL=df.bL,cB=df.cB,cz=df.cz,cJ=df.cJ;var aB=this;return new Promise(function(cC,aW){if(true){var ce=f6.na(G);var aEW={
  instrument:bJ,
  units:aj==f6.ab.dN?(bL*ce): -(bL*ce),

  clientExtensions:{
   id:"",
   tag:"",
   comment:cJ
  },

  type:aB.iE.Dp
 };aB.iJ.wT.aqa(G,H,aEW).then(function(aM){cC("")}).catch(function(){aW()})}})},

 wF:function(df){var G=df.G,H=df.H,fz=df.fz,bu=0,Sl=this.SC.sv;var aB=this;return new Promise(function(cC,aW){aB.iJ.vp.ep(G,H,fz,{units:Sl}).then(function(aM){cC("")}).catch(function(){aW()})})},
 Df:function(dY){var ai={eJ:dY.eJ,aV:dY.aV,bG:dY.bG,ck:dY.ck,rk:dY.rk,fc:dY.fc,mO:dY.mO,ri:dY.ri,fg:dY.fg,hh:dY.hh};if(ai.fg!=null&&ai.hh!=null){ai.jm=Math.round(dY.bG*(ai.fg-ai.hh))/dY.bG}else{ai.jm=null}return ai},
 DI:function(nc){var ac=[];for(var i in nc){if(nc[i].cb==f6.jJ.eP&&nc[i].iv!=null&&nc[i].iv!=0&&nc[i].T!=null&&nc[i].bJ!=null&&nc[i].eC!=null&&nc[i].bu!=null&&nc[i].io!=null){ac.push({T:nc[i].T,bJ:nc[i].bJ,aj:nc[i].iv>0?f6.ab.dN:f6.ab.fk,eC:nc[i].eC,dX:nc[i].bu,io:Math.abs(nc[i].io),db:null,cD:null,cW:nc[i].cW,ck:nc[i].ck,gw:0.0})}}ac.sort(function(a,b){return a.eC-b.eC});return ac},
 Lp:function(fP){var de=[];for(var i in fP){if(fP[i].cb==f6.jJ.qi&&fP[i].iv!=null&&fP[i].iv!=0){var jT=null;var ke=null;var Ei=null;var fZ=null;for(var j in fP){if(fP[j].cb==f6.jJ.qi&&fP[j].sx.length>0&&fP[j].sx[0]+""===fP[i].T){jT=fP[j].eC;ke=fP[j].bu;Ei=fP[j].ck;fZ=fP[j].fZ;break}}if(fP[i].T!=null&&fP[i].bJ!=null&&fP[i].eC!=null&&fP[i].bu!=null&&jT!=null&&ke!=null&&Ei!=null&&fP[i].cW!=null&&fZ!=null&&fP[i].ck!=null){de.push({T:fP[i].T,bJ:fP[i].bJ,aj:fP[i].iv>0?f6.ab.dN:f6.ab.fk,eC:fP[i].eC,dX:fP[i].bu,jT:jT,ke:ke,iv:Math.abs(fP[i].iv),cW:fP[i].cW,fZ:fZ,ck:fP[i].ck+Ei})}}}de.sort(function(a,b){return a.eC-b.eC});return de},
 Ej:function(Nb){return Nb},
 Ok:function(G,V){if(f6.cQ(V)){var JH=[];for(var i in V){JH.push(this.aal(G,V[i]))}return JH}else{throw new Error(f6.R.ava)}},
 PB:function(G,V){if(f6.cQ(V)){var fP=[];for(var i in V){fP.push(this.YN(G,V[i]))}return fP}else{throw new Error(f6.R.atD)}},
 acI:function(G,V){if(f6.cQ(V)){var ng=[];for(var i in V){ng.push(this.acG(G,V[i]))}return ng}else{throw new Error(f6.R.atJ)}},
 SM:function(G,H){var aB=this;var aw={ai:null,du:null,ac:null,de:null};return new Promise(function(CO,Bu){aB.iJ.bQ.fh(G,H).then(function(aM){return new Promise(function(cC,aW){try{if(typeof aM.account!=f6.L.K){aw.ai=aB.Df(aB.MO(G,aM.account));aw.du=aB.Ej(aB.Ok(G,aM.account.orders));aw.de=[];aw.ac=aB.DI(aB.PB(G,aM.account.trades));cC()}else{f6.az(f6.R.NL);f6.gE(f6.R.NL);aW()}}catch(e){f6.az(e.message);f6.gE(e.message);aW()}})}).then(function(){CO(aw)}).catch(function(){Bu()})})},
 AS:function(G,V){if(f6.cQ(V)){var bn=[];var ce=f6.na(G);for(var i in V){if(typeof V[i].displayName==f6.L.C&&typeof V[i].name==f6.L.C&&f6.bI(V[i].displayPrecision)&&typeof V[i].displayPrecision!=f6.L.C&&f6.bI(V[i].marginRate)&&typeof V[i].marginRate==f6.L.C&&f6.bI(V[i].maximumOrderUnits)&&typeof V[i].maximumOrderUnits==f6.L.C){var ax=V[i].name.split("_");if(ax.length!=2){throw new Error(f6.R.pN)}bn.push({bJ:V[i].name,bs:V[i].displayName,eH:ax[1],jA:ax[0],bG:Math.pow(10,V[i].displayPrecision),LV:0.0,LL:0.0,Ps:0.0,QG:0.0,EA:true,zu:3,mv:1.0/parseFloat(V[i].marginRate),uH:parseFloat(V[i].maximumOrderUnits)/ce,KC:0.0,Mb:0.0,KS:0.0,Mu:0.0,afn:0.0,aeW:0.0,adu:0.0,acR:0.0,rZ:parseFloat(V[i].minimumTradeSize)/ce,re:parseFloat(V[i].minimumTradeSize)/ce,qa:0.0})}else{throw new Error(f6.R.pN)}}return bn}else{throw new Error(f6.R.pN)}},
 vf:function(G,H){var aB=this;return new Promise(function(cC,aW){aB.iJ.bQ.xs(G,H,{}).then(function(aM){try{cC(aB.AS(G,aM.instruments))}catch(e){f6.az(e.message);f6.gE(e.message);aW()}}).catch(function(){aW()})})}
};f6o.fo={};f6o.fo.kl=function(rK,jw,lE,rr,dz){return new Promise(function(cC,aW){try{var dO=new XMLHttpRequest();if(lE===f6.ae.gH||lE===f6.ae.Af){dO.open(lE,rK+jw,true);dO.setRequestHeader(f6.ae.arp,f6.ae.ajB);dO.setRequestHeader(f6.ae.Ic,f6.ae.AU+" "+dz);dO.send(JSON.stringify(rr))}else if(lE===f6.ae.fh){dO.open(lE,rK+jw+"?"+f6.Mo(rr),true);dO.setRequestHeader(f6.ae.Ic,f6.ae.AU+" "+dz);dO.send(null)}else{throw new Error(f6.R.JS)}dO.onreadystatechange=function(){if(dO.readyState==4){if(dO.status==200||dO.status==0){try{if(dO.responseText!=""){cC(JSON.parse(dO.responseText))}else{cC(dO.responseText)}}catch(e){f6.az(e.message);f6.gE(e.message);aW()}}else{f6.az(dO.status+" "+dO.responseText);f6.gE(dO.status+" "+dO.responseText);aW()}}};dO.onerror=function(){f6.az(f6.R.Kc);aW()}}catch(e){f6.az(e.message);f6.gE(e.message);aW()}})};f6o.fo.qF=[];f6o.fo.uT=function(qH,jw,lE,rr,aF){try{if(lE===f6.ae.fh){if(! !self.EventSource){this.ur(qH,jw);this.qF[qH+jw]=new self.EventSource(qH+jw+"?"+f6.Mo(rr),{withCredentials:true});this.qF[qH+jw].addEventListener(f6.cS.lC,function(e){try{aF(JSON.parse(e.data))}catch(e){f6.az(e.message);f6.gE(e.message)}},false);this.qF[qH+jw].addEventListener(f6.cS.eP,function(e){},false);this.qF[qH+jw].addEventListener(f6.cS.mk,function(e){if(e.readyState==self.EventSource.CLOSED){}f6.az(f6.R.Kc+" ("+qH+jw+")");aF({type:f6.dh.uh})},false)}else{}}else{throw new Error(f6.R.JS)}}catch(e){f6.az(e.message);f6.gE(e.message)}};f6o.fo.ur=function(rK,jw){if(typeof this.qF[rK+jw]!=f6.L.K){this.qF[rK+jw].close();delete this.qF[rK+jw]}};f6o.fo.bQ={};f6o.fo.bQ.xs=function(G,H,LJ){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/instruments",f6.ae.fh,LJ,f6.iL(G,H))};f6o.fo.bQ.fh=function(G,H){return f6o.fo.kl(f6.fw(G),"/accounts/"+H,f6.ae.fh,{},f6.iL(G,H))};f6o.fo.vH={};f6o.fo.vH.UW=function(G,H,jZ){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/transactions",f6.ae.fh,jZ,f6.iL(G,H))};f6o.fo.vH.ail=function(G,H,jZ){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/transactions/sinceid",f6.ae.fh,jZ,f6.iL(G,H))};f6o.fo.vH.fh=function(G,H,aBW){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/transactions/"+aBW,f6.ae.fh,{},f6.iL(G,H))};f6o.fo.vH.uT=function(G,H,jZ,aF){f6o.fo.uT(f6.NX(G),"/accounts/"+H+"/transactions/stream",f6.ae.fh,{aH:f6.ae.AU+" "+f6.iL(G,H)},aF)};f6o.fo.vH.ur=function(G,H){f6o.fo.ur(f6.NX(G),"/accounts/"+H+"/transactions/stream")};f6o.fo.vp={};f6o.fo.vp.UW=function(G,H,jZ){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/trades",f6.ae.fh,jZ,f6.iL(G,H))};f6o.fo.vp.aCr=function(G,H){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/openTrades",f6.ae.fh,{},f6.iL(G,H))};f6o.fo.vp.fh=function(G,H,Jr){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/trades/"+Jr,f6.ae.fh,{},f6.iL(G,H))};f6o.fo.vp.ep=function(G,H,Jr,afi){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/trades/"+Jr+"/close",f6.ae.Af,afi,f6.iL(G,H))};f6o.fo.vp.aEQ=function(G,H,Jr,JP){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/trades/"+Jr+"/orders",f6.ae.Af,JP,f6.iL(G,H))};f6o.fo.wT={};f6o.fo.wT.UW=function(G,H,jZ){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/orders",f6.ae.fh,jZ,f6.iL(G,H))};f6o.fo.wT.aRO=function(G,H){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/pendingOrders",f6.ae.fh,{},f6.iL(G,H))};f6o.fo.wT.fh=function(G,H,Je){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/orders/"+Je,f6.ae.fh,{},f6.iL(G,H))};f6o.fo.wT.aqa=function(G,H,JP){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/orders",f6.ae.gH,JP,f6.iL(G,H))};f6o.fo.wT.aGS=function(G,H,Je){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/orders/"+Je+"/cancel",f6.ae.Af,{},f6.iL(G,H))};f6o.fo.wT.Bk=function(G,H,Je,JP){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/orders/"+Je,f6.ae.Af,JP,f6.iL(G,H))};f6o.fo.Nl={};f6o.fo.Nl.UW=function(G,H){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/positions",f6.ae.fh,{},f6.iL(G,H))};f6o.fo.Nl.aCr=function(G,H){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/openPositions",f6.ae.fh,{},f6.iL(G,H))};f6o.fo.Nl.fh=function(G,H,afI){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/positions/"+afI,f6.ae.fh,{},f6.iL(G,H))};f6o.fo.Nl.ep=function(G,H,afI,afi){return f6o.fo.kl(f6.fw(G),"/accounts/"+H+"/positions/"+afI+"/close",f6.ae.Af,afi,f6.iL(G,H))};
